//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Jun  3 2014 10:55:11).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSPopUpButton.h"

@class TArrangeByMenuController;

@interface TArrangeByPopUp : NSPopUpButton
{
    TArrangeByMenuController *_arrangeByMenuController;
}

@property(retain, nonatomic) TArrangeByMenuController *arrangeByMenuController; // @synthesize arrangeByMenuController=_arrangeByMenuController;
- (void)mouseDown:(id)arg1;
- (void)dealloc;

@end

