//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Jun  3 2014 10:55:11).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@interface TBVDSBulkConfigChangedState : NSObject
{
    _Bool _delegateChanged;
    _Bool _sortByChanged;
    _Bool _groupByChanged;
    _Bool _checkChildrenForTagsChanged;
    function_f9feaa7d _sortByCompletionHandler;
}

@property function_f9feaa7d sortByCompletionHandler; // @synthesize sortByCompletionHandler=_sortByCompletionHandler;
@property _Bool checkChildrenForTagsChanged; // @synthesize checkChildrenForTagsChanged=_checkChildrenForTagsChanged;
@property _Bool groupByChanged; // @synthesize groupByChanged=_groupByChanged;
@property _Bool sortByChanged; // @synthesize sortByChanged=_sortByChanged;
@property _Bool delegateChanged; // @synthesize delegateChanged=_delegateChanged;
- (id).cxx_construct;
- (void).cxx_destruct;

@end

