//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Jun  3 2014 10:55:11).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "TUpdateLayerView.h"

@class NSPasteboard;

@interface TClipView : TUpdateLayerView
{
    struct TNSRef<NSPasteboard *> _pasteboard;
    struct TNSRef<TScrollView *> _textScrollView;
    struct TNSRef<TClipImageView *> _imageView;
    _Bool _canSelectAndCopy;
}

+ (struct __CFString *)displayableUTIForPasteboard:(id)arg1;
@property _Bool canSelectAndCopy; // @synthesize canSelectAndCopy=_canSelectAndCopy;
- (id).cxx_construct;
- (void).cxx_destruct;
@property(readonly) struct CGSize optimalSize;
- (void)update;
@property(retain) NSPasteboard *pasteboard;
- (void)initCommon;

@end

