//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Jun  3 2014 10:55:11).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSSliderCell.h"

@interface TNotifyingSliderCell : NSSliderCell
{
}

- (BOOL)startTrackingAt:(struct CGPoint)arg1 inView:(id)arg2;
- (void)stopTracking:(struct CGPoint)arg1 at:(struct CGPoint)arg2 inView:(id)arg3 mouseIsUp:(BOOL)arg4;

@end

