//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Jun  3 2014 10:55:11).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "TPropertyTextFieldController.h"

@class NSColor;

@interface TPropertyContentSizeController : TPropertyTextFieldController
{
    NSColor *_textColor;
}

@property(retain) NSColor *textColor; // @synthesize textColor=_textColor;
- (void)flush;
- (id)extractValueFromNodes:(const struct TFENodeVector *)arg1;
- (void)dealloc;
- (void)initCommon;

@end

