//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Jun  3 2014 10:55:11).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

#import "TCoalescingNodeObserverProtocol.h"

@class NSString;

@interface TPromiseDragReceiver : NSObject <TCoalescingNodeObserverProtocol>
{
    struct function<void (const TFENode &)> _promiseDragNodeAddedCallback;
    struct function<void (const TFENodeVector &, const TError &)> _promiseDragCompletionCallback;
    struct TCoalescingNodeObserverCocoaBridge *_nodeObserver;
    struct TFENode _dropTargetNode;
    struct TStringVector _rawNamesOfPendingPromisedNodes;
    struct TPromiseDragReceiverThread *_receiverThread;
}

- (id).cxx_construct;
- (void).cxx_destruct;
- (void)coalescingNodeObserver:(struct TCoalescingNodeObserver *)arg1 nodesChanged:(const vector_614ab7ad *)arg2 inObservedNode:(const struct TFENode *)arg3;
- (void)coalescingNodeObserver:(struct TCoalescingNodeObserver *)arg1 nodesAdded:(const struct TFENodeVector *)arg2 toObservedNode:(const struct TFENode *)arg3;
- (void)coalescingNodeObserver:(struct TCoalescingNodeObserver *)arg1 openSyncCompleted:(const struct TFENode *)arg2;
- (void)waitForPromisedNodesAsync;
- (void)receivePromiseDrag:(struct TDropOperation *)arg1 nodeAddedCallback:(CDUnknownBlockType)arg2 completionCallback:(CDUnknownBlockType)arg3;
- (void)dealloc;
- (id)initWithDropTargetNode:(const struct TFENode *)arg1;
- (id)init;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

