//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Jun  3 2014 10:55:11).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "TPaneController.h"

@class NSTextField, TSidebarPrefsBG, TSidebarPrefsItem;

@interface TSidebarPaneController : TPaneController
{
    TSidebarPrefsBG *_background;
    NSTextField *_placesFld;
    TSidebarPrefsItem *_allMyFilesBtn;
    TSidebarPrefsItem *_airDropBtn;
    TSidebarPrefsItem *_applicationsBtn;
    TSidebarPrefsItem *_desktopBtn;
    TSidebarPrefsItem *_documentsBtn;
    TSidebarPrefsItem *_downloadsBtn;
    TSidebarPrefsItem *_finderCloudBtn;
    TSidebarPrefsItem *_moviesBtn;
    TSidebarPrefsItem *_musicBtn;
    TSidebarPrefsItem *_picturesBtn;
    TSidebarPrefsItem *_homeBtn;
    NSTextField *_sharedFld;
    TSidebarPrefsItem *_btmmBtn;
    TSidebarPrefsItem *_serversBtn;
    TSidebarPrefsItem *_bonjourBtn;
    NSTextField *_devicesFld;
    TSidebarPrefsItem *_computerBtn;
    TSidebarPrefsItem *_hardDisksBtn;
    TSidebarPrefsItem *_externalDisksBtn;
    TSidebarPrefsItem *_ejectablesBtn;
    NSTextField *_tagsFld;
    TSidebarPrefsItem *_recentTagsBtn;
}

- (void)sidebarItemToggle:(id)arg1;
- (void)preferencesUpdated:(id)arg1;
- (void)handleItemsAddedOrRemoved:(id)arg1;
- (void)close:(_Bool)arg1;
- (void)open;
- (void)viewLoaded;
- (void)removeButton:(id)arg1;

@end

