//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Jun  3 2014 10:55:11).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSSplitView.h"

@interface TSplitView : NSSplitView
{
    double _dividerThickness;
}

- (BOOL)isOpaque;
- (void)viewDidEndLiveResize;
- (void)animatePosition:(double)arg1 ofDividerAtIndex:(unsigned long long)arg2;
- (double)positionOfDividerAtIndex:(unsigned long long)arg1;
- (struct CGSize)sizeOfSubviewAtIndex:(unsigned long long)arg1;
- (id)subviewAtIndex:(unsigned long long)arg1;
@property double dividerThickness; // @dynamic dividerThickness;
- (void)initCommon;
- (id)initWithFrame:(struct CGRect)arg1;
- (id)initWithCoder:(id)arg1;

@end

