//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Jun  3 2014 10:55:11).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NCTodayItemViewController.h"

@class CALayer, NCDNDViewController, NSLayoutConstraint;

@interface NCTodayDNDViewController : NCTodayItemViewController
{
    CALayer *_darkeningLayer;
    NSLayoutConstraint *_heightConstraint;
    NCDNDViewController *_dndViewController;
}

@property(readonly) NCDNDViewController *dndViewController; // @synthesize dndViewController=_dndViewController;
- (void).cxx_destruct;
- (void)viewDidLayout;
- (void)loadView;

@end

