//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Jun 14 2016 15:02:16).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <Foundation/NSObject.h>

#import <Google Chrome Framework/NSApplicationDelegate-Protocol.h>

@class NSString;

__attribute__((visibility("hidden")))
@interface AppShimDelegate : NSObject <NSApplicationDelegate>
{
    struct AppShimController *appShimController_;
    BOOL terminateNow_;
    BOOL terminateRequested_;
    vector_44fa41c0 filesToOpenAtStartup_;
}

- (id).cxx_construct;
- (void).cxx_destruct;
- (void)terminateNow;
- (void)applicationWillUnhide:(id)arg1;
- (void)applicationWillHide:(id)arg1;
- (unsigned long long)applicationShouldTerminate:(id)arg1;
- (void)applicationWillBecomeActive:(id)arg1;
- (BOOL)applicationOpenUntitledFile:(id)arg1;
- (void)application:(id)arg1 openFiles:(id)arg2;
- (BOOL)application:(id)arg1 openFile:(id)arg2;
- (void)openFiles:(id)arg1;
- (void)setController:(struct AppShimController *)arg1;
- (BOOL)getFilesToOpenAtStartup:(vector_44fa41c0 *)arg1;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

