//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Jun 14 2016 15:02:16).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <Google Chrome Framework/MenuButton.h>

__attribute__((visibility("hidden")))
@interface AppToolbarButton : MenuButton
{
    int severity_;
    int type_;
}

- (void)setSeverity:(int)arg1 iconType:(int)arg2 shouldAnimate:(BOOL)arg3;
- (unsigned int)vectorIconColor:(BOOL)arg1;
- (int)vectorIconId;
- (void)commonInit;
- (void)awakeFromNib;
- (id)initWithFrame:(struct CGRect)arg1;

@end

