//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Jun 14 2016 15:02:16).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <Google Chrome Framework/BasePasswordsContentViewController.h>

__attribute__((visibility("hidden")))
@interface AutoSigninViewController : BasePasswordsContentViewController
{
    struct scoped_nsobject<CredentialItemButton> credentialView_;
    struct scoped_nsobject<AccountAvatarFetcherManager> avatarManager_;
    struct unique_ptr<base::Timer, std::__1::default_delete<base::Timer>> timer_;
}

- (id).cxx_construct;
- (void).cxx_destruct;
- (void)loadView;
- (id)initWithAvatarManager:(id)arg1 delegate:(id)arg2;
- (id)initWithDelegate:(id)arg1;

@end

