//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Jun 14 2016 15:02:16).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <AppKit/NSViewController.h>

@class AutofillBubbleController, NSString;

__attribute__((visibility("hidden")))
@interface AutofillTooltipController : NSViewController
{
    struct scoped_nsobject<AutofillTooltip> view_;
    AutofillBubbleController *bubbleController_;
    NSString *message_;
    int arrowLocation_;
    BOOL shouldDisplayTooltip_;
    BOOL isHoveringOnBubble_;
}

@property(copy, nonatomic) NSString *message; // @synthesize message=message_;
- (id).cxx_construct;
- (void).cxx_destruct;
- (void)updateTooltipDisplayState;
- (void)setHoveringOnBubble:(BOOL)arg1;
- (void)hideHover;
- (void)displayHover;
- (void)tooltipWindowWillClose:(id)arg1;
- (void)setImage:(id)arg1;
- (void)dealloc;
- (id)initWithArrowLocation:(int)arg1;

@end

