//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Jun 14 2016 15:02:16).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <AppKit/NSPopUpButton.h>

#import <Google Chrome Framework/AutofillInputField-Protocol.h>

@class NSString;
@protocol AutofillInputDelegate;

__attribute__((visibility("hidden")))
@interface AutofillPopUpButton : NSPopUpButton <AutofillInputField>
{
    id <AutofillInputDelegate> inputDelegate_;
    struct scoped_nsobject<NSString> validityMessage_;
}

+ (Class)cellClass;
@property(nonatomic) id <AutofillInputDelegate> inputDelegate; // @synthesize inputDelegate=inputDelegate_;
- (id).cxx_construct;
- (void).cxx_destruct;
- (void)didSelectItem:(id)arg1;
@property(readonly, nonatomic) BOOL isDefault;
@property(copy, nonatomic) NSString *defaultValue;
@property(readonly, nonatomic) BOOL invalid;
@property(copy, nonatomic) NSString *validityMessage;
@property(copy, nonatomic) NSString *fieldValue;
- (BOOL)becomeFirstResponder;
- (id)initWithFrame:(struct CGRect)arg1 pullsDown:(BOOL)arg2;

@end

