//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Jun 14 2016 15:02:16).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <AppKit/NSView.h>

@class AvatarMenuItemController;

__attribute__((visibility("hidden")))
@interface AvatarMenuItemView : NSView
{
    AvatarMenuItemController *viewController_;
    struct ScopedCrTrackingArea trackingArea_;
}

@property(nonatomic) AvatarMenuItemController *viewController; // @synthesize viewController=viewController_;
- (id).cxx_construct;
- (void).cxx_destruct;
- (void)accessibilityPerformAction:(id)arg1;
- (id)accessibilityAttributeValue:(id)arg1;
- (id)accessibilityActionNames;
- (id)accessibilityAttributeNames;
- (BOOL)accessibilityIsIgnored;
- (BOOL)canBecomeKeyView;
- (void)drawRect:(struct CGRect)arg1;
- (void)mouseUp:(id)arg1;
- (void)mouseExited:(id)arg1;
- (void)mouseEntered:(id)arg1;
- (void)updateTrackingAreas;
- (void)awakeFromNib;

@end

