//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Jun 14 2016 15:02:16).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <Google Chrome Framework/HoverImageButton.h>

__attribute__((visibility("hidden")))
@interface BackgroundColorHoverButton : HoverImageButton
{
    struct scoped_nsobject<NSColor> backgroundColor_;
    struct scoped_nsobject<NSColor> hoverColor_;
}

- (id).cxx_construct;
- (void).cxx_destruct;
- (BOOL)canBecomeKeyView;
- (void)keyDown:(id)arg1;
- (void)drawRect:(struct CGRect)arg1;
- (void)setRightMarginSpacing:(int)arg1;
- (id)initWithFrame:(struct CGRect)arg1 imageTitleSpacing:(int)arg2 backgroundColor:(id)arg3;

@end

