//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Jun 14 2016 15:02:16).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <Foundation/NSObject.h>

#import <Google Chrome Framework/HasWeakBrowserPointer-Protocol.h>
#import <Google Chrome Framework/NSMenuDelegate-Protocol.h>

@class MenuButton, NSString;

__attribute__((visibility("hidden")))
@interface BackForwardMenuController : NSObject <NSMenuDelegate, HasWeakBrowserPointer>
{
    int type_;
    MenuButton *button_;
    struct unique_ptr<BackForwardMenuModel, std::__1::default_delete<BackForwardMenuModel>> model_;
    struct scoped_nsobject<NSMenu> backForwardMenu_;
}

@property(readonly, nonatomic) int type; // @synthesize type=type_;
- (id).cxx_construct;
- (void).cxx_destruct;
- (void)executeMenuItem:(id)arg1;
- (void)menuNeedsUpdate:(id)arg1;
- (void)browserWillBeDestroyed;
- (id)initWithBrowser:(struct Browser *)arg1 modelType:(int)arg2 button:(id)arg3;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

