//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Jun 14 2016 15:02:16).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <AppKit/NSView.h>

#import <Google Chrome Framework/ThemedWindowDrawing-Protocol.h>

__attribute__((visibility("hidden")))
@interface BackgroundGradientView : NSView <ThemedWindowDrawing>
{
    BOOL showsDivider_;
    unsigned long long dividerEdge_;
}

@property(nonatomic) unsigned long long dividerEdge; // @synthesize dividerEdge=dividerEdge_;
@property(nonatomic) BOOL showsDivider; // @synthesize showsDivider=showsDivider_;
- (void)windowDidChangeActive;
- (void)windowDidChangeTheme;
- (void)setFrameOrigin:(struct CGPoint)arg1;
- (void)viewDidEndLiveResize;
- (void)viewWillStartLiveResize;
- (void)viewDidMoveToWindow;
- (id)backgroundImageColor;
- (id)strokeColor;
- (void)drawBackground:(struct CGRect)arg1;
- (struct CGPoint)patternPhase;
- (void)commonInit;
- (id)initWithCoder:(id)arg1;
- (id)initWithFrame:(struct CGRect)arg1;

@end

