//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Jun 14 2016 15:02:16).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <Foundation/NSObject.h>

#import <Google Chrome Framework/NSAnimationDelegate-Protocol.h>

@class NSString;

__attribute__((visibility("hidden")))
@interface BlinkScrollbarPainterDelegate : NSObject <NSAnimationDelegate>
{
    struct Scrollbar *_scrollbar;
    RetainPtr_40d2a6d7 _knobAlphaAnimation;
    RetainPtr_40d2a6d7 _trackAlphaAnimation;
    RetainPtr_40d2a6d7 _uiStateTransitionAnimation;
    RetainPtr_40d2a6d7 _expansionTransitionAnimation;
    BOOL _hasExpandedSinceInvisible;
}

- (id).cxx_construct;
- (void).cxx_destruct;
- (void)invalidate;
- (void)scrollerImp:(id)arg1 overlayScrollerStateChangedTo:(unsigned long long)arg2;
- (void)scrollerImp:(id)arg1 animateExpansionTransitionWithDuration:(double)arg2;
- (void)scrollerImp:(id)arg1 animateUIStateTransitionWithDuration:(double)arg2;
- (void)scrollerImp:(id)arg1 animateTrackAlphaTo:(double)arg2 duration:(double)arg3;
- (void)scrollerImp:(id)arg1 animateKnobAlphaTo:(double)arg2 duration:(double)arg3;
- (void)setUpAlphaAnimation:(RetainPtr_40d2a6d7 *)arg1 scrollerPainter:(id)arg2 part:(int)arg3 animateAlphaTo:(double)arg4 duration:(double)arg5;
- (struct CGPoint)mouseLocationInScrollerForScrollerImp:(id)arg1;
- (struct CGRect)convertRectFromBacking:(struct CGRect)arg1;
- (struct CGRect)convertRectToBacking:(struct CGRect)arg1;
- (struct ScrollAnimatorMac *)scrollAnimator;
- (void)cancelAnimations;
- (void)updateVisibilityImmediately:(_Bool)arg1;
- (id)initWithScrollbar:(struct Scrollbar *)arg1;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

