//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Jun 14 2016 15:02:16).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <Foundation/NSObject.h>

__attribute__((visibility("hidden")))
@interface BlinkScrollbarObserver : NSObject
{
    struct ScrollbarThemeClient *_scrollbar;
    RetainPtr_98a04a83 _scrollbarPainter;
}

- (id).cxx_construct;
- (void).cxx_destruct;
- (void)observeValueForKeyPath:(id)arg1 ofObject:(id)arg2 change:(id)arg3 context:(void *)arg4;
- (void)dealloc;
- (id)painter;
- (id)initWithScrollbar:(struct ScrollbarThemeClient *)arg1 painter:(const RetainPtr_98a04a83 *)arg2;

@end

