//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Jun 14 2016 15:02:16).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <Foundation/NSObject.h>

__attribute__((visibility("hidden")))
@interface BlinkScrollbarPartAnimation : NSObject
{
    struct Scrollbar *_scrollbar;
    struct unique_ptr<blink::BlinkScrollbarPartAnimationTimer, std::__1::default_delete<blink::BlinkScrollbarPartAnimationTimer>> _timer;
    RetainPtr_98a04a83 _scrollbarPainter;
    int _featureToAnimate;
    double _startValue;
    double _endValue;
}

- (id).cxx_construct;
- (void).cxx_destruct;
- (void)invalidate;
- (void)setCurrentProgress:(float)arg1;
- (void)setEndValue:(double)arg1;
- (void)setStartValue:(double)arg1;
- (void)setDuration:(double)arg1;
- (void)stopAnimation;
- (void)startAnimation;
- (id)initWithScrollbar:(struct Scrollbar *)arg1 featureToAnimate:(int)arg2 animateFrom:(double)arg3 animateTo:(double)arg4 duration:(double)arg5;

@end

