//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Jun 14 2016 15:02:16).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <Foundation/NSObject.h>

#import <Google Chrome Framework/IOBluetoothRFCOMMChannelDelegate-Protocol.h>

__attribute__((visibility("hidden")))
@interface BluetoothRfcommChannelDelegate : NSObject <IOBluetoothRFCOMMChannelDelegate>
{
    struct BluetoothRfcommChannelMac *channel_;
}

- (void)rfcommChannelClosed:(id)arg1;
- (void)rfcommChannelData:(id)arg1 data:(void *)arg2 length:(unsigned long long)arg3;
- (void)rfcommChannelWriteComplete:(id)arg1 refcon:(void *)arg2 status:(int)arg3;
- (void)rfcommChannelOpenComplete:(id)arg1 status:(int)arg2;
- (id)initWithChannel:(struct BluetoothRfcommChannelMac *)arg1;

@end

