//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Jun 14 2016 15:02:16).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <Foundation/NSObject.h>

#import <Google Chrome Framework/CBPeripheralDelegate-Protocol.h>

@class NSString;

__attribute__((visibility("hidden")))
@interface BluetoothLowEnergyPeripheralDelegate : NSObject <CBPeripheralDelegate>
{
    struct unique_ptr<device::BluetoothLowEnergyPeripheralBridge, std::__1::default_delete<device::BluetoothLowEnergyPeripheralBridge>> bridge_;
}

- (id).cxx_construct;
- (void).cxx_destruct;
- (void)peripheral:(id)arg1 didUpdateNotificationStateForCharacteristic:(id)arg2 error:(id)arg3;
- (void)peripheral:(id)arg1 didWriteValueForCharacteristic:(id)arg2 error:(id)arg3;
- (void)peripheral:(id)arg1 didUpdateValueForCharacteristic:(id)arg2 error:(id)arg3;
- (void)peripheral:(id)arg1 didDiscoverCharacteristicsForService:(id)arg2 error:(id)arg3;
- (void)peripheral:(id)arg1 didDiscoverServices:(id)arg2;
- (void)peripheral:(id)arg1 didModifyServices:(id)arg2;
- (void)dealloc;
- (id)initWithBluetoothLowEnergyDeviceMac:(struct BluetoothLowEnergyDeviceMac *)arg1;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

