//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Jun 14 2016 15:02:16).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <Foundation/NSObject.h>

#import <Google Chrome Framework/IOBluetoothL2CAPChannelDelegate-Protocol.h>

__attribute__((visibility("hidden")))
@interface BluetoothL2capChannelDelegate : NSObject <IOBluetoothL2CAPChannelDelegate>
{
    struct BluetoothL2capChannelMac *channel_;
}

- (void)l2capChannelQueueSpaceAvailable:(id)arg1;
- (void)l2capChannelReconfigured:(id)arg1;
- (void)l2capChannelClosed:(id)arg1;
- (void)l2capChannelData:(id)arg1 data:(void *)arg2 length:(unsigned long long)arg3;
- (void)l2capChannelWriteComplete:(id)arg1 refcon:(void *)arg2 status:(int)arg3;
- (void)l2capChannelOpenComplete:(id)arg1 status:(int)arg2;
- (id)initWithChannel:(struct BluetoothL2capChannelMac *)arg1;

@end

