//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Jun 14 2016 15:02:16).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <Foundation/NSObject.h>

#import <Google Chrome Framework/CBCentralManagerDelegate-Protocol.h>

@class NSString;

__attribute__((visibility("hidden")))
@interface BluetoothLowEnergyCentralManagerDelegate : NSObject <CBCentralManagerDelegate>
{
    struct unique_ptr<device::BluetoothLowEnergyCentralManagerBridge, std::__1::default_delete<device::BluetoothLowEnergyCentralManagerBridge>> bridge_;
}

- (id).cxx_construct;
- (void).cxx_destruct;
- (void)centralManager:(id)arg1 didDisconnectPeripheral:(id)arg2 error:(id)arg3;
- (void)centralManager:(id)arg1 didFailToConnectPeripheral:(id)arg2 error:(id)arg3;
- (void)centralManager:(id)arg1 didConnectPeripheral:(id)arg2;
- (void)centralManagerDidUpdateState:(id)arg1;
- (void)centralManager:(id)arg1 didDiscoverPeripheral:(id)arg2 advertisementData:(id)arg3 RSSI:(id)arg4;
- (void)dealloc;
- (id)initWithDiscoveryManager:(struct BluetoothLowEnergyDiscoveryManagerMac *)arg1 andAdapter:(struct BluetoothAdapterMac *)arg2;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

