//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Jun 14 2016 15:02:16).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <AppKit/NSBrowserCell.h>

@class NSMatrix;

__attribute__((visibility("hidden")))
@interface BookmarkTreeBrowserCell : NSBrowserCell
{
    const struct BookmarkNode *bookmarkNode_;
    NSMatrix *matrix_;
    id target_;
    SEL action_;
}

- (void)setAction:(SEL)arg1;
- (SEL)action;
- (void)setTarget:(id)arg1;
- (id)target;
@property(nonatomic) NSMatrix *matrix; // @synthesize matrix=matrix_;
- (void)setBookmarkNode:(const struct BookmarkNode *)arg1;
- (const struct BookmarkNode *)bookmarkNode;

@end

