//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Jun 14 2016 15:02:16).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <AppKit/NSView.h>

@protocol BookmarkButtonControllerProtocol;

__attribute__((visibility("hidden")))
@interface BookmarkBarFolderView : NSView
{
    BOOL inDrag_;
    BOOL dropIndicatorShown_;
    id <BookmarkButtonControllerProtocol> controller_;
    scoped_nsobject_02675140 dropIndicator_;
}

- (id).cxx_construct;
- (void).cxx_destruct;
- (void)setDropIndicatorShown:(BOOL)arg1;
- (BOOL)performDragOperation:(id)arg1;
- (BOOL)performDragOperationForBookmarkButton:(id)arg1;
- (BOOL)performDragOperationForURL:(id)arg1;
- (BOOL)prepareForDragOperation:(id)arg1;
- (unsigned long long)draggingUpdated:(id)arg1;
- (BOOL)wantsPeriodicDraggingUpdates;
- (void)draggingEnded:(id)arg1;
- (void)draggingExited:(id)arg1;
- (unsigned long long)draggingEntered:(id)arg1;
@property(readonly, nonatomic) id <BookmarkButtonControllerProtocol> controller;
- (void)dealloc;
- (void)awakeFromNib;

@end

