//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Jun 14 2016 15:02:16).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <AppKit/NSView.h>

@class BookmarkBarController, BookmarkBarItemContainer, BookmarkBarTextField, NSButton;

__attribute__((visibility("hidden")))
@interface BookmarkBarView : NSView
{
    BOOL dropIndicatorShown_;
    double dropIndicatorPosition_;
    BookmarkBarController *controller_;
    BookmarkBarTextField *noItemTextfield_;
    NSButton *importBookmarksButton_;
    BookmarkBarItemContainer *noItemContainer_;
}

@property(nonatomic) BookmarkBarItemContainer *noItemContainer; // @synthesize noItemContainer=noItemContainer_;
@property(readonly, nonatomic) double dropIndicatorPosition; // @synthesize dropIndicatorPosition=dropIndicatorPosition_;
@property(readonly, nonatomic) BOOL dropIndicatorShown; // @synthesize dropIndicatorShown=dropIndicatorShown_;
- (int)viewID;
- (void)setController:(id)arg1;
- (id)menu;
- (BOOL)performDragOperation:(id)arg1;
- (BOOL)performDragOperationForBookmarkButton:(id)arg1;
- (BOOL)performDragOperationForURL:(id)arg1;
- (BOOL)prepareForDragOperation:(id)arg1;
- (unsigned long long)draggingUpdated:(id)arg1;
- (BOOL)wantsPeriodicDraggingUpdates;
- (void)draggingEnded:(id)arg1;
- (void)draggingExited:(id)arg1;
- (unsigned long long)draggingEntered:(id)arg1;
- (void)dropIndicatorChanged;
- (id)controller;
- (id)importBookmarksButton;
- (id)noItemTextfield;
- (BOOL)mouseDownCanMoveWindow;
- (void)updateTheme:(const struct ThemeProvider *)arg1;
- (void)themeDidChangeNotification:(id)arg1;
- (void)viewDidMoveToWindow;
- (void)viewWillMoveToWindow:(id)arg1;
- (void)awakeFromNib;
- (void)dealloc;
- (void)setFrameSize:(struct CGSize)arg1;

@end

