//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Jun 14 2016 15:02:16).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <Google Chrome Framework/ElementAppleScript.h>

@class NSString;

__attribute__((visibility("hidden")))
@interface BookmarkNodeAppleScript : ElementAppleScript
{
    const struct BookmarkNode *bookmarkNode_;
    NSString *tempTitle_;
}

@property(copy, nonatomic) NSString *tempTitle; // @synthesize tempTitle=tempTitle_;
- (struct BookmarkModel *)bookmarkModel;
- (id)index;
- (void)setTitle:(id)arg1;
- (id)title;
- (void)setBookmarkNode:(const struct BookmarkNode *)arg1;
- (id)initWithBookmarkNode:(const struct BookmarkNode *)arg1;
- (void)dealloc;
- (id)init;

@end

