//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Jun 14 2016 15:02:16).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <Foundation/NSObject.h>

@protocol BookmarkButtonControllerProtocol;

__attribute__((visibility("hidden")))
@interface BookmarkFolderTarget : NSObject
{
    id <BookmarkButtonControllerProtocol> controller_;
    struct Profile *profile_;
}

- (id)pasteboardItemForDragOfButton:(id)arg1;
- (void)openBookmarkFolderFromButton:(id)arg1;
- (id)initWithController:(id)arg1 profile:(struct Profile *)arg2;

@end

