//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Jun 14 2016 15:02:16).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <Foundation/NSObject.h>

@class NSWindow;

__attribute__((visibility("hidden")))
@interface BridgedNativeWindowTracker : NSObject
{
    NSWindow *window_;
}

- (void)onWindowWillClose:(id)arg1;
- (_Bool)wasNSWindowClosed;
- (void)dealloc;
- (id)initWithNSWindow:(id)arg1;

@end

