//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Jun 14 2016 15:02:16).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <AppKit/NSView.h>

#import <Google Chrome Framework/NSAnimationDelegate-Protocol.h>

@class NSString;

__attribute__((visibility("hidden")))
@interface BrowserActionsContainerView : NSView <NSAnimationDelegate>
{
    struct CGRect grippyRect_;
    struct CGPoint initialDragPoint_;
    double maxDesiredWidth_;
    BOOL userIsResizing_;
    BOOL resizable_;
    BOOL isOverflow_;
    BOOL canDragLeft_;
    BOOL canDragRight_;
    BOOL grippyPinned_;
    unique_ptr_1d93bd1c highlight_;
    struct BrowserActionsContainerViewSizeDelegate *sizeDelegate_;
    struct scoped_nsobject<NSViewAnimation> resizeAnimation_;
    struct BrowserActionsContainerViewSizeDelegate *delegate_;
}

@property(nonatomic) struct BrowserActionsContainerViewSizeDelegate *delegate; // @synthesize delegate=delegate_;
@property(readonly, nonatomic) BOOL userIsResizing; // @synthesize userIsResizing=userIsResizing_;
@property(nonatomic) double maxDesiredWidth; // @synthesize maxDesiredWidth=maxDesiredWidth_;
@property(nonatomic) BOOL grippyPinned; // @synthesize grippyPinned=grippyPinned_;
@property(nonatomic) BOOL canDragRight; // @synthesize canDragRight=canDragRight_;
@property(nonatomic) BOOL canDragLeft; // @synthesize canDragLeft=canDragLeft_;
- (id).cxx_construct;
- (void).cxx_destruct;
- (double)maxAllowedWidth;
- (id)appropriateCursorForGrippy;
- (void)stopAnimation;
- (BOOL)isAnimating;
- (struct CGRect)animationEndFrame;
- (void)resizeToWidth:(double)arg1 animate:(BOOL)arg2;
- (int)viewID;
- (void)notifyAnimationEnded;
- (void)animationDidStop:(id)arg1;
- (void)animationDidEnd:(id)arg1;
- (void)mouseDragged:(id)arg1;
- (void)mouseUp:(id)arg1;
- (void)mouseDown:(id)arg1;
- (BOOL)acceptsFirstResponder;
- (void)resetCursorRects;
- (void)setIsOverflow:(BOOL)arg1;
- (BOOL)isHighlighting;
- (void)setHighlight:(unique_ptr_1d93bd1c)arg1;
- (void)keyDown:(id)arg1;
- (void)viewDidMoveToWindow;
- (void)drawRect:(struct CGRect)arg1;
- (id)initWithFrame:(struct CGRect)arg1;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

