//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Jun 14 2016 15:02:16).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

@class CAAnimation;

@protocol CAAnimationDelegate
- (void)animationDidStop:(CAAnimation *)arg1 finished:(BOOL)arg2;
- (void)animationDidStart:(CAAnimation *)arg1;
@end

