//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Jun 14 2016 15:02:16).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <Google Chrome Framework/HoverImageButton.h>

__attribute__((visibility("hidden")))
@interface ChosenObjectDeleteButton : HoverImageButton
{
    unique_ptr_fa8befec objectInfo_;
    Callback_6e21b799 callback_;
}

- (id).cxx_construct;
- (void).cxx_destruct;
- (void)deleteClicked:(id)arg1;
- (id)initWithChosenObject:(unique_ptr_fa8befec)arg1 atPoint:(struct CGPoint)arg2 withCallback:(Callback_6e21b799)arg3;

@end

