//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Jun 14 2016 15:02:16).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <Google Chrome Framework/NSObject-Protocol.h>

@class NSEvent, NSWindow;

@protocol CommandDispatcherDelegate <NSObject>
- (BOOL)postPerformKeyEquivalent:(NSEvent *)arg1 window:(NSWindow *)arg2;
- (BOOL)prePerformKeyEquivalent:(NSEvent *)arg1 window:(NSWindow *)arg2;
- (BOOL)eventHandledByExtensionCommand:(NSEvent *)arg1 isRedispatch:(BOOL)arg2;
@end

