//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Jun 14 2016 15:02:16).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <AppKit/NSWindowController.h>

#import <Google Chrome Framework/NSWindowDelegate-Protocol.h>

@class ConfirmQuitFrameView, NSString;

__attribute__((visibility("hidden")))
@interface ConfirmQuitPanelController : NSWindowController <NSWindowDelegate>
{
    ConfirmQuitFrameView *contentView_;
}

+ (id)keyCombinationForAccelerator:(const struct PlatformAcceleratorCocoa *)arg1;
+ (unique_ptr_95f286f2)quitAccelerator;
+ (id)keyCommandString;
+ (BOOL)eventTriggersFeature:(id)arg1;
+ (id)sharedController;
- (void)hideAllWindowsForApplication:(id)arg1 withDuration:(double)arg2;
- (id)pumpEventQueueForKeyUp:(id)arg1 untilDate:(id)arg2;
- (void)animationDidStop:(id)arg1 finished:(BOOL)arg2;
- (void)animationDidStart:(id)arg1;
- (void)animateFadeOut;
- (void)dismissPanel;
- (void)showWindow:(id)arg1;
- (void)windowWillClose:(id)arg1;
- (unsigned long long)runModalLoopForApplication:(id)arg1;
- (id)init;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

