//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Jun 14 2016 15:02:16).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <Foundation/NSObject.h>

@class NSWindow;

__attribute__((visibility("hidden")))
@interface ConstrainedWindowSheetController : NSObject
{
    scoped_nsobject_9420f295 sheets_;
    struct scoped_nsobject<NSWindow> parentWindow_;
    scoped_nsobject_7ff2efe9 activeView_;
    BOOL isSheetHiddenForFullscreen_;
    struct unique_ptr<WebContentsModalDialogHostCocoa, std::__1::default_delete<WebContentsModalDialogHostCocoa>> dialogHost_;
}

+ (id)sheetForOverlayWindow:(id)arg1;
+ (id)controllerForSheet:(id)arg1;
+ (id)controllerForParentWindow:(id)arg1;
- (id).cxx_construct;
- (void).cxx_destruct;
- (void)closeSheet:(id)arg1 withAnimation:(BOOL)arg2;
- (void)onOverlayWindowMouseDown:(id)arg1;
- (struct CGPoint)originForSheetSize:(struct CGSize)arg1 inContainerRect:(struct CGRect)arg2;
- (struct CGRect)overlayWindowFrameForParentView:(id)arg1;
- (void)updateSheetPosition:(id)arg1;
- (void)onParentWindowSizeDidChange:(id)arg1;
- (void)onParentWindowWillClose:(id)arg1;
- (id)findSheetInfoForSheet:(id)arg1;
- (id)findSheetInfoForParentView:(id)arg1;
- (struct CGSize)overlayWindowSizeForParentView:(id)arg1;
- (int)sheetCount;
- (void)pulseSheet:(id)arg1;
- (void)closeSheet:(id)arg1;
- (struct CGPoint)originForSheet:(id)arg1 withWindowSize:(struct CGSize)arg2;
- (void)unhideSheetForFullscreenTransition;
- (void)hideSheetForFullscreenTransition;
- (void)hideSheet:(id)arg1;
- (void)showSheet:(id)arg1 forParentView:(id)arg2;
@property(readonly, nonatomic) NSWindow *parentWindow;
@property(readonly, nonatomic) struct WebContentsModalDialogHost *dialogHost;
- (id)initWithParentWindow:(id)arg1;

@end

