//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Jun 14 2016 15:02:16).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <Google Chrome Framework/NSObject-Protocol.h>

@class NSWindow;

@protocol ConstrainedWindowSheet <NSObject>
@property(readonly, nonatomic) NSWindow *sheetWindow;
- (void)resizeWithNewSize:(struct CGSize)arg1;
- (void)updateSheetPosition;
- (void)makeSheetKeyAndOrderFront;
- (void)pulseSheet;
- (void)unhideSheet;
- (void)hideSheet;
- (void)closeSheetWithAnimation:(BOOL)arg1;
- (void)showSheetForWindow:(NSWindow *)arg1;
@end

