//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Jun 14 2016 15:02:16).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <AppKit/NSButtonCell.h>

#import <Google Chrome Framework/ConstrainedWindowButtonDrawableCell-Protocol.h>

__attribute__((visibility("hidden")))
@interface ConstrainedWindowButtonCell : NSButtonCell <ConstrainedWindowButtonDrawableCell>
{
    BOOL isMouseInside_;
}

@property(nonatomic) BOOL isMouseInside; // @synthesize isMouseInside=isMouseInside_;
- (id)getAttributedTitle;
- (struct CGSize)cellSize;
- (void)drawInteriorWithFrame:(struct CGRect)arg1 inView:(id)arg2;
- (void)drawBezelWithFrame:(struct CGRect)arg1 inView:(id)arg2;

@end

