//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Jun 14 2016 15:02:16).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <Foundation/NSObject.h>

__attribute__((visibility("hidden")))
@interface CrAVFoundationDeviceObserver : NSObject
{
    Callback_64de60db onDeviceChangedCallback_;
    struct set<base::scoped_nsobject<CrAVCaptureDevice>, std::__1::less<base::scoped_nsobject<CrAVCaptureDevice>>, std::__1::allocator<base::scoped_nsobject<CrAVCaptureDevice>>> monitoredDevices_;
    struct ThreadChecker mainThreadChecker_;
}

- (id).cxx_construct;
- (void).cxx_destruct;
- (void)observeValueForKeyPath:(id)arg1 ofObject:(id)arg2 change:(id)arg3 context:(void *)arg4;
- (void)removeObservers:(id)arg1;
- (void)clearOnDeviceChangedCallback;
- (void)stopObserving:(id)arg1;
- (void)startObserving:(scoped_nsobject_898878d5)arg1;
- (void)dealloc;
- (id)initWithOnChangedCallback:(const Callback_64de60db *)arg1;

@end

