//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Jun 14 2016 15:02:16).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <Foundation/NSObject.h>

@class NSButton;

__attribute__((visibility("hidden")))
@interface CrCreateAppShortcutCheckboxObserver : NSObject
{
    NSButton *checkbox_;
    NSButton *continueButton_;
}

- (void)observeValueForKeyPath:(id)arg1 ofObject:(id)arg2 change:(id)arg3 context:(void *)arg4;
- (void)stopObserving;
- (void)startObserving;
- (id)initWithCheckbox:(id)arg1 continueButton:(id)arg2;

@end

