//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Jun 14 2016 15:02:16).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <AppKit/NSButtonCell.h>

__attribute__((visibility("hidden")))
@interface CustomPaddingImageButtonCell : NSButtonCell
{
    int leftMarginSpacing_;
    int imageTitleSpacing_;
    int rightMarginSpacing_;
}

- (void)drawWithFrame:(struct CGRect)arg1 inView:(id)arg2;
- (unsigned long long)focusRingType;
- (struct CGSize)cellSize;
- (void)drawImage:(id)arg1 withFrame:(struct CGRect)arg2 inView:(id)arg3;
- (struct CGRect)drawTitle:(id)arg1 withFrame:(struct CGRect)arg2 inView:(id)arg3;
- (void)setRightMarginSpacing:(int)arg1;
- (id)initWithLeftMarginSpacing:(int)arg1 imageTitleSpacing:(int)arg2;

@end

