//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Jun 14 2016 15:02:16).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

@protocol DesktopMediaPickerObserver
- (void)sourceThumbnailChangedForList:(struct DesktopMediaList *)arg1 atIndex:(int)arg2;
- (void)sourceNameChangedForList:(struct DesktopMediaList *)arg1 atIndex:(int)arg2;
- (void)sourceMovedForList:(struct DesktopMediaList *)arg1 from:(int)arg2 to:(int)arg3;
- (void)sourceRemovedForList:(struct DesktopMediaList *)arg1 atIndex:(int)arg2;
- (void)sourceAddedForList:(struct DesktopMediaList *)arg1 atIndex:(int)arg2;
@end

