//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Jun 14 2016 15:02:16).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <Foundation/NSObject.h>

__attribute__((visibility("hidden")))
@interface DeviceNameAndTransportType : NSObject
{
    struct scoped_nsobject<NSString> deviceName_;
    int transportType_;
}

- (id).cxx_construct;
- (void).cxx_destruct;
- (int)transportType;
- (id)deviceName;
- (id)initWithName:(id)arg1 transportType:(int)arg2;

@end

