//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Jun 14 2016 15:02:16).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <AppKit/NSViewController.h>

#import <Google Chrome Framework/NSTableViewDataSource-Protocol.h>
#import <Google Chrome Framework/NSTableViewDelegate-Protocol.h>

@class NSButton, NSScrollView, NSString, NSTableColumn, NSTableView, NSTextField;

__attribute__((visibility("hidden")))
@interface DevicePermissionsViewController : NSViewController <NSTableViewDataSource, NSTableViewDelegate>
{
    NSTextField *titleField_;
    NSTextField *promptField_;
    NSButton *cancelButton_;
    NSButton *okButton_;
    NSTableView *tableView_;
    NSTableColumn *deviceNameColumn_;
    NSTableColumn *serialNumberColumn_;
    NSScrollView *scrollView_;
    struct DevicePermissionsDialogController *controller_;
    scoped_refptr_721ff621 prompt_;
}

- (id).cxx_construct;
- (void).cxx_destruct;
- (void)tableViewSelectionDidChange:(id)arg1;
- (id)tableView:(id)arg1 objectValueForTableColumn:(id)arg2 row:(long long)arg3;
- (long long)numberOfRowsInTableView:(id)arg1;
- (void)awakeFromNib;
- (void)devicesChanged;
- (void)ok:(id)arg1;
- (void)cancel:(id)arg1;
- (id)initWithController:(struct DevicePermissionsDialogController *)arg1 prompt:(scoped_refptr_721ff621)arg2;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

