//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Jun 14 2016 15:02:16).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <Google Chrome Framework/BaseView.h>

@class NSView;

__attribute__((visibility("hidden")))
@interface DevToolsContainerView : BaseView
{
    struct DevToolsContentsResizingStrategy strategy_;
    NSView *devToolsView_;
    NSView *contentsView_;
}

- (id).cxx_construct;
- (void)adjustSubviews;
- (BOOL)hasDevToolsView;
- (void)resizeSubviewsWithOldSize:(struct CGSize)arg1;
- (BOOL)setDevToolsView:(id)arg1 withStrategy:(const struct DevToolsContentsResizingStrategy *)arg2;

@end

