//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Jun 14 2016 15:02:16).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <Foundation/NSObject.h>

__attribute__((visibility("hidden")))
@interface DockIcon : NSObject
{
    struct TimeTicks lastUpdate_;
    BOOL forceUpdate_;
}

+ (id)sharedDockIcon;
- (id).cxx_construct;
- (void)setProgress:(float)arg1;
- (void)setIndeterminate:(BOOL)arg1;
- (void)setDownloads:(int)arg1;
- (void)updateIcon;

@end

