//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Jun 14 2016 15:02:16).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <AppKit/NSAnimation.h>

@class DownloadItemCell;

__attribute__((visibility("hidden")))
@interface DownloadItemCellAnimation : NSAnimation
{
    DownloadItemCell *cell_;
}

- (void)setCurrentProgress:(float)arg1;
- (id)initWithDownloadItemCell:(id)arg1 duration:(double)arg2 animationCurve:(unsigned long long)arg3;

@end

