//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Jun 14 2016 15:02:16).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <AppKit/NSButton.h>

#import <Google Chrome Framework/ThemedWindowDrawing-Protocol.h>

__attribute__((visibility("hidden")))
@interface DownloadShowAllButton : NSButton <ThemedWindowDrawing>
{
}

- (void)windowDidChangeActive;
- (void)windowDidChangeTheme;
- (void)drawRect:(struct CGRect)arg1;
- (BOOL)isOpaque;
- (void)sizeToFit;
- (void)awakeFromNib;

@end

