//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Jun 14 2016 15:02:16).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <Google Chrome Framework/DraggableButton.h>

#import <Google Chrome Framework/NSMenuDelegate-Protocol.h>
#import <Google Chrome Framework/ThemedWindowDrawing-Protocol.h>

@class DownloadItemController, NSString;

__attribute__((visibility("hidden")))
@interface DownloadItemButton : DraggableButton <NSMenuDelegate, ThemedWindowDrawing>
{
    struct FilePath downloadPath_;
    DownloadItemController *controller_;
    struct scoped_nsobject<NSMenu> contextMenu_;
}

@property(nonatomic) DownloadItemController *controller; // @synthesize controller=controller_;
@property(nonatomic) struct FilePath download; // @synthesize download=downloadPath_;
- (id).cxx_construct;
- (void).cxx_destruct;
- (void)viewWillMoveToWindow:(id)arg1;
- (BOOL)showingContextMenu;
- (void)windowDidChangeActive;
- (void)windowDidChangeTheme;
- (void)drawRect:(struct CGRect)arg1;
- (BOOL)isOpaque;
- (BOOL)shouldDelayWindowOrderingForEvent:(id)arg1;
- (void)menuDidClose:(id)arg1;
- (void)rightMouseDown:(id)arg1;
- (void)mouseDown:(id)arg1;
- (void)showContextMenu;
- (void)beginDrag:(id)arg1;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

