//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Jun 14 2016 15:02:16).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <Google Chrome Framework/HoverImageButton.h>

@class ProfileChooserController;

__attribute__((visibility("hidden")))
@interface EditableProfilePhoto : HoverImageButton
{
    struct AvatarMenu *avatarMenu_;
    struct scoped_nsobject<TransparentBackgroundImageView> changePhotoImage_;
    ProfileChooserController *controller_;
}

- (id).cxx_construct;
- (void).cxx_destruct;
- (void)accessibilityPerformAction:(id)arg1;
- (id)accessibilityActionNames;
- (BOOL)accessibilityIsIgnored;
- (BOOL)canBecomeKeyView;
- (void)setHoverState:(int)arg1;
- (void)editPhoto:(id)arg1;
- (id)initWithFrame:(struct CGRect)arg1 avatarMenu:(struct AvatarMenu *)arg2 profileIcon:(const struct Image *)arg3 editingAllowed:(BOOL)arg4 withController:(id)arg5;

@end

