//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Jun 14 2016 15:02:16).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <AppKit/NSAnimation.h>

#import <Google Chrome Framework/NSAnimationDelegate-Protocol.h>

@class NSApplication, NSString;

__attribute__((visibility("hidden")))
@interface FadeAllWindowsAnimation : NSAnimation <NSAnimationDelegate>
{
    NSApplication *application_;
}

- (void)animationDidStop:(id)arg1;
- (void)setCurrentProgress:(float)arg1;
- (id)initWithApplication:(id)arg1 animationDuration:(double)arg2;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

