//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Jun 14 2016 15:02:16).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <AppKit/NSViewController.h>

#import <Google Chrome Framework/HasWeakBrowserPointer-Protocol.h>
#import <Google Chrome Framework/NSAnimationDelegate-Protocol.h>

@class FindBarTextField, NSButton, NSString, NSView;

__attribute__((visibility("hidden")))
@interface FindBarCocoaController : NSViewController <NSAnimationDelegate, HasWeakBrowserPointer>
{
    NSView *findBarView_;
    FindBarTextField *findText_;
    NSButton *nextButton_;
    NSButton *previousButton_;
    NSButton *closeButton_;
    struct FindBarBridge *findBarBridge_;
    struct Browser *browser_;
    struct scoped_nsobject<FocusTracker> focusTracker_;
    struct scoped_nsobject<NSViewAnimation> showHideAnimation_;
    struct scoped_nsobject<NSViewAnimation> moveAnimation_;
    BOOL suppressPboardUpdateActions_;
    double maxY_;
    double defaultWidth_;
}

@property(readonly, nonatomic) NSView *findBarView; // @synthesize findBarView=findBarView_;
- (id).cxx_construct;
- (void).cxx_destruct;
- (int)findBarWidth;
- (struct Point)findBarWindowPosition;
- (void)animationDidEnd:(id)arg1;
- (BOOL)isFindBarAnimating;
- (BOOL)isFindBarVisible;
- (void)updateUIForFindResult:(const struct FindNotificationDetails *)arg1 withText:(const basic_string_61b65554 *)arg2;
- (void)clearResults:(const struct FindNotificationDetails *)arg1;
- (void)updateFindBarForChangedWebContents;
- (id)matchCountText;
- (struct _NSRange)selectedRange;
- (id)findText;
- (void)setFindText:(id)arg1 selectedRange:(const struct _NSRange *)arg2;
- (void)restoreSavedFocus;
- (void)setFocusAndSelection;
- (void)stopAnimation;
- (void)hideFindBar:(BOOL)arg1;
- (void)showFindBar:(BOOL)arg1;
- (BOOL)control:(id)arg1 textView:(id)arg2 doCommandBySelector:(SEL)arg3;
- (void)controlTextDidChange:(id)arg1;
- (BOOL)isOffTheRecordProfile;
- (void)positionFindBarViewAtMaxY:(double)arg1 maxWidth:(double)arg2;
- (void)findPboardUpdated:(id)arg1;
- (void)nextResult:(id)arg1;
- (void)previousResult:(id)arg1;
- (void)close:(id)arg1;
- (void)awakeFromNib;
- (void)setFindBarBridge:(struct FindBarBridge *)arg1;
- (void)browserWillBeDestroyed;
- (void)dealloc;
- (id)initWithBrowser:(struct Browser *)arg1;
- (id)browserWindowController;
- (void)clearFindResultsForCurrentBrowser;
- (void)prepopulateText:(id)arg1;
- (void)moveFindBarIfNecessary:(BOOL)arg1;
- (float)findBarHorizontalPosition;
- (void)setFindBarFrame:(struct CGRect)arg1 animate:(BOOL)arg2 duration:(float)arg3;
- (id)createAnimationForView:(id)arg1 toFrame:(struct CGRect)arg2 duration:(float)arg3;
- (struct CGRect)hiddenFindBarFrame;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

