//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Jun 14 2016 15:02:16).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <Foundation/NSObject.h>

@class FullscreenToolbarController;

__attribute__((visibility("hidden")))
@interface FullscreenToolbarVisibilityLockController : NSObject
{
    struct scoped_nsobject<NSMutableSet> visibilityLocks_;
    FullscreenToolbarController *owner_;
    struct FullscreenToolbarAnimationController *animationController_;
}

- (id).cxx_construct;
- (void).cxx_destruct;
- (void)releaseToolbarVisibilityForOwner:(id)arg1 withAnimation:(BOOL)arg2;
- (void)lockToolbarVisibilityForOwner:(id)arg1 withAnimation:(BOOL)arg2;
- (BOOL)isToolbarVisibilityLockedForOwner:(id)arg1;
- (BOOL)isToolbarVisibilityLocked;
- (id)initWithFullscreenToolbarController:(id)arg1 animationController:(struct FullscreenToolbarAnimationController *)arg2;

@end

