//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Jun 14 2016 15:02:16).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <Foundation/NSObject.h>

@class BrowserWindowController;

__attribute__((visibility("hidden")))
@interface FullscreenToolbarController : NSObject
{
    BrowserWindowController *browserController_;
    BOOL inFullscreenMode_;
    struct scoped_nsobject<FullscreenMenubarTracker> menubarTracker_;
    struct scoped_nsobject<FullscreenToolbarVisibilityLockController> visibilityLockController_;
    struct unique_ptr<FullscreenToolbarAnimationController, std::__1::default_delete<FullscreenToolbarAnimationController>> animationController_;
    struct scoped_nsobject<FullscreenToolbarMouseTracker> mouseTracker_;
    int systemFullscreenMode_;
    int toolbarStyle_;
}

@property(nonatomic) int toolbarStyle; // @synthesize toolbarStyle=toolbarStyle_;
- (id).cxx_construct;
- (void).cxx_destruct;
- (void)updateToolbarFrame:(struct CGRect)arg1;
- (BOOL)isMouseOnScreen;
- (BOOL)isInFullscreen;
- (BOOL)isFullscreenTransitionInProgress;
- (BOOL)mustShowFullscreenToolbar;
- (double)toolbarFraction;
- (double)menubarOffset;
- (id)visibilityLockController;
- (id)browserWindowController;
- (void)updateToolbar;
- (void)updateToolbarStyle;
- (void)setSystemFullscreenModeTo:(int)arg1;
- (void)revealToolbarForTabStripChanges;
- (void)cancelAnimationAndTimer;
- (void)windowDidResignMain:(id)arg1;
- (void)windowDidBecomeMain:(id)arg1;
- (void)windowDidMove:(id)arg1;
- (void)windowDidChangeScreen:(id)arg1;
- (void)exitFullscreenMode;
- (void)enterFullscreenMode;
- (void)dealloc;
- (id)initWithBrowserController:(id)arg1;
- (BOOL)shouldShowMenubarInImmersiveFullscreen;
- (void)cleanup;
- (int)desiredSystemFullscreenMode;
- (BOOL)isWindowOnPrimaryScreen;
- (BOOL)doesScreenHaveMenuBar;
- (void)updateMenuBarAndDockVisibility;

@end

