//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Jun 14 2016 15:02:16).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <Foundation/NSObject.h>

__attribute__((visibility("hidden")))
@interface GTMCarbonEventHandler : NSObject
{
    struct OpaqueEventHandlerRef *eventHandler_;
    id delegate_;
    BOOL delegateRespondsToHandleEvent_;
}

- (void)setDelegate:(id)arg1;
- (id)delegate;
- (struct OpaqueEventHandlerRef *)eventHandler;
- (struct OpaqueEventTargetRef *)eventTarget;
- (int)handleEvent:(id)arg1 handler:(struct OpaqueEventHandlerCallRef *)arg2;
- (void)unregisterForEvents:(const struct EventTypeSpec *)arg1 count:(unsigned long long)arg2;
- (void)registerForEvents:(const struct EventTypeSpec *)arg1 count:(unsigned long long)arg2;
- (BOOL)delegateRespondsToHandleEvent;
- (void)dealloc;

@end

