//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Jun 14 2016 15:02:16).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <Foundation/NSArray.h>

__attribute__((visibility("hidden")))
@interface GTMIBArray : NSArray
{
    id object1_;
    id object2_;
    id object3_;
    id object4_;
    id object5_;
    NSArray *realArray_;
}

- (void)awakeFromNib;
- (BOOL)isEqual:(id)arg1;
- (unsigned long long)hash;
- (id)mutableCopyWithZone:(struct _NSZone *)arg1;
- (id)copyWithZone:(struct _NSZone *)arg1;
- (unsigned long long)countByEnumeratingWithState:(CDStruct_70511ce9 *)arg1 objects:(id *)arg2 count:(unsigned long long)arg3;
- (id)reverseObjectEnumerator;
- (id)objectEnumerator;
- (id)objectAtIndex:(unsigned long long)arg1;
- (unsigned long long)count;
- (void)setupRealArray;
- (void)dealloc;

@end

