//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Jun 14 2016 15:02:16).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <Foundation/NSObject.h>

@class GTMUILocalizer;

__attribute__((visibility("hidden")))
@interface GTMUILocalizerAndLayoutTweaker : NSObject
{
    id uiObject_;
    GTMUILocalizer *localizer_;
    id localizerOwner_;
}

+ (void)resizeViewWithoutAutoResizingSubViews:(id)arg1 delta:(struct CGSize)arg2;
+ (void)resizeWindowWithoutAutoResizingSubViews:(id)arg1 delta:(struct CGSize)arg2;
+ (void)wrapRadioGroupForWidth:(id)arg1;
+ (void)wrapButtonTitleForWidth:(id)arg1;
+ (double)sizeToFitFixedHeightTextField:(id)arg1 minWidth:(unsigned long long)arg2;
+ (double)sizeToFitFixedHeightTextField:(id)arg1;
+ (double)sizeToFitFixedWidthTextField:(id)arg1;
+ (struct CGSize)sizeToFitView:(id)arg1;
+ (id)wrapString:(id)arg1 width:(double)arg2 font:(id)arg3;
- (void)tweakView:(id)arg1;
- (void)tweakUI:(id)arg1;
- (void)applyLocalizer:(id)arg1 tweakingUI:(id)arg2;
- (void)awakeFromNib;

@end

