//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Jun 14 2016 15:02:16).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <Foundation/NSObject.h>

@class NSUserActivity;

__attribute__((visibility("hidden")))
@interface HandoffManager : NSObject
{
    struct ObjCPropertyReleaser _propertyReleaser_HandoffManager;
    struct GURL _activeURL;
    NSUserActivity *_userActivity;
    int _origin;
}

@property(retain, nonatomic) NSUserActivity *userActivity; // @synthesize userActivity=_userActivity;
- (id).cxx_construct;
- (void).cxx_destruct;
- (void)updateUserActivity;
- (BOOL)shouldUseActiveURL;
- (void)updateActiveURL:(const struct GURL *)arg1;
- (id)init;

@end

