//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Jun 14 2016 15:02:16).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <Foundation/NSObject.h>

__attribute__((visibility("hidden")))
@interface HistoryMenuCocoaController : NSObject
{
    struct HistoryMenuBridge *bridge_;
}

- (void)openHistoryMenuItem:(id)arg1;
- (void)openURLForItem:(const struct HistoryItem *)arg1;
- (BOOL)validateMenuItem:(id)arg1;
- (id)initWithBridge:(struct HistoryMenuBridge *)arg1;

@end

