//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Jun 14 2016 15:02:16).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <AppKit/NSViewController.h>

__attribute__((visibility("hidden")))
@interface HistoryOverlayController : NSViewController
{
    int mode_;
    struct scoped_nsobject<HistoryOverlayView> contentView_;
    scoped_nsobject_7ff2efe9 parent_;
}

- (id).cxx_construct;
- (void).cxx_destruct;
- (void)dismiss;
- (void)showPanelForView:(id)arg1;
- (void)setProgress:(double)arg1 finished:(BOOL)arg2;
- (void)loadView;
- (id)initForMode:(int)arg1;

@end

