//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Jun 14 2016 15:02:16).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <Foundation/NSObject.h>

@class HistoryOverlayController;
@protocol HistorySwiperDelegate;

__attribute__((visibility("hidden")))
@interface HistorySwiper : NSObject
{
    HistoryOverlayController *historyOverlay_;
    struct CGPoint gestureStartPoint_;
    struct CGPoint gestureCurrentPoint_;
    double gestureTotalY_;
    BOOL inGesture_;
    BOOL receivingTouches_;
    int gestureStartPointValid_;
    int historySwipeDirection_;
    BOOL historySwipeDirectionInverted_;
    BOOL firstScrollUnconsumed_;
    BOOL waitingForFirstGestureScroll_;
    int recognitionState_;
    id <HistorySwiperDelegate> delegate_;
    struct CGSize mouseScrollDelta_;
}

+ (void)resetMagicMouseState;
@property(nonatomic) id <HistorySwiperDelegate> delegate; // @synthesize delegate=delegate_;
- (BOOL)shouldConsumeWheelEvent:(id)arg1;
- (BOOL)handleScrollWheelEvent:(id)arg1;
- (void)initiateMagicMouseHistorySwipe:(BOOL)arg1 event:(id)arg2;
- (BOOL)handleMagicMouseWheelEvent:(id)arg1;
- (BOOL)browserCanNavigateInDirection:(int)arg1 event:(id)arg2;
- (void)navigateBrowserInDirection:(int)arg1;
- (BOOL)systemSettingsAllowHistorySwiping:(id)arg1;
- (void)showHistoryOverlay:(int)arg1;
- (BOOL)isEventDirectionInverted:(id)arg1;
- (BOOL)updateProgressBar;
- (void)removeHistoryOverlay;
- (void)cancelHistorySwipe;
- (BOOL)shouldCancelHorizontalSwipeWithCurrentPoint:(struct CGPoint)arg1 startPoint:(struct CGPoint)arg2;
- (BOOL)processTouchEventForHistorySwiping:(id)arg1;
- (void)touchesEndedWithEvent:(id)arg1;
- (void)touchesCancelledWithEvent:(id)arg1;
- (void)touchesMovedWithEvent:(id)arg1;
- (void)touchesBeganWithEvent:(id)arg1;
- (void)updateGestureCurrentPointFromEvent:(id)arg1;
- (struct CGPoint)averagePositionInEvent:(id)arg1;
- (void)endGestureWithEvent:(id)arg1;
- (void)beginGestureWithEvent:(id)arg1;
- (void)rendererHandledGestureScrollEvent:(const struct WebGestureEvent *)arg1 consumed:(BOOL)arg2;
- (void)rendererHandledWheelEvent:(const struct WebMouseWheelEvent *)arg1 consumed:(BOOL)arg2;
- (BOOL)handleEvent:(id)arg1;
- (void)dealloc;
- (id)initWithDelegate:(id)arg1;

@end

