//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Jun 14 2016 15:02:16).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <AppKit/NSPopUpButtonCell.h>

@class NSImage;

__attribute__((visibility("hidden")))
@interface HoverImageMenuButtonCell : NSPopUpButtonCell
{
    struct scoped_nsobject<NSImage> hoverImage_;
    BOOL hovered_;
}

@property(nonatomic, getter=isHovered) BOOL hovered; // @synthesize hovered=hovered_;
- (id).cxx_construct;
- (void).cxx_destruct;
- (void)drawWithFrame:(struct CGRect)arg1 inView:(id)arg2;
- (void)setDefaultImage:(id)arg1;
- (id)imageToDraw;
@property(retain, nonatomic) NSImage *hoverImage;
- (id)initTextCell:(id)arg1 pullsDown:(BOOL)arg2;

@end

