//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Jun 14 2016 15:02:16).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <AppKit/NSWindowController.h>

#import <Google Chrome Framework/NSTableViewDataSource-Protocol.h>

@class MultiKeyEquivalentButton, NSButton, NSImageView, NSString, NSTableView, NSTextField;

__attribute__((visibility("hidden")))
@interface HungRendererController : NSWindowController <NSTableViewDataSource>
{
    MultiKeyEquivalentButton *waitButton_;
    NSButton *killButton_;
    NSTableView *tableView_;
    NSImageView *imageView_;
    NSTextField *messageView_;
    struct WebContents *hungContents_;
    struct unique_ptr<HungRendererWebContentsObserverBridge, std::__1::default_delete<HungRendererWebContentsObserverBridge>> hungContentsObserver_;
    struct scoped_nsobject<NSArray> hungTitles_;
    struct scoped_nsobject<NSArray> hungFavicons_;
}

+ (void)endForWebContents:(struct WebContents *)arg1;
+ (void)showForWebContents:(struct WebContents *)arg1;
- (id).cxx_construct;
- (void).cxx_destruct;
- (void)renderProcessGone;
- (void)endForWebContents:(struct WebContents *)arg1;
- (void)showForWebContents:(struct WebContents *)arg1;
- (void)windowWillClose:(id)arg1;
- (id)tableView:(id)arg1 dataCellForTableColumn:(id)arg2 row:(long long)arg3;
- (id)tableView:(id)arg1 objectValueForTableColumn:(id)arg2 row:(long long)arg3;
- (long long)numberOfRowsInTableView:(id)arg1;
- (void)wait:(id)arg1;
- (void)kill:(id)arg1;
- (void)layoutForItemCount:(int)arg1;
- (void)awakeFromNib;
- (void)dealloc;
- (id)initWithWindowNibName:(id)arg1;
- (id)waitButton;
- (id)killButton;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

