//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Jun 14 2016 15:02:16).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <AppKit/NSView.h>

__attribute__((visibility("hidden")))
@interface InfoBubbleView : NSView
{
    int arrowLocation_;
    int alignment_;
    int cornerFlags_;
    struct scoped_nsobject<NSColor> backgroundColor_;
}

@property(nonatomic) int cornerFlags; // @synthesize cornerFlags=cornerFlags_;
@property(nonatomic) int alignment; // @synthesize alignment=alignment_;
@property(nonatomic) int arrowLocation; // @synthesize arrowLocation=arrowLocation_;
- (id).cxx_construct;
- (void).cxx_destruct;
- (void)setBackgroundColor:(id)arg1;
- (id)backgroundColor;
- (struct CGPoint)arrowTip;
- (void)drawRect:(struct CGRect)arg1;
- (BOOL)performKeyEquivalent:(id)arg1;
- (id)initWithFrame:(struct CGRect)arg1;

@end

