//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Jun 14 2016 15:02:16).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <AppKit/NSView.h>

__attribute__((visibility("hidden")))
@interface MediaGalleryListEntry : NSView
{
    struct MediaGalleryListEntryController *controller_;
    unsigned long long prefId_;
    struct scoped_nsobject<MediaGalleryButton> checkbox_;
    scoped_nsobject_0ef9b51e details_;
}

- (id).cxx_construct;
- (void).cxx_destruct;
- (void)layoutSubViews;
- (struct MenuModel *)getContextMenu;
- (void)onFolderViewerClicked:(id)arg1;
- (void)onCheckboxToggled:(id)arg1;
- (void)setState:(_Bool)arg1;
- (void)resizeWithOldSuperviewSize:(struct CGSize)arg1;
- (void)setFrameSize:(struct CGSize)arg1;
- (id)initWithFrame:(struct CGRect)arg1 controller:(struct MediaGalleryListEntryController *)arg2 prefInfo:(const struct MediaGalleryPrefInfo *)arg3;

@end

