//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Jun 14 2016 15:02:16).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <AppKit/NSWindowController.h>

#import <Google Chrome Framework/NSWindowDelegate-Protocol.h>

@class NSString;

__attribute__((visibility("hidden")))
@interface NativeAppWindowController : NSWindowController <NSWindowDelegate>
{
    struct NativeAppWindowCocoa *appWindow_;
    scoped_nsobject_7ff2efe9 titlebar_background_view_;
}

@property(nonatomic) struct NativeAppWindowCocoa *appWindow; // @synthesize appWindow=appWindow_;
- (id).cxx_construct;
- (void).cxx_destruct;
- (BOOL)handledByExtensionCommand:(id)arg1 priority:(int)arg2;
- (struct CGSize)window:(id)arg1 willUseFullScreenContentSize:(struct CGSize)arg2;
- (BOOL)windowShouldZoom:(id)arg1 toFrame:(struct CGRect)arg2;
- (void)windowDidDeminiaturize:(id)arg1;
- (void)windowDidMiniaturize:(id)arg1;
- (void)windowDidMove:(id)arg1;
- (void)windowDidExitFullScreen:(id)arg1;
- (void)windowDidEnterFullScreen:(id)arg1;
- (void)windowDidEndLiveResize:(id)arg1;
- (void)windowDidResize:(id)arg1;
- (void)windowDidResignMain:(id)arg1;
- (void)windowDidBecomeMain:(id)arg1;
- (void)windowDidResignKey:(id)arg1;
- (void)windowDidBecomeKey:(id)arg1;
- (void)windowWillClose:(id)arg1;
- (void)setTitlebarBackgroundView:(id)arg1;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

