//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Jun 14 2016 15:02:16).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <Foundation/NSObject.h>

#import <Google Chrome Framework/NSNetServiceBrowserDelegate-Protocol.h>
#import <Google Chrome Framework/NSNetServiceDelegate-Protocol.h>

@class NSString;

__attribute__((visibility("hidden")))
@interface NetServiceBrowserDelegate : NSObject <NSNetServiceBrowserDelegate, NSNetServiceDelegate>
{
    struct NetServiceBrowserContainer *container_;
    scoped_nsobject_9420f295 services_;
}

- (id).cxx_construct;
- (void).cxx_destruct;
- (void)netService:(id)arg1 didUpdateTXTRecordData:(id)arg2;
- (void)netServiceBrowser:(id)arg1 didRemoveService:(id)arg2 moreComing:(BOOL)arg3;
- (void)netServiceBrowser:(id)arg1 didFindService:(id)arg2 moreComing:(BOOL)arg3;
- (id)initWithContainer:(struct NetServiceBrowserContainer *)arg1;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

