//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Jun 14 2016 15:02:16).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <Foundation/NSObject.h>

__attribute__((visibility("hidden")))
@interface NotificationRemoteDispatcher : NSObject
{
    struct scoped_nsobject<NSXPCConnection> xpcConnection_;
}

- (id).cxx_construct;
- (void).cxx_destruct;
- (void)notificationClick:(id)arg1;
- (void)closeAllNotifications;
- (void)closeNotificationWithId:(id)arg1 withProfileId:(id)arg2;
- (void)dispatchNotification:(id)arg1;
- (id)init;

@end

