//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Jun 14 2016 15:02:16).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <Google Chrome Framework/BackgroundGradientView.h>

__attribute__((visibility("hidden")))
@interface OmniboxPopupTopSeparatorView : BackgroundGradientView
{
}

+ (double)preferredHeight;
- (void)drawRect:(struct CGRect)arg1;

@end

