//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Jun 14 2016 15:02:16).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <AppKit/NSViewController.h>

#import <Google Chrome Framework/NSTextViewDelegate-Protocol.h>

@class NSButton, NSString, NSTextField;

__attribute__((visibility("hidden")))
@interface OneClickSigninViewController : NSViewController <NSTextViewDelegate>
{
    NSTextField *messageTextField_;
    NSTextField *titleTextField_;
    NSTextField *informativePlaceholderTextField_;
    NSButton *advancedLink_;
    NSButton *closeButton_;
    BOOL isSyncDialog_;
    BOOL clickedLearnMore_;
    basic_string_61b65554 email_;
    struct scoped_nsobject<NSString> errorMessage_;
    scoped_nsobject_1b22b22f informativeTextView_;
    Callback_077da0e6 startSyncCallback_;
    Callback_64de60db closeCallback_;
    struct WebContents *webContents_;
}

- (id).cxx_construct;
- (void).cxx_destruct;
- (void)close;
- (BOOL)textView:(id)arg1 clickedOnLink:(id)arg2 atIndex:(unsigned long long)arg3;
- (double)initializeInformativeTextView;
- (void)awakeFromNib;
- (void)onClickClose:(id)arg1;
- (void)onClickAdvancedLink:(id)arg1;
- (void)onClickUndo:(id)arg1;
- (void)ok:(id)arg1;
- (void)viewWillClose;
- (id)initWithNibName:(id)arg1 webContents:(struct WebContents *)arg2 syncCallback:(const Callback_077da0e6 *)arg3 closeCallback:(const Callback_64de60db *)arg4 isSyncDialog:(BOOL)arg5 email:(const basic_string_61b65554 *)arg6 errorMessage:(id)arg7;
- (id)linkViewForTesting;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

