//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Jun 14 2016 15:02:16).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <AppKit/NSViewController.h>

@class NSView;

__attribute__((visibility("hidden")))
@interface OverlayableContentsController : NSViewController
{
    scoped_nsobject_7ff2efe9 activeContainer_;
}

- (id).cxx_construct;
- (void).cxx_destruct;
@property(readonly, nonatomic) NSView *activeContainer;
- (id)init;

@end

