//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Jun 14 2016 15:02:16).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <Google Chrome Framework/NSObject-Protocol.h>

@protocol PasswordItemTwoColumnView <NSObject>
@property(readonly, nonatomic) double secondColumnWidth;
@property(readonly, nonatomic) double firstColumnWidth;
- (void)layoutWithFirstColumn:(double)arg1 secondColumn:(double)arg2;
@end

