//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Jun 14 2016 15:02:16).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <AppKit/NSViewController.h>

#import <Google Chrome Framework/NSTextViewDelegate-Protocol.h>

@class NSButton, NSString, NSTextView;

__attribute__((visibility("hidden")))
@interface ProfileSigninConfirmationViewController : NSViewController <NSTextViewDelegate>
{
    struct Browser *browser_;
    basic_string_805fe43b username_;
    _Bool offerProfileCreation_;
    struct ProfileSigninConfirmationDelegate *delegate_;
    Callback_64de60db closeDialogCallback_;
    scoped_nsobject_02675140 promptBox_;
    scoped_nsobject_6cadfeaf closeButton_;
    scoped_nsobject_0ef9b51e titleField_;
    scoped_nsobject_0ef9b51e promptField_;
    scoped_nsobject_2ce0c752 explanationField_;
    struct scoped_nsobject<ConstrainedWindowButton> createProfileButton_;
    struct scoped_nsobject<ConstrainedWindowButton> cancelButton_;
    struct scoped_nsobject<ConstrainedWindowButton> okButton_;
}

- (id).cxx_construct;
- (void).cxx_destruct;
- (void)addButton:(id)arg1 withTitle:(int)arg2 target:(id)arg3 action:(SEL)arg4 shouldAutoSize:(BOOL)arg5;
- (BOOL)textView:(id)arg1 clickedOnLink:(id)arg2 atIndex:(unsigned long long)arg3;
- (void)learnMore;
- (void)createProfile:(id)arg1;
- (void)close:(id)arg1;
- (void)ok:(id)arg1;
- (void)cancel:(id)arg1;
- (void)loadView;
- (id)initWithBrowser:(struct Browser *)arg1 username:(const basic_string_805fe43b *)arg2 delegate:(struct ProfileSigninConfirmationDelegate *)arg3 closeDialogCallback:(const Callback_64de60db *)arg4 offerProfileCreation:(_Bool)arg5;
@property(readonly, nonatomic) NSTextView *explanationField;
@property(readonly, nonatomic) NSButton *createProfileButton;
@property(readonly, nonatomic) struct ProfileSigninConfirmationDelegate *delegate;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

