//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Jun 14 2016 15:02:16).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <AppKit/NSWindowController.h>

#import <Google Chrome Framework/NSWindowDelegate-Protocol.h>

@class NSString;

__attribute__((visibility("hidden")))
@interface ReauthDialogWindowController : NSWindowController <NSWindowDelegate>
{
    basic_string_805fe43b emailAddress_;
    struct WebContents *webContents_;
    int reason_;
    struct unique_ptr<(anonymous namespace)::ReauthDialogDelegate, std::__1::default_delete<(anonymous namespace)::ReauthDialogDelegate>> webContentsDelegate_;
    struct unique_ptr<ConstrainedWindowMac, std::__1::default_delete<ConstrainedWindowMac>> constrained_window_;
    struct unique_ptr<content::WebContents, std::__1::default_delete<content::WebContents>> reauthWebContents_;
}

- (id).cxx_construct;
- (void).cxx_destruct;
- (void)dealloc;
- (void)close;
- (void)closeButtonClicked:(id)arg1;
- (void)show;
- (void)showURL:(const struct GURL *)arg1;
- (id)initWithProfile:(struct Profile *)arg1 email:(basic_string_805fe43b)arg2 reason:(int)arg3 webContents:(struct WebContents *)arg4;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

