//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Jun 14 2016 15:02:16).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <Foundation/NSObject.h>

__attribute__((visibility("hidden")))
@interface ReplyEventHandler : NSObject
{
    Callback_e1d315fe onReply_;
    struct AEDesc replyEvent_;
}

+ (void)pingProcessAndCall:(Callback_e1d315fe)arg1;
- (id).cxx_construct;
- (void).cxx_destruct;
- (void)closeWithSuccess:(_Bool)arg1;
- (void)message:(id)arg1 withReply:(id)arg2;
- (void)pingProcess;
- (id)initWithCallback:(Callback_e1d315fe)arg1;

@end

