//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Jun 14 2016 15:02:16).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <Foundation/NSObject.h>

#import <Google Chrome Framework/NSOpenSavePanelDelegate-Protocol.h>

@class NSString;

__attribute__((visibility("hidden")))
@interface SelectFileDialogBridge : NSObject <NSOpenSavePanelDelegate>
{
    struct SelectFileDialogImpl *selectFileDialogImpl_;
}

- (BOOL)panel:(id)arg1 shouldEnableURL:(id)arg2;
- (void)endedPanel:(id)arg1 didCancel:(_Bool)arg2 type:(int)arg3 parentWindow:(id)arg4;
- (id)initWithSelectFileDialogImpl:(struct SelectFileDialogImpl *)arg1;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

