//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Jun 14 2016 15:02:16).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <Google Chrome Framework/BasePasswordsContentViewController.h>

@class NSButton;

__attribute__((visibility("hidden")))
@interface SignInPromoViewController : BasePasswordsContentViewController
{
    scoped_nsobject_6cadfeaf _signInButton;
    scoped_nsobject_6cadfeaf _noButton;
    scoped_nsobject_6cadfeaf _closeButton;
}

- (id).cxx_construct;
- (void).cxx_destruct;
- (void)onCloseClicked:(id)arg1;
- (void)onNoClicked:(id)arg1;
- (void)onSignInClicked:(id)arg1;
- (void)loadView;
- (id)defaultButton;
- (id)initWithDelegate:(id)arg1;
@property(readonly) NSButton *closeButton;
@property(readonly) NSButton *noButton;
@property(readonly) NSButton *signInButton;

@end

