//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Jun 14 2016 15:02:16).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <AppKit/NSSpeechSynthesizer.h>

__attribute__((visibility("hidden")))
@interface SingleUseSpeechSynthesizer : NSSpeechSynthesizer
{
    struct scoped_nsobject<NSString> utterance_;
    _Bool didSpeak_;
}

- (id).cxx_construct;
- (void).cxx_destruct;
- (_Bool)startSpeakingString:(id)arg1;
- (_Bool)startSpeakingRetainedUtterance;
- (id)initWithUtterance:(id)arg1;

@end

