//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Jun 14 2016 15:02:16).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <AppKit/NSView.h>

#import <Google Chrome Framework/CALayerDelegate-Protocol.h>

@class CALayer, CAShapeLayer;

__attribute__((visibility("hidden")))
@interface SpinnerView : NSView <CALayerDelegate>
{
    struct scoped_nsobject<CAAnimationGroup> spinnerAnimation_;
    struct scoped_nsobject<CABasicAnimation> rotationAnimation_;
    CAShapeLayer *shapeLayer_;
    CALayer *rotationLayer_;
}

- (id).cxx_construct;
- (void).cxx_destruct;
- (void)updateAnimation:(id)arg1;
- (void)initializeAnimation;
- (BOOL)layer:(id)arg1 shouldInheritContentsScale:(double)arg2 fromWindow:(id)arg3;
- (void)setHidden:(BOOL)arg1;
- (id)makeBackingLayer;
- (BOOL)isAnimating;
- (void)viewDidMoveToWindow;
- (void)viewWillMoveToWindow:(id)arg1;
- (void)dealloc;
- (id)initWithFrame:(struct CGRect)arg1;

@end

