//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Jun 14 2016 15:02:16).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <Foundation/NSObject.h>

#import <Google Chrome Framework/CAAnimationDelegate-Protocol.h>

__attribute__((visibility("hidden")))
@interface StatusBubbleAnimationDelegate : NSObject <CAAnimationDelegate>
{
    struct ScopedBlock<void (^)()> completionHandler_;
}

- (id).cxx_construct;
- (void).cxx_destruct;
- (void)animationDidStop:(id)arg1 finished:(BOOL)arg2;
- (void)animationDidStart:(id)arg1;
- (id)initWithCompletionHandler:(CDUnknownBlockType)arg1;

@end

