//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Jun 14 2016 15:02:16).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <AppKit/NSTextFieldCell.h>

__attribute__((visibility("hidden")))
@interface StyledTextFieldCell : NSTextFieldCell
{
}

- (void)drawWithFrame:(struct CGRect)arg1 inView:(id)arg2;
- (struct CGRect)drawingRectForBounds:(struct CGRect)arg1;
- (void)resetCursorRect:(struct CGRect)arg1 inView:(id)arg2;
- (struct CGRect)textCursorFrameForFrame:(struct CGRect)arg1;
- (struct CGRect)textFrameForFrame:(struct CGRect)arg1;
- (struct CGRect)textFrameForFrameInternal:(struct CGRect)arg1;
- (BOOL)shouldDrawBezel;
- (int)roundedCornerFlags;
- (double)cornerRadius;
- (double)bottomTextFrameOffset;
- (double)topTextFrameOffset;

@end

