//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Jun 14 2016 15:02:16).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <Foundation/NSObject.h>

#import <Google Chrome Framework/CAAnimationDelegate-Protocol.h>

@class TabController, TabStripController;

__attribute__((visibility("hidden")))
@interface TabCloseAnimationDelegate : NSObject <CAAnimationDelegate>
{
    TabStripController *strip_;
    TabController *controller_;
}

- (void)animationDidStop:(id)arg1 finished:(BOOL)arg2;
- (void)animationDidStart:(id)arg1;
- (void)invalidate;
- (id)initWithTabStrip:(id)arg1 tabController:(id)arg2;

@end

