//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Jun 14 2016 15:02:16).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <AppKit/NSView.h>

@class TabContentsController;

__attribute__((visibility("hidden")))
@interface TabContentsContainerView : NSView
{
    TabContentsController *delegate_;
}

- (BOOL)canBecomeKeyView;
- (BOOL)becomeFirstResponder;
- (BOOL)acceptsFirstResponder;
- (int)viewID;
- (void)updateBackgroundColor;
- (void)setNeedsDisplayInRect:(struct CGRect)arg1;
- (void)resizeSubviewsWithOldSize:(struct CGSize)arg1;
- (void)delegateDestroyed;
- (id)initWithDelegate:(id)arg1;

@end

