//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Jun 14 2016 15:02:16).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <AppKit/NSViewController.h>

#import <Google Chrome Framework/TabDraggingEventTarget-Protocol.h>

@class AlertIndicatorButton, HoverCloseButton, NSString, NSView;
@protocol TabControllerTarget;

__attribute__((visibility("hidden")))
@interface TabController : NSViewController <TabDraggingEventTarget>
{
    struct scoped_nsobject<SpriteView> iconView_;
    struct scoped_nsobject<AlertIndicatorButton> alertIndicatorButton_;
    struct scoped_nsobject<HoverCloseButton> closeButton_;
    struct CGRect originalIconFrame_;
    BOOL isIconShowing_;
    BOOL pinned_;
    BOOL active_;
    BOOL selected_;
    struct GURL url_;
    int loadingState_;
    id <TabControllerTarget> target_;
    SEL action_;
    struct unique_ptr<ui::SimpleMenuModel, std::__1::default_delete<ui::SimpleMenuModel>> contextMenuModel_;
    struct unique_ptr<TabControllerInternal::MenuDelegate, std::__1::default_delete<TabControllerInternal::MenuDelegate>> contextMenuDelegate_;
    struct scoped_nsobject<MenuController> contextMenuController_;
}

+ (double)pinnedTabWidth;
+ (double)maxTabWidth;
+ (double)minActiveTabWidth;
+ (double)minTabWidth;
+ (double)defaultTabHeight;
@property(nonatomic) struct GURL url; // @synthesize url=url_;
@property(nonatomic) id target; // @synthesize target=target_;
@property(nonatomic) BOOL pinned; // @synthesize pinned=pinned_;
@property(nonatomic) int loadingState; // @synthesize loadingState=loadingState_;
@property(nonatomic) SEL action; // @synthesize action=action_;
- (id).cxx_construct;
- (void).cxx_destruct;
- (void)maybeStartDrag:(id)arg1 forTab:(id)arg2;
- (BOOL)inRapidClosureMode;
- (void)themeChangedNotification:(id)arg1;
- (void)updateTitleColor;
- (void)updateVisibility;
- (void)setIconImage:(id)arg1 withToastAnimation:(BOOL)arg2;
- (void)setIconImage:(id)arg1;
- (BOOL)shouldShowCloseButton;
- (BOOL)shouldShowAlertIndicator;
- (BOOL)shouldShowIcon;
- (int)iconCapacity;
@property(nonatomic) NSString *toolTip;
@property(readonly, nonatomic) HoverCloseButton *closeButton;
- (void)setAlertState:(int)arg1;
@property(readonly, nonatomic) AlertIndicatorButton *alertIndicatorButton;
- (void)setIconView:(id)arg1;
@property(readonly, nonatomic) NSView *iconView;
@property(nonatomic) BOOL selected;
@property(nonatomic) BOOL active;
- (void)setTitle:(id)arg1;
- (void)selectTab:(id)arg1;
- (void)closeTab:(id)arg1;
- (void)toggleMute:(id)arg1;
- (id)menu;
- (void)internalSetSelected:(BOOL)arg1;
- (void)dealloc;
- (id)init;
- (id)tabView;

@end

