//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Jun 14 2016 15:02:16).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <AppKit/NSCustomImageRep.h>

@class NSImage;

__attribute__((visibility("hidden")))
@interface ToolbarButtonImageRep : NSCustomImageRep
{
    int style_;
    NSImage *icon_;
}

+ (void)drawImage:(id)arg1;
@property(nonatomic) int style; // @synthesize style=style_;
@property(retain, nonatomic) NSImage *icon; // @synthesize icon=icon_;
- (void)dealloc;

@end

