//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Jun 14 2016 15:02:16).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <Foundation/NSObject.h>

@class NSView;
@protocol URLDropTarget;

__attribute__((visibility("hidden")))
@interface URLDropTargetHandler : NSObject
{
    NSView<URLDropTarget> *view_;
}

+ (id)handledDragTypes;
- (BOOL)performDragOperation:(id)arg1;
- (void)draggingExited:(id)arg1;
- (unsigned long long)draggingUpdated:(id)arg1;
- (unsigned long long)draggingEntered:(id)arg1;
- (id)initWithView:(id)arg1;
- (void)hideIndicator;
- (unsigned long long)getDragOperation:(id)arg1;

@end

