//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Jun 14 2016 15:02:16).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <Foundation/NSObject.h>

#import <Google Chrome Framework/NSWindowDelegate-Protocol.h>

@class NSCursor, NSString;

__attribute__((visibility("hidden")))
@interface ViewsNSWindowDelegate : NSObject <NSWindowDelegate>
{
    struct BridgedNativeWidget *parent_;
    struct scoped_nsobject<NSCursor> cursor_;
}

- (id).cxx_construct;
- (void).cxx_destruct;
- (struct CGRect)window:(id)arg1 willPositionSheet:(id)arg2 usingRect:(struct CGRect)arg3;
- (struct CGSize)window:(id)arg1 willUseFullScreenContentSize:(struct CGSize)arg2;
- (void)windowDidExitFullScreen:(id)arg1;
- (void)windowWillExitFullScreen:(id)arg1;
- (void)windowDidEnterFullScreen:(id)arg1;
- (void)windowWillEnterFullScreen:(id)arg1;
- (void)windowDidChangeBackingProperties:(id)arg1;
- (void)windowDidDeminiaturize:(id)arg1;
- (void)windowDidMiniaturize:(id)arg1;
- (void)windowWillClose:(id)arg1;
- (void)windowDidResignKey:(id)arg1;
- (void)windowDidBecomeKey:(id)arg1;
- (void)windowDidMove:(id)arg1;
- (void)windowDidResize:(id)arg1;
- (void)windowDidFailToExitFullScreen:(id)arg1;
- (void)windowDidFailToEnterFullScreen:(id)arg1;
- (BOOL)shouldRepostPendingLeftMouseDown:(struct CGPoint)arg1;
- (void)sheetDidEnd:(id)arg1 returnCode:(long long)arg2 contextInfo:(void *)arg3;
- (void)onSystemControlTintChanged:(id)arg1;
- (void)onWindowOrderChanged:(id)arg1;
@property(retain, nonatomic) NSCursor *cursor;
@property(readonly, nonatomic) struct NativeWidgetMac *nativeWidgetMac;
- (id)initWithBridgedNativeWidget:(struct BridgedNativeWidget *)arg1;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

