//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Jun 14 2016 15:02:16).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <Google Chrome Framework/BaseBubbleController.h>

@class NSButton, NSTextField, NSView;

__attribute__((visibility("hidden")))
@interface WebsiteSettingsBubbleController : BaseBubbleController
{
    struct WebContents *webContents_;
    scoped_nsobject_7ff2efe9 contentView_;
    NSView *securitySectionView_;
    NSTextField *securitySummaryField_;
    NSTextField *securityDetailsField_;
    NSButton *securityDetailsButton_;
    struct GURL url_;
    NSTextField *resetDecisionsField_;
    NSButton *resetDecisionsButton_;
    BOOL isDevToolsDisabled_;
    struct scoped_refptr<net::X509Certificate> certificate_;
    NSView *separatorAfterSecuritySection_;
    NSView *siteSettingsSectionView_;
    NSView *cookiesView_;
    NSView *permissionsView_;
    BOOL permissionsPresent_;
    NSButton *siteSettingsButton_;
    struct unique_ptr<WebsiteSettings, std::__1::default_delete<WebsiteSettings>> presenter_;
    struct unique_ptr<WebsiteSettingsUIBridge, std::__1::default_delete<WebsiteSettingsUIBridge>> bridge_;
}

- (id).cxx_construct;
- (void).cxx_destruct;
- (void)setPermissionInfo:(const vector_77964467 *)arg1 andChosenObjects:(vector_00bd8384)arg2;
- (void)setCookieInfo:(const vector_496a3f5c *)arg1;
- (void)alignPermissionIcon:(id)arg1 withTextField:(id)arg2;
- (struct CGPoint)addChosenObject:(unique_ptr_fa8befec)arg1 toView:(id)arg2 atPoint:(struct CGPoint)arg3;
- (struct CGPoint)addPermission:(const struct PermissionInfo *)arg1 toView:(id)arg2 atPoint:(struct CGPoint)arg3;
- (void)onChosenObjectDeleted:(const struct ChosenObjectInfo *)arg1;
- (void)onPermissionChanged:(int)arg1 to:(int)arg2;
- (id)addDeleteButtonForChosenObject:(unique_ptr_fa8befec)arg1 toView:(id)arg2 atPoint:(struct CGPoint)arg3;
- (id)addPopUpButtonForPermission:(const struct PermissionInfo *)arg1 toView:(id)arg2 atPoint:(struct CGPoint)arg3;
- (void)setIdentityInfo:(const struct IdentityInfo *)arg1;
- (id)addButtonWithText:(id)arg1 toView:(id)arg2;
- (id)addLinkButtonWithText:(id)arg1 toView:(id)arg2;
- (id)addSeparatorToView:(id)arg1;
- (id)addImageWithSize:(struct CGSize)arg1 toView:(id)arg2 atPoint:(struct CGPoint)arg3;
- (id)addText:(const basic_string_61b65554 *)arg1 withSize:(double)arg2 bold:(BOOL)arg3 toView:(id)arg4 atPoint:(struct CGPoint)arg5;
- (void)sizeTextFieldHeightToFit:(id)arg1;
- (void)configureTextFieldAsLabel:(id)arg1;
- (void)sizeAndPositionWindow;
- (void)layoutSiteSettingsSection;
- (void)layoutSecuritySection;
- (void)performLayout;
- (void)setHeightOfView:(id)arg1 to:(double)arg2;
- (void)setWidthOfView:(id)arg1 to:(double)arg2;
- (double)setYPositionOfView:(id)arg1 to:(double)arg2;
- (double)layoutViewAtRTLStart:(id)arg1 withYPosition:(double)arg2;
- (void)resetCertificateDecisions:(id)arg1;
- (void)showCertificateInfo:(id)arg1;
- (void)showSecurityDetails:(id)arg1;
- (void)showSiteSettingsData:(id)arg1;
- (void)showCookiesAndSiteData:(id)arg1;
- (id)addSiteSettingsSectionToView:(id)arg1;
- (id)addSecuritySectionToView:(id)arg1;
- (void)initializeContents;
- (void)initializeContentsForInternalPage:(const struct GURL *)arg1;
- (void)setPresenter:(struct WebsiteSettings *)arg1;
- (void)windowWillClose:(id)arg1;
- (struct Profile *)profile;
- (id)initWithParentWindow:(id)arg1 websiteSettingsUIBridge:(struct WebsiteSettingsUIBridge *)arg2 webContents:(struct WebContents *)arg3 url:(const struct GURL *)arg4 isDevToolsDisabled:(BOOL)arg5;
- (double)defaultWindowWidth;

@end

