//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Jun  3 2014 10:55:11).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

@class NSDictionary, NSString, SAUIAddViews;

@protocol SiriNCClientProtocol
- (void)serviceUIWasDismissed;
- (void)serviceUIWillAppear;
- (void)addViewsCommandStashed:(SAUIAddViews *)arg1 forCardWithTitle:(NSString *)arg2 imagePath:(NSString *)arg3;
- (void)radarCreated:(NSString *)arg1;
- (void)showBugTemplateWithValues:(NSDictionary *)arg1 completion:(void (^)(BOOL, NSDictionary *))arg2;
@end

