//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Jun 14 2016 15:02:16).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

@class NSWindow;

@protocol PreferencesViewController

@optional
+ (void)registerDefaults;
@property(readonly, nonatomic) double minimumPaneHeight;
- (void)focusDefaultViewWithHostWindow:(NSWindow *)arg1;
- (void)hostModuleWillBeRemoved;
- (void)hostModuleWillBeDisplayed;
- (void)hostModuleWasInitializedFromDefaults;
@end

