//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Jun 14 2016 15:02:16).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "NSObject-Protocol.h"

@class NCAppInfo, NSString;

@protocol NCAppInfoDelegate <NSObject>
- (void)app:(NCAppInfo *)arg1 foundAtLocation:(NSString *)arg2;
- (void)appUnreadNotificationsChanged:(NCAppInfo *)arg1;
@end

