//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Jun 14 2016 15:02:16).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "NCNotificationWindow.h"

@class NCRemoteAlertModel;

__attribute__((visibility("hidden")))
@interface NCRemoteNotificationWindow : NCNotificationWindow
{
    _Bool _removalDelayed;
    id _strongSelf;
    _Bool _live;
    NCRemoteAlertModel *_remoteAlertModel;
}

@property(nonatomic) _Bool live; // @synthesize live=_live;
@property(readonly) NCRemoteAlertModel *remoteAlertModel; // @synthesize remoteAlertModel=_remoteAlertModel;
- (void).cxx_destruct;
- (void)reactivate;
- (unsigned long long)maxNotificationHeight;
- (id)nibName;
- (BOOL)loadView;
- (void)dealloc;
- (id)initWithModel:(id)arg1;

@end

