//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Jun 14 2016 15:02:16).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <objc/NSObject.h>

__attribute__((visibility("hidden")))
@interface WKEditCommandObjC : NSObject
{
    RefPtr_3f15df8d m_command;
}

- (id).cxx_construct;
- (void).cxx_destruct;
- (struct WebEditCommandProxy *)command;
- (id)initWithWebEditCommandProxy:(RefPtr_3f15df8d)arg1;

@end

