//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Jun  3 2014 10:55:11).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

#import "NCBannerAnimationDelegate.h"

@class NSArray, NSHashTable, NSMutableArray, NSObject<OS_dispatch_source>, NSPanel, NSView, _NCBannersWindow;

@interface NCBannerWindowController : NSObject <NCBannerAnimationDelegate>
{
    _NCBannersWindow *_window;
    NSView *_contentView;
    NSMutableArray *_windows;
    struct CGRect _visibleRect;
    struct CGRect _screenRect;
    double _rightColumnConstraintConstant;
    double _dockRightMargin;
    long long _windowRaiseCount;
    long long _normalWindowLevel;
    long long _animationWindowLevel;
    NSHashTable *_coalescedSlideOutBanners;
    NSObject<OS_dispatch_source> *_coalescedSlideOutTimer;
    _Bool _lockscreenMode;
    _Bool _disableAnimations;
    id <NCBannerWindowControllerDelegate> _delegate;
}

@property __weak id <NCBannerWindowControllerDelegate> delegate; // @synthesize delegate=_delegate;
@property(nonatomic) _Bool disableAnimations; // @synthesize disableAnimations=_disableAnimations;
@property(nonatomic) _Bool lockscreenMode; // @synthesize lockscreenMode=_lockscreenMode;
@property(retain, nonatomic) NSArray *windows; // @synthesize windows=_windows;
@property(readonly) NSPanel *window; // @synthesize window=_window;
- (void).cxx_destruct;
- (void)_animateWithDuration:(double)arg1 change:(CDUnknownBlockType)arg2 completed:(CDUnknownBlockType)arg3;
- (struct CGRect)_windowFrame;
- (void)_orderWindowOnIfNecessary;
- (void)_orderWindowOutIfNecessary;
- (void)_sortViews;
- (void)_horizontalLayout;
- (void)_recalculateOverflow;
- (void)_lockVerticalConstraintForWindow:(id)arg1;
- (void)_addHorizontalConstraintToWindow:(id)arg1;
- (void)_addVerticalConstraintToWindow:(id)arg1;
- (void)_fixupVerticalConstraints;
- (void)_insertWindow:(id)arg1 atIndex:(long long)arg2 withAnimation:(int)arg3;
- (id)_prepareMoveWindow:(id)arg1 fromIndex:(long long)arg2 toIndex:(long long)arg3;
- (id)_prepareInsertWindow:(id)arg1 atIndex:(long long)arg2 withAnimation:(int)arg3;
- (id)_prepareAnimationAndRemoveWindow:(id)arg1 withAnimationType:(int)arg2;
- (void)bannerAnimationDoneRaisedWindowLevel:(id)arg1;
- (void)bannerAnimationNeedsRaisedWindowLevel:(id)arg1;
- (void)performAnimationsDisabled:(CDUnknownBlockType)arg1;
- (id)existingBannerDisplayedByApplication:(id)arg1;
- (void)layoutWindowForScreenRect:(struct CGRect)arg1 visibleRect:(struct CGRect)arg2;
- (void)replaceWindows:(id)arg1;
- (void)removeWindows:(id)arg1 withAnimation:(int)arg2;
- (void)removeWindow:(id)arg1 withAnimation:(int)arg2;
- (void)replaceWindow:(id)arg1 withWindow:(id)arg2;
- (void)insertWindow:(id)arg1 above:(id)arg2 withAnimation:(int)arg3;
- (void)insertWindow:(id)arg1 below:(id)arg2 withAnimation:(int)arg3;
- (void)addWindow:(id)arg1 withAnimation:(int)arg2;
@property(readonly) double rightMargin;
- (id)initWithScreenFrame:(struct CGRect)arg1 andVisibleFrame:(struct CGRect)arg2 spaces:(id)arg3;

@end

