//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Jun  3 2014 10:55:11).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class NSObject<OS_dispatch_source>;

@interface NCHotKey : NSObject
{
    unsigned int _cid;
    NSObject<OS_dispatch_source> *_source;
    void *_lsNoteID;
    double _openTime;
    CDUnknownBlockType _focusChangeNotification;
}

+ (id)sharedManager;
@property(copy, nonatomic) CDUnknownBlockType focusChangeNotification; // @synthesize focusChangeNotification=_focusChangeNotification;
- (void).cxx_destruct;
- (void)_handleEvents;
- (void)dealloc;
- (id)init;

@end

