//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Jun  3 2014 10:55:11).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSViewController.h"

#import "NSTextViewDelegate.h"
#import "PasswordPromptViewInterface.h"

@class NSArray, NSButton, NSString, NSTextView;

@interface AccountChooserViewController : NSViewController <PasswordPromptViewInterface, NSTextViewDelegate>
{
    NSButton *cancelButton_;
    NSButton *signInButton_;
    NSTextView *titleView_;
    struct scoped_nsobject<NSArray> credentialButtons_;
    struct scoped_nsobject<AccountAvatarFetcherManager> avatarManager_;
    struct PasswordPromptBridgeInterface *bridge_;
}

@property(nonatomic) struct PasswordPromptBridgeInterface *bridge; // @synthesize bridge=bridge_;
- (id).cxx_construct;
- (void).cxx_destruct;
- (void)loadCredentialItems;
- (void)onSignInClicked:(id)arg1;
- (void)onCredentialClicked:(id)arg1;
- (void)onCancelClicked:(id)arg1;
- (BOOL)textView:(id)arg1 clickedOnLink:(id)arg2 atIndex:(unsigned long long)arg3;
- (void)loadView;
- (id)defaultButton;
- (id)initWithBridge:(struct PasswordPromptBridgeInterface *)arg1;
@property(readonly, nonatomic) NSTextView *titleView;
@property(readonly, nonatomic) NSArray *credentialButtons;
@property(readonly, nonatomic) NSButton *signInButton;
@property(readonly, nonatomic) NSButton *cancelButton;
- (id)initWithBridge:(struct PasswordPromptBridgeInterface *)arg1 avatarManager:(id)arg2;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

