//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Jun  3 2014 10:55:11).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import <Google Chrome Framework/TranslateInfoBarControllerBase.h>

@interface AfterTranslateInfobarController : TranslateInfoBarControllerBase
{
    _Bool autodeterminedSourceLanguage_;
    _Bool swappedLanugageButtons_;
}

- (_Bool)verifyLayout;
- (id)visibleControls;
- (void)layout;
- (void)loadLabelText;

@end

