//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Jun  3 2014 10:55:11).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

#import "CBPeripheralDelegate.h"

@class NSString;

@interface BluetoothLowEnergyPeripheralDelegate : NSObject <CBPeripheralDelegate>
{
    struct unique_ptr<device::BluetoothLowEnergyPeripheralBridge, std::__1::default_delete<device::BluetoothLowEnergyPeripheralBridge>> bridge_;
}

- (id).cxx_construct;
- (void).cxx_destruct;
- (void)peripheral:(id)arg1 didDiscoverServices:(id)arg2;
- (void)peripheral:(id)arg1 didModifyServices:(id)arg2;
- (void)dealloc;
- (id)initWithBluetoothLowEnergyDeviceMac:(struct BluetoothLowEnergyDeviceMac *)arg1;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

