//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Jun  3 2014 10:55:11).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import <Google Chrome Framework/BookmarkButtonCell.h>

@interface BookmarkBarFolderButtonCell : BookmarkButtonCell
{
}

+ (id)buttonCellForNode:(const struct BookmarkNode *)arg1 text:(id)arg2 image:(id)arg3 menuController:(id)arg4;
- (int)verticalTextOffset;
- (void)setMouseInside:(BOOL)arg1 animate:(BOOL)arg2;
- (BOOL)isFolderButtonCell;

@end

