//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Jun  3 2014 10:55:11).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

@class BookmarkButton, NSEvent, NSPasteboardItem, NSWindow;

@protocol BookmarkButtonDelegate
- (void)bookmarkDragDidEnd:(BookmarkButton *)arg1 operation:(unsigned long long)arg2;
- (void)didDragBookmarkToTrash:(BookmarkButton *)arg1;
- (BOOL)canDragBookmarkButtonToTrash:(BookmarkButton *)arg1;
- (NSWindow *)browserWindow;
- (BOOL)dragShouldLockBarVisibility;
- (void)mouseExitedButton:(id)arg1 event:(NSEvent *)arg2;
- (void)mouseEnteredButton:(id)arg1 event:(NSEvent *)arg2;
- (NSPasteboardItem *)pasteboardItemForDragOfButton:(BookmarkButton *)arg1;

@optional
- (void)willBeginPasteboardDrag;
@end

