//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Jun  3 2014 10:55:11).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

#import "NSMenuDelegate.h"

@class NSMenu, NSString;

@interface BookmarkMenuCocoaController : NSObject <NSMenuDelegate>
{
    struct BookmarkMenuBridge *bridge_;
    struct scoped_nsobject<NSMenu> menu_;
}

+ (id)tooltipForNode:(const struct BookmarkNode *)arg1;
+ (id)menuTitleForNode:(const struct BookmarkNode *)arg1;
- (id).cxx_construct;
- (void).cxx_destruct;
- (void)openAllBookmarksIncognitoWindow:(id)arg1;
- (void)openAllBookmarksNewWindow:(id)arg1;
- (void)openAllBookmarks:(id)arg1;
- (void)openBookmarkMenuItem:(id)arg1;
- (void)openAll:(long long)arg1 withDisposition:(int)arg2;
- (void)openURLForNode:(const struct BookmarkNode *)arg1;
- (const struct BookmarkNode *)nodeForIdentifier:(int)arg1;
- (void)menuNeedsUpdate:(id)arg1;
- (BOOL)validateMenuItem:(id)arg1;
@property(readonly, nonatomic) NSMenu *menu;
- (void)dealloc;
- (id)initWithBridge:(struct BookmarkMenuBridge *)arg1 andMenu:(id)arg2;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

