//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Jun  3 2014 10:55:11).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import <Google Chrome Framework/ToolTipBaseView.h>

#import "NSDraggingSource.h"
#import "NSTextInputClient.h"
#import "NSUserInterfaceValidations.h"

@class NSString;

@interface BridgedContentView : ToolTipBaseView <NSTextInputClient, NSUserInterfaceValidations, NSDraggingSource>
{
    struct View *hostedView_;
    struct TextInputClient *textInputClient_;
    struct ScopedCrTrackingArea cursorTrackingArea_;
    BOOL inKeyDown_;
    basic_string_61b65554 lastTooltipText_;
    BOOL drawMenuBackgroundForBlur_;
    BOOL mouseDownCanMoveWindow_;
    struct scoped_nsobject<NSBezierPath> windowMask_;
}

@property BOOL mouseDownCanMoveWindow; // @synthesize mouseDownCanMoveWindow=mouseDownCanMoveWindow_;
@property(nonatomic) BOOL drawMenuBackgroundForBlur; // @synthesize drawMenuBackgroundForBlur=drawMenuBackgroundForBlur_;
@property(nonatomic) struct TextInputClient *textInputClient; // @synthesize textInputClient=textInputClient_;
@property(readonly, nonatomic) struct View *hostedView; // @synthesize hostedView=hostedView_;
- (id).cxx_construct;
- (void).cxx_destruct;
- (id)accessibilityHitTest:(struct CGPoint)arg1;
- (id)accessibilityAttributeValue:(id)arg1;
- (void)draggingSession:(id)arg1 endedAtPoint:(struct CGPoint)arg2 operation:(unsigned long long)arg3;
- (unsigned long long)draggingSession:(id)arg1 sourceOperationMaskForDraggingContext:(long long)arg2;
- (BOOL)validateUserInterfaceItem:(id)arg1;
- (id)validAttributesForMarkedText;
- (void)unmarkText;
- (void)setMarkedText:(id)arg1 selectedRange:(struct _NSRange)arg2 replacementRange:(struct _NSRange)arg3;
- (struct _NSRange)selectedRange;
- (struct _NSRange)markedRange;
- (void)insertText:(id)arg1 replacementRange:(struct _NSRange)arg2;
- (BOOL)hasMarkedText;
- (struct CGRect)firstRectForCharacterRange:(struct _NSRange)arg1 actualRange:(struct _NSRange *)arg2;
- (void)doCommandBySelector:(SEL)arg1;
- (unsigned long long)characterIndexForPoint:(struct CGPoint)arg1;
- (id)attributedSubstringForProposedRange:(struct _NSRange)arg1 actualRange:(struct _NSRange *)arg2;
- (BOOL)readSelectionFromPasteboard:(id)arg1;
- (BOOL)writeSelectionToPasteboard:(id)arg1 types:(id)arg2;
- (id)validRequestorForSendType:(id)arg1 returnType:(id)arg2;
- (void)cancelOperation:(id)arg1;
- (void)deleteToEndOfParagraph:(id)arg1;
- (void)deleteToBeginningOfParagraph:(id)arg1;
- (void)deleteToEndOfLine:(id)arg1;
- (void)deleteToBeginningOfLine:(id)arg1;
- (void)deleteWordBackward:(id)arg1;
- (void)deleteWordForward:(id)arg1;
- (void)deleteBackward:(id)arg1;
- (void)deleteForward:(id)arg1;
- (void)moveToRightEndOfLineAndModifySelection:(id)arg1;
- (void)moveToLeftEndOfLineAndModifySelection:(id)arg1;
- (void)moveToRightEndOfLine:(id)arg1;
- (void)moveToLeftEndOfLine:(id)arg1;
- (void)moveWordLeftAndModifySelection:(id)arg1;
- (void)moveWordRightAndModifySelection:(id)arg1;
- (void)moveLeftAndModifySelection:(id)arg1;
- (void)moveRightAndModifySelection:(id)arg1;
- (void)moveWordLeft:(id)arg1;
- (void)moveWordRight:(id)arg1;
- (void)moveParagraphBackwardAndModifySelection:(id)arg1;
- (void)moveParagraphForwardAndModifySelection:(id)arg1;
- (void)pageUpAndModifySelection:(id)arg1;
- (void)pageDownAndModifySelection:(id)arg1;
- (void)moveToBeginningOfDocumentAndModifySelection:(id)arg1;
- (void)moveToEndOfDocumentAndModifySelection:(id)arg1;
- (void)moveToEndOfParagraphAndModifySelection:(id)arg1;
- (void)moveToBeginningOfParagraphAndModifySelection:(id)arg1;
- (void)moveToEndOfLineAndModifySelection:(id)arg1;
- (void)moveToBeginningOfLineAndModifySelection:(id)arg1;
- (void)moveDownAndModifySelection:(id)arg1;
- (void)moveUpAndModifySelection:(id)arg1;
- (void)moveWordBackwardAndModifySelection:(id)arg1;
- (void)moveWordForwardAndModifySelection:(id)arg1;
- (void)moveForwardAndModifySelection:(id)arg1;
- (void)moveBackwardAndModifySelection:(id)arg1;
- (void)pageUp:(id)arg1;
- (void)pageDown:(id)arg1;
- (void)moveToBeginningOfDocument:(id)arg1;
- (void)moveToEndOfDocument:(id)arg1;
- (void)moveToEndOfParagraph:(id)arg1;
- (void)moveToBeginningOfParagraph:(id)arg1;
- (void)moveToEndOfLine:(id)arg1;
- (void)moveToBeginningOfLine:(id)arg1;
- (void)moveWordBackward:(id)arg1;
- (void)moveWordForward:(id)arg1;
- (void)moveDown:(id)arg1;
- (void)moveUp:(id)arg1;
- (void)moveLeft:(id)arg1;
- (void)moveBackward:(id)arg1;
- (void)moveRight:(id)arg1;
- (void)moveForward:(id)arg1;
- (void)insertText:(id)arg1;
- (void)scrollWheel:(id)arg1;
- (void)keyDown:(id)arg1;
- (id)inputContext;
- (BOOL)performDragOperation:(id)arg1;
- (unsigned long long)draggingUpdated:(id)arg1;
- (unsigned long long)draggingEntered:(id)arg1;
- (BOOL)acceptsFirstMouse:(id)arg1;
- (void)drawRect:(struct CGRect)arg1;
- (void)viewDidEndLiveResize;
- (void)setFrameSize:(struct CGSize)arg1;
- (void)viewDidMoveToWindow;
- (BOOL)resignFirstResponder;
- (BOOL)becomeFirstResponder;
- (BOOL)acceptsFirstResponder;
- (void)mouseEvent:(id)arg1;
- (void)enableTracking;
- (void)selectAll:(id)arg1;
- (void)paste:(id)arg1;
- (void)copy:(id)arg1;
- (void)cut:(id)arg1;
- (void)redo:(id)arg1;
- (void)undo:(id)arg1;
- (struct DragDropClientMac *)dragDropClient;
- (void)onFullKeyboardAccessModeChanged:(id)arg1;
- (void)handleAction:(int)arg1 keyCode:(int)arg2 domCode:(int)arg3 eventFlags:(int)arg4;
- (void)handleKeyEvent:(id)arg1;
- (void)updateFullKeyboardAccess;
- (void)updateWindowMask;
- (void)updateTooltipIfRequiredAt:(const struct Point *)arg1;
- (void)processCapturedMouseEvent:(id)arg1;
- (void)clearView;
- (id)initWithView:(struct View *)arg1;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

