//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Jun  3 2014 10:55:11).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSViewController.h"

#import "NSTextFieldDelegate.h"
#import "NSWindowDelegate.h"

@class NSString;

@interface CardUnmaskPromptViewCocoa : NSViewController <NSWindowDelegate, NSTextFieldDelegate>
{
    scoped_nsobject_02675140 permanentErrorBox_;
    struct scoped_nsobject<NSView> expirationView_;
    struct scoped_nsobject<NSView> inputRowView_;
    struct scoped_nsobject<NSView> progressOverlayView_;
    struct scoped_nsobject<NSView> storageView_;
    scoped_nsobject_0ef9b51e titleLabel_;
    scoped_nsobject_0ef9b51e permanentErrorLabel_;
    scoped_nsobject_0ef9b51e instructionsLabel_;
    struct scoped_nsobject<AutofillTextField> cvcInput_;
    struct scoped_nsobject<AutofillPopUpButton> monthPopup_;
    struct scoped_nsobject<AutofillPopUpButton> yearPopup_;
    struct scoped_nsobject<NSImageView> cvcImageView_;
    scoped_nsobject_6cadfeaf newCardButton_;
    scoped_nsobject_6cadfeaf cancelButton_;
    scoped_nsobject_6cadfeaf verifyButton_;
    scoped_nsobject_6cadfeaf storageCheckbox_;
    struct scoped_nsobject<AutofillTooltipController> storageTooltip_;
    scoped_nsobject_0ef9b51e errorLabel_;
    scoped_nsobject_0ef9b51e progressOverlayLabel_;
    struct scoped_nsobject<SpinnerView> progressOverlaySpinner_;
    int monthPopupDefaultIndex_;
    int yearPopupDefaultIndex_;
    struct CardUnmaskPromptViewBridge *bridge_;
}

+ (void)verticallyCenterSubviewsInView:(id)arg1;
+ (void)sizeToFitView:(id)arg1;
+ (scoped_nsobject_02675140)createPlainBox;
+ (id)buildDatePopupWithModel:(struct ComboboxModel *)arg1;
- (id).cxx_construct;
- (void).cxx_destruct;
- (void)loadView;
- (void)performLayoutAndDisplay:(BOOL)arg1;
- (void)createStorageViewWithController:(struct CardUnmaskPromptController *)arg1;
- (void)createExpirationView;
- (void)createNewCardButton;
- (void)updateInstructionsText;
- (void)controlTextDidChange:(id)arg1;
- (void)onExpirationDateChanged:(id)arg1;
- (BOOL)expirationDateIsValid;
- (void)onNewCard:(id)arg1;
- (void)onCancel:(id)arg1;
- (void)onVerify:(id)arg1;
- (void)updateVerifyButtonEnabled;
- (void)setPermanentErrorMessage:(const basic_string_61b65554 *)arg1;
- (void)setRetriableErrorMessage:(const basic_string_61b65554 *)arg1;
- (void)setInputsEnabled:(BOOL)arg1;
- (void)setProgressOverlayText:(const basic_string_61b65554 *)arg1 showSpinner:(BOOL)arg2;
- (void)updateProgressOverlayOrigin;
- (id)initWithBridge:(struct CardUnmaskPromptViewBridge *)arg1;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

