//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Jun  3 2014 10:55:11).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import <Google Chrome Framework/HoverImageButton.h>

@interface ChosenObjectDeleteButton : HoverImageButton
{
    unique_ptr_fa8befec objectInfo_;
    Callback_1cddaf27 callback_;
}

- (id).cxx_construct;
- (void).cxx_destruct;
- (void)deleteClicked:(id)arg1;
- (id)initWithChosenObject:(unique_ptr_fa8befec)arg1 atPoint:(struct CGPoint)arg2 withCallback:(Callback_1cddaf27)arg3;

@end

