//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Jun  3 2014 10:55:11).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSButton.h"

@interface ConstrainedWindowButton : NSButton
{
    struct ScopedCrTrackingArea trackingArea_;
}

+ (void)DrawBorderForPath:(id)arg1 withCell:(id)arg2 inView:(id)arg3;
+ (void)DrawInnerHighlightForPath:(id)arg1 withCell:(id)arg2 inView:(id)arg3;
+ (void)DrawBackgroundAndShadowForPath:(id)arg1 withCell:(id)arg2 inView:(id)arg3;
+ (Class)cellClass;
- (id).cxx_construct;
- (void).cxx_destruct;
- (void)sizeToFit;
- (BOOL)isMouseReallyInside;
- (void)mouseExited:(id)arg1;
- (void)mouseEntered:(id)arg1;
- (void)updateTrackingAreas;

@end

