//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Jun  3 2014 10:55:11).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class NSView, NSWindow;

@interface ConstrainedWindowSheetInfo : NSObject
{
    struct scoped_nsprotocol<id<ConstrainedWindowSheet>> sheet_;
    struct scoped_nsobject<NSView> parentView_;
    struct scoped_nsobject<NSWindow> overlayWindow_;
    BOOL sheetDidShow_;
}

@property(nonatomic) BOOL sheetDidShow; // @synthesize sheetDidShow=sheetDidShow_;
- (id).cxx_construct;
- (void).cxx_destruct;
- (void)showSheet;
- (void)hideSheet;
@property(readonly, nonatomic) NSWindow *overlayWindow;
@property(readonly, nonatomic) NSView *parentView;
@property(readonly, nonatomic) id <ConstrainedWindowSheet> sheet;
- (id)initWithSheet:(id)arg1 parentView:(id)arg2 overlayWindow:(id)arg3;

@end

