//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Jun  3 2014 10:55:11).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import <Google Chrome Framework/BaseBubbleController.h>

@class NSButton, NSMatrix, NSTextField, NSView;

@interface ContentSettingBubbleController : BaseBubbleController
{
    NSTextField *titleLabel_;
    NSMatrix *allowBlockRadioGroup_;
    NSButton *manageButton_;
    NSButton *doneButton_;
    NSButton *loadButton_;
    NSView *contentsContainer_;
    NSTextField *blockedResourcesField_;
    struct unique_ptr<ContentSettingBubbleModel, std::__1::default_delete<ContentSettingBubbleModel>> contentSettingBubbleModel_;
    struct unique_ptr<ContentSettingBubbleWebContentsObserverBridge, std::__1::default_delete<ContentSettingBubbleWebContentsObserverBridge>> observerBridge_;
    struct map<NSButton *, int, std::__1::less<NSButton *>, std::__1::allocator<std::__1::pair<NSButton *const, int>>> popupLinks_;
    map_e1ccd0c7 mediaMenus_;
}

+ (id)showForModel:(struct ContentSettingBubbleModel *)arg1 webContents:(struct WebContents *)arg2 parentWindow:(id)arg3 anchoredAt:(struct CGPoint)arg4;
- (id).cxx_construct;
- (void).cxx_destruct;
- (map_e1ccd0c7 *)mediaMenus;
- (void)mediaMenuChanged:(id)arg1;
- (void)closeBubble:(id)arg1;
- (void)manageBlocking:(id)arg1;
- (void)learnMoreLinkClicked:(id)arg1;
- (void)load:(id)arg1;
- (void)showMoreInfo:(id)arg1;
- (void)clearMIDISysExForCurrentHost:(id)arg1;
- (void)clearGeolocationForCurrentHost:(id)arg1;
- (void)popupLinkClicked:(id)arg1;
- (void)allowBlockToggled:(id)arg1;
- (void)awakeFromNib;
- (void)initManageDoneButtons;
- (void)sizeToFitLoadButton;
- (void)initializeMIDISysExLists;
- (void)initializeMediaMenus;
- (void)initializeGeoLists;
- (void)initializeItemList;
- (void)initializeBlockedPluginsList;
- (id)hyperlinkButtonWithFrame:(struct CGRect)arg1 title:(id)arg2 icon:(id)arg3 referenceFrame:(struct CGRect)arg4;
- (void)initializeRadioGroup;
- (void)initializeTitle;
- (void)dealloc;
- (id)initWithModel:(struct ContentSettingBubbleModel *)arg1 webContents:(struct WebContents *)arg2 parentWindow:(id)arg3 anchoredAt:(struct CGPoint)arg4;

@end

