//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Jun  3 2014 10:55:11).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import <Google Chrome Framework/GradientButtonCell.h>

#import "NSAnimationDelegate.h"

@class NSFont, NSString;

@interface DownloadItemCell : GradientButtonCell <NSAnimationDelegate>
{
    int mousePosition_;
    int mouseInsideCount_;
    struct scoped_nsobject<NSTrackingArea> trackingAreaButton_;
    struct scoped_nsobject<NSTrackingArea> trackingAreaDropdown_;
    struct FilePath downloadPath_;
    NSString *secondaryTitle_;
    NSFont *secondaryFont_;
    int percentDone_;
    struct scoped_nsobject<NSAnimation> completionAnimation_;
    struct TimeTicks progressStartTime_;
    struct scoped_nsobject<IndeterminateProgressTimer> indeterminateProgressTimer_;
    BOOL isStatusTextVisible_;
    double titleY_;
    double statusAlpha_;
    struct scoped_nsobject<NSAnimation> toggleStatusVisibilityAnimation_;
    struct unique_ptr<ui::ThemeProvider, std::__1::default_delete<ui::ThemeProvider>> themeProvider_;
}

@property(retain, nonatomic) NSFont *secondaryFont; // @synthesize secondaryFont=secondaryFont_;
@property(copy, nonatomic) NSString *secondaryTitle; // @synthesize secondaryTitle=secondaryTitle_;
- (id).cxx_construct;
- (void).cxx_destruct;
- (void)skipVisibilityAnimation;
- (double)titleY;
- (double)statusTextAlpha;
- (BOOL)isStatusTextVisible;
- (void)animationDidEnd:(id)arg1;
- (void)stopIndeterminateAnimation;
- (void)updateIndeterminateDownload;
- (void)animation:(id)arg1 progressed:(float)arg2;
- (id)indeterminateProgressTimer;
- (void)hideSecondaryTitle;
- (void)showSecondaryTitle;
- (void)setupToggleStatusVisibilityAnimation;
- (struct CGRect)imageRectForBounds:(struct CGRect)arg1;
- (void)drawInteriorWithFrame:(struct CGRect)arg1 inView:(id)arg2;
- (void)drawWithFrame:(struct CGRect)arg1 inView:(id)arg2;
- (BOOL)isDefaultTheme;
- (void)drawSecondaryTitleInRect:(struct CGRect)arg1;
- (id)titleColorForPart:(int)arg1;
- (BOOL)pressedWithDefaultThemeOnPart:(int)arg1;
- (const struct ThemeProvider *)backgroundThemeWrappingProvider:(const struct ThemeProvider *)arg1;
- (id)elideStatus:(int)arg1;
- (id)elideTitle:(int)arg1;
- (id)rightRoundedPath:(double)arg1 inRect:(struct CGRect)arg2;
- (id)leftRoundedPath:(double)arg1 inRect:(struct CGRect)arg2;
- (BOOL)isDropdownPartPressed;
- (BOOL)isMouseOverDropdownPart;
- (BOOL)isButtonPartPressed;
- (BOOL)isMouseOverButtonPart;
- (BOOL)isMouseInside;
- (void)mouseExited:(id)arg1;
- (void)mouseEntered:(id)arg1;
- (void)setShowsBorderOnlyWhileMouseInside:(BOOL)arg1;
- (void)updateTrackingAreas:(id)arg1;
- (void)setStateFromDownload:(struct DownloadItemModel *)arg1;
- (void)dealloc;
- (id)initTextCell:(id)arg1;
- (id)initWithCoder:(id)arg1;
- (void)setInitialState;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

