//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Jun  3 2014 10:55:11).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSAnimation.h"

@class DownloadItemCell;

@interface DownloadItemCellAnimation : NSAnimation
{
    DownloadItemCell *cell_;
}

- (void)setCurrentProgress:(float)arg1;
- (id)initWithDownloadItemCell:(id)arg1 duration:(double)arg2 animationCurve:(unsigned long long)arg3;

@end

