//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Jun  3 2014 10:55:11).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import <Google Chrome Framework/MenuController.h>

@interface DownloadShelfContextMenuController : MenuController
{
    struct scoped_nsobject<DownloadItemController> itemController_;
    id <NSMenuDelegate> menuDelegate_;
}

- (id).cxx_construct;
- (void).cxx_destruct;
- (void)menuDidClose:(id)arg1;
- (id)initWithItemController:(id)arg1 withDelegate:(id)arg2;

@end

