//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Jun  3 2014 10:55:11).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class NSNumber, NSString;

@interface ElementAppleScript : NSObject
{
    NSNumber *uniqueID_;
    id container_;
    NSString *containerProperty_;
}

@property(copy, nonatomic) NSString *containerProperty; // @synthesize containerProperty=containerProperty_;
@property(retain, nonatomic) id container; // @synthesize container=container_;
@property(copy, nonatomic) NSNumber *uniqueID; // @synthesize uniqueID=uniqueID_;
- (void)dealloc;
- (void)setContainer:(id)arg1 property:(id)arg2;
- (id)objectSpecifier;

@end

