//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Jun  3 2014 10:55:11).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class NSAlert;

@interface ExternalProtocolDialogController : NSObject
{
    NSAlert *alert_;
    struct GURL url_;
    int render_process_host_id_;
    int routing_id_;
    struct Time creation_time_;
}

- (id).cxx_construct;
- (void).cxx_destruct;
- (void)alertEnded:(id)arg1 returnCode:(int)arg2 contextInfo:(void *)arg3;
- (void)dealloc;
- (id)initWithGURL:(const struct GURL *)arg1 renderProcessHostId:(int)arg2 routingId:(int)arg3;

@end

