//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Jun  3 2014 10:55:11).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import <Google Chrome Framework/GTMABRecord.h>

@interface GTMABPerson : GTMABRecord
{
}

+ (long long)typeOfProperty:(id)arg1;
+ (unsigned int)compositeNameFormat;
+ (id)localizedPropertyName:(id)arg1;
+ (id)personWithFirstName:(id)arg1 lastName:(id)arg2;
- (id)description;
- (id)compositeName;
- (id)imageData;
- (BOOL)setImage:(struct NSImage *)arg1;
- (struct NSImage *)image;
- (BOOL)setImageData:(id)arg1;
- (id)init;

@end

