//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Jun  3 2014 10:55:11).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

#import "NSConnectionDelegate.h"

@class NSConnection, NSPort, NSString, Protocol;

@interface GTMAbstractDOListener : NSObject <NSConnectionDelegate>
{
    NSString *registeredName_;
    Protocol *protocol_;
    NSConnection *connection_;
    BOOL isRunningInNewThread_;
    BOOL shouldShutdown_;
    double requestTimeout_;
    double replyTimeout_;
    NSPort *port_;
    double heartRate_;
}

+ (id)allListeners;
+ (void)initialize;
- (void)shutdown;
- (void)runInNewThreadWithErrorTarget:(id)arg1 selector:(SEL)arg2 withObjectArgument:(id)arg3;
- (BOOL)runInCurrentThread;
@property(readonly, copy) NSString *description;
- (id)connection;
- (double)ThreadHeartRate;
- (void)setThreadHeartRate:(double)arg1;
- (void)setReplyTimeout:(double)arg1;
- (double)replyTimeout;
- (void)setRequestTimeout:(double)arg1;
- (double)requestTimeout;
- (void)setRegisteredName:(id)arg1;
- (id)registeredName;
- (void)dealloc;
- (id)initWithRegisteredName:(id)arg1 protocol:(id)arg2 port:(id)arg3;
- (id)initWithRegisteredName:(id)arg1 protocol:(id)arg2;
- (id)init;
- (id)portDescription;
- (void)stopListening;
- (BOOL)startListening;
- (void)threadMain:(id)arg1;
- (BOOL)doRunInitialization;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

