//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Jun  3 2014 10:55:11).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class NSArray;

@interface GTMGetURLHandler : NSObject
{
    NSArray *urlTypes_;
}

+ (id)handlerForBundle:(id)arg1;
+ (void)getUrl:(id)arg1 withReplyEvent:(id)arg2;
+ (void)load;
- (void)addError:(int)arg1 withDescription:(id)arg2 toDescriptor:(id)arg3;
- (void)getUrl:(id)arg1 withReplyEvent:(id)arg2;
- (Class)getClassForScheme:(id)arg1 withReplyEvent:(id)arg2;
- (id)extractURLFromEvent:(id)arg1 withReplyEvent:(id)arg2;
- (void)dealloc;
- (id)initWithTypes:(id)arg1;

@end

