//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Jun  3 2014 10:55:11).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class NSDictionary, NSString;

@interface GTMGoogleSearch : NSObject
{
    NSString *allAppsCachedDomain_;
    NSString *allAppsCachedLanguage_;
    NSString *curAppCachedDomain_;
    NSString *curAppCachedLanguage_;
    NSDictionary *globalSearchArguments_;
}

+ (id)sharedInstance;
- (BOOL)performQuery:(id)arg1 ofType:(id)arg2 arguments:(id)arg3;
- (id)searchURLFor:(id)arg1 ofType:(id)arg2 arguments:(id)arg3;
- (void)setGlobalSearchArguments:(id)arg1;
- (id)globalSearchArguments;
- (void)clearPreferredDomainAndLanguageForAllApps;
- (void)clearPreferredDomainAndLanguageForCurrentApplication;
- (void)updatePreferredDomain:(id)arg1 language:(id)arg2 currentApplicationOnly:(BOOL)arg3;
- (void)preferredDomain:(id *)arg1 language:(id *)arg2 areCurrentAppOnly:(char *)arg3;
- (void)dealloc;
- (void)finalize;
- (id)init;
- (void)updateAllAppsDomain:(id)arg1 language:(id)arg2;
- (void)reloadAllAppCachedValues:(id)arg1;
- (void)defaultDomain:(id *)arg1 language:(id *)arg2;

@end

