//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Jun  3 2014 10:55:11).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSTextView.h"

@class GTMHotKeyTextFieldCell;

@interface GTMHotKeyFieldEditor : NSTextView
{
    GTMHotKeyTextFieldCell *cell_;
}

+ (id)sharedHotKeyFieldEditor;
- (id)hotKeyForEvent:(id)arg1;
- (void)processEventToHotKeyAndString:(id)arg1;
- (BOOL)shouldBypassEvent:(id)arg1;
- (BOOL)performKeyEquivalent:(id)arg1;
- (void)keyDown:(id)arg1;
- (struct _NSRange)selectionRangeForProposedRange:(struct _NSRange)arg1 granularity:(unsigned long long)arg2;
- (BOOL)shouldDrawInsertionPoint;
- (void)windowResigned:(id)arg1;
- (BOOL)resignFirstResponder;
- (BOOL)becomeFirstResponder;
- (id)writablePasteboardTypes;
- (id)readablePasteboardTypes;
- (id)acceptableDragTypes;
- (void)setCell:(id)arg1;
- (id)cell;
- (void)dealloc;
- (id)init;

@end

