//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Jun  3 2014 10:55:11).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

#import "NSCopying.h"

@interface GTMHotKey : NSObject <NSCopying>
{
    unsigned long long modifiers_;
    unsigned long long keyCode_;
    BOOL doubledModifier_;
}

+ (id)hotKeyWithKeyCode:(unsigned long long)arg1 modifiers:(unsigned long long)arg2 useDoubledModifier:(BOOL)arg3;
- (id)description;
- (id)copyWithZone:(struct _NSZone *)arg1;
- (unsigned long long)hash;
- (BOOL)isEqual:(id)arg1;
- (BOOL)doubledModifier;
- (unsigned long long)keyCode;
- (unsigned long long)modifiers;
- (id)initWithKeyCode:(unsigned long long)arg1 modifiers:(unsigned long long)arg2 useDoubledModifier:(BOOL)arg3;

@end

