//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Jun  3 2014 10:55:11).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSProxy.h"

@class NSDistantObject, NSString, Protocol;

@interface GTMTransientRootProxy : NSProxy
{
    Protocol *protocol_;
    NSDistantObject *realProxy_;
    NSString *registeredName_;
    NSString *host_;
    double requestTimeout_;
    double replyTimeout_;
}

+ (id)rootProxyWithRegisteredName:(id)arg1 host:(id)arg2 protocol:(id)arg3 requestTimeout:(double)arg4 replyTimeout:(double)arg5;
- (void)forwardInvocation:(id)arg1;
- (id)methodSignatureForSelector:(SEL)arg1;
- (BOOL)isConnected;
- (void)dealloc;
- (id)init;
- (id)initWithRegisteredName:(id)arg1 host:(id)arg2 protocol:(id)arg3 requestTimeout:(double)arg4 replyTimeout:(double)arg5;
- (void)releaseRealProxy;
- (void)connectionDidDie:(id)arg1;
- (id)realProxy;
- (id)makeConnection;

@end

