//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Jun  3 2014 10:55:11).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class NSBundle;

@interface GTMUILocalizer : NSObject
{
    id owner_;
    id otherObjectToLocalize_;
    id yetAnotherObjectToLocalize_;
    NSBundle *bundle_;
}

+ (id)bundleForOwner:(id)arg1;
- (void)localizeAccessibility:(id)arg1;
- (void)localizeBindings:(id)arg1;
- (void)localizeCell:(id)arg1 recursively:(BOOL)arg2;
- (void)localizeMenu:(id)arg1 recursively:(BOOL)arg2;
- (void)localizeView:(id)arg1 recursively:(BOOL)arg2;
- (void)localizeToolbar:(id)arg1;
- (void)localizeWindow:(id)arg1 recursively:(BOOL)arg2;
- (void)localizeObject:(id)arg1 recursively:(BOOL)arg2;
- (id)localizedStringForString:(id)arg1;
- (void)awakeFromNib;
- (void)dealloc;
- (id)initWithBundle:(id)arg1;
- (void)localizedObjects;

@end

