//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Jun  3 2014 10:55:11).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class NSArray;

@interface GTMWorkspaceRunningApplicationList : NSObject
{
    NSArray *launchedApps_;
}

+ (id)sharedApplicationList;
- (id)launchedApplications;
- (id)currentApps;
- (void)didLaunchOrTerminateApp:(id)arg1;
- (void)dealloc;
- (void)finalize;
- (id)init;

@end

