//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Jun  3 2014 10:55:11).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSAnimation.h"

@class AnimatableView;

@interface HeightAnimation : NSAnimation
{
    AnimatableView *view_;
    double startHeight_;
    double endHeight_;
}

- (void)setCurrentProgress:(float)arg1;
- (id)initWithView:(id)arg1 finalHeight:(double)arg2 duration:(double)arg3;

@end

