//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Jun  3 2014 10:55:11).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

#import "ICDeviceBrowserDelegate.h"

@class NSString;

@interface ImageCaptureDeviceManagerImpl : NSObject <ICDeviceBrowserDelegate>
{
    struct scoped_nsobject<ICDeviceBrowser> deviceBrowser_;
    scoped_nsobject_9420f295 cameras_;
    struct Receiver *notifications_;
}

- (id).cxx_construct;
- (void).cxx_destruct;
- (id)deviceBrowserForTest;
- (void)deviceBrowser:(id)arg1 didRemoveDevice:(id)arg2 moreGoing:(BOOL)arg3;
- (void)deviceBrowser:(id)arg1 didAddDevice:(id)arg2 moreComing:(BOOL)arg3;
- (id)deviceForUUID:(const basic_string_805fe43b *)arg1;
- (void)close;
- (void)setNotifications:(struct Receiver *)arg1;
- (id)init;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

