//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Jun  3 2014 10:55:11).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

#import "ICCameraDeviceDelegate.h"
#import "ICCameraDeviceDownloadDelegate.h"

@class NSString;

@interface ImageCaptureDevice : NSObject <ICCameraDeviceDelegate, ICCameraDeviceDownloadDelegate>
{
    struct scoped_nsobject<ICCameraDevice> camera_;
    WeakPtr_15e7b238 listener_;
    _Bool closing_;
}

- (id).cxx_construct;
- (void).cxx_destruct;
- (void)didDownloadFile:(id)arg1 error:(id)arg2 options:(id)arg3 contextInfo:(void *)arg4;
- (void)deviceDidBecomeReadyWithCompleteContentCatalog:(id)arg1;
- (void)device:(id)arg1 didEncounterError:(id)arg2;
- (void)device:(id)arg1 didOpenSessionWithError:(id)arg2;
- (void)didRemoveDevice:(id)arg1;
- (void)cameraDevice:(id)arg1 didAddItems:(id)arg2;
- (void)cameraDevice:(id)arg1 didAddItem:(id)arg2;
- (void)downloadFile:(const basic_string_805fe43b *)arg1 localPath:(const struct FilePath *)arg2;
- (void)eject;
- (void)close;
- (void)open;
- (void)setListener:(WeakPtr_15e7b238)arg1;
- (void)dealloc;
- (id)initWithCameraDevice:(id)arg1;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

