//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Jun  3 2014 10:55:11).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class InfoBubbleWindow;

@interface InfoBubbleWindowCloser : NSObject
{
    InfoBubbleWindow *window_;
}

- (void)animationDidStop:(id)arg1 finished:(BOOL)arg2;
- (id)initWithWindow:(id)arg1;

@end

