//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Jun  3 2014 10:55:11).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import <Google Chrome Framework/VerticalGradientView.h>

@interface InfoBarGradientView : VerticalGradientView
{
    double arrowHeight_;
    double arrowHalfWidth_;
    double arrowX_;
    BOOL hasTip_;
}

@property(nonatomic) BOOL hasTip; // @synthesize hasTip=hasTip_;
@property(nonatomic) double arrowX; // @synthesize arrowX=arrowX_;
@property(nonatomic) double arrowHalfWidth; // @synthesize arrowHalfWidth=arrowHalfWidth_;
@property(nonatomic) double arrowHeight; // @synthesize arrowHeight=arrowHeight_;
- (id)accessibilityAttributeValue:(id)arg1;
- (BOOL)accessibilityIsIgnored;
- (BOOL)mouseDownCanMoveWindow;
- (void)drawRect:(struct CGRect)arg1;
- (id)strokeColor;
- (void)setInfobarType:(int)arg1;
- (id)initWithCoder:(id)arg1;
- (id)initWithFrame:(struct CGRect)arg1;

@end

