//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Jun  3 2014 10:55:11).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

#import "NSAlertDelegate.h"

@class NSString;

@interface JavaScriptAppModalDialogHelper : NSObject <NSAlertDelegate>
{
    struct scoped_nsobject<NSAlert> alert_;
    struct JavaScriptAppModalDialogCocoa *nativeDialog_;
    scoped_nsobject_0ef9b51e textField_;
    BOOL alertShown_;
}

- (id).cxx_construct;
- (void).cxx_destruct;
- (_Bool)shouldSuppress;
- (basic_string_61b65554)input;
- (void)destroyNativeDialog;
- (void)sendCloseToNativeDialog;
- (void)sendCancelToNativeDialog;
- (void)sendAcceptToNativeDialog;
- (void)closeWindow;
- (void)cancelAlert;
- (void)acceptAlert;
- (void)showAlert;
- (void)alertDidEnd:(id)arg1 returnCode:(int)arg2 contextInfo:(void *)arg3;
- (void)addTextFieldWithPrompt:(id)arg1;
- (id)alert;
- (id)initWithNativeDialog:(struct JavaScriptAppModalDialogCocoa *)arg1;
- (id)init;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

