//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Jun  3 2014 10:55:11).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSPopUpButton.h"

@interface MCDropDown : NSPopUpButton
{
    struct scoped_nsobject<NSColor> backgroundColor_;
}

- (id).cxx_construct;
- (void).cxx_destruct;
- (void)setBackgroundColor:(id)arg1;
- (id)backgroundColor;
- (void)drawRect:(struct CGRect)arg1;
- (BOOL)isOpaque;

@end

