//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Jun  3 2014 10:55:11).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@interface MediaGalleriesCocoaController : NSObject
{
    struct MediaGalleriesDialogCocoa *dialog_;
}

@property(nonatomic) struct MediaGalleriesDialogCocoa *dialog; // @synthesize dialog=dialog_;
- (void)onAuxiliaryButton:(id)arg1;
- (void)onCancelButton:(id)arg1;
- (void)onAcceptButton:(id)arg1;

@end

