//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Jun  3 2014 10:55:11).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSButton.h"

@interface MenuTrackedButton : NSButton
{
    BOOL didEnter_;
    BOOL tracking_;
    long long trackingTag_;
}

@property(readonly, nonatomic, getter=isTracking) BOOL tracking; // @synthesize tracking=tracking_;
- (struct CGRect)insetBounds;
- (void)checkMouseInRect;
- (void)doHighlight:(BOOL)arg1;
- (void)mouseUp:(id)arg1;
- (void)mouseDragged:(id)arg1;
- (void)mouseExited:(id)arg1;
- (void)mouseEntered:(id)arg1;
- (void)viewDidMoveToWindow;
- (void)updateTrackingAreas;

@end

