//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Jun  3 2014 10:55:11).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSAppleEventDescriptor.h"

@interface NSAppleEventDescriptor (GTMAppleEventDescriptorHandlerAdditions)
+ (id)gtm_descriptorWithLabeledHandler:(id)arg1 labels:(unsigned int *)arg2 parameters:(id *)arg3 count:(unsigned long long)arg4;
+ (id)gtm_descriptorWithPositionalHandler:(id)arg1 parametersDescriptor:(id)arg2;
+ (id)gtm_descriptorWithPositionalHandler:(id)arg1 parametersArray:(id)arg2;
- (id)gtm_initWithLabeledHandler:(id)arg1 labels:(unsigned int *)arg2 parameters:(id *)arg3 count:(unsigned long long)arg4;
- (id)gtm_initWithPositionalHandler:(id)arg1 parametersDescriptor:(id)arg2;
- (id)gtm_initWithPositionalHandler:(id)arg1 parametersArray:(id)arg2;
@end

