//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Jun  3 2014 10:55:11).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSEnumerator.h"

@interface NSEnumerator (GTMEnumeratorFilterAdditions)
- (id)gtm_enumeratorByTarget:(id)arg1 performOnEachSelector:(SEL)arg2 withObject:(id)arg3;
- (id)gtm_enumeratorByTarget:(id)arg1 performOnEachSelector:(SEL)arg2;
- (id)gtm_filteredEnumeratorByTarget:(id)arg1 performOnEachSelector:(SEL)arg2 withObject:(id)arg3;
- (id)gtm_filteredEnumeratorByTarget:(id)arg1 performOnEachSelector:(SEL)arg2;
- (id)gtm_enumeratorByMakingEachObjectPerformSelector:(SEL)arg1 withObject:(id)arg2;
- (id)gtm_filteredEnumeratorByMakingEachObjectPerformSelector:(SEL)arg1 withObject:(id)arg2;
@end

