//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Jun  3 2014 10:55:11).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSCell.h"

@interface OmniboxPopupCell : NSCell
{
}

+ (id)createSeparatorStringForDarkTheme:(BOOL)arg1;
+ (double)computeContentsOffset:(const struct AutocompleteMatch *)arg1;
- (double)drawMatchPart:(id)arg1 withFrame:(struct CGRect)arg2 origin:(struct CGPoint)arg3 withMaxWidth:(int)arg4 forDarkTheme:(BOOL)arg5;
- (double)drawMatchPrefixWithFrame:(struct CGRect)arg1 tableView:(id)arg2 withContentsMaxWidth:(int *)arg3 forDarkTheme:(BOOL)arg4;
- (void)drawMatchWithFrame:(struct CGRect)arg1 inView:(id)arg2;
- (void)drawInteriorWithFrame:(struct CGRect)arg1 inView:(id)arg2;

@end

