//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Jun  3 2014 10:55:11).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSWindowController.h"

#import "NSAnimationDelegate.h"
#import "NSWindowDelegate.h"

@class NSString, NSViewAnimation, PanelTitlebarViewCocoa;

@interface PanelWindowControllerCocoa : NSWindowController <NSWindowDelegate, NSAnimationDelegate>
{
    PanelTitlebarViewCocoa *titlebar_view_;
    struct unique_ptr<PanelCocoa, std::__1::default_delete<PanelCocoa>> windowShim_;
    struct scoped_nsobject<NSString> pendingWindowTitle_;
    NSViewAnimation *boundsAnimation_;
    BOOL animateOnBoundsChange_;
    BOOL throbberShouldSpin_;
    BOOL playingMinimizeAnimation_;
    float animationStopToShowTitlebarOnly_;
    BOOL canBecomeKeyWindow_;
    BOOL activationRequestedByPanel_;
    BOOL userResizing_;
    struct ScopedCrTrackingArea trackingArea_;
}

- (id).cxx_construct;
- (void).cxx_destruct;
- (struct CGRect)contentRectForFrameRect:(struct CGRect)arg1;
- (struct CGRect)frameRectForContentRect:(struct CGRect)arg1;
- (BOOL)canResizeByMouseAtCurrentLocation;
- (BOOL)isMiniaturized;
- (void)miniaturize;
- (void)showShadow:(BOOL)arg1;
- (void)updateTrackingArea;
- (void)updateWindowCollectionBehavior;
- (void)updateWindowLevel:(BOOL)arg1;
- (void)updateWindowLevel;
- (BOOL)activationRequestedByPanel;
- (int)numPanels;
- (BOOL)canBecomeKeyWindow;
- (void)fullScreenModeChanged:(_Bool)arg1;
- (void)preventBecomingKeyWindow:(BOOL)arg1;
- (void)onWindowDidResignKey;
- (void)deactivate;
- (void)activate;
- (void)windowDidResize:(id)arg1;
- (struct CGSize)windowWillResize:(id)arg1 toSize:(struct CGSize)arg2;
- (void)windowDidEndLiveResize:(id)arg1;
- (void)windowWillStartLiveResize:(id)arg1;
- (void)windowDidResignKey:(id)arg1;
- (void)windowDidBecomeKey:(id)arg1;
- (int)titlebarHeightInScreenCoordinates;
- (void)onTitlebarDoubleClicked:(int)arg1;
- (void)onTitlebarMouseClicked:(int)arg1;
- (BOOL)isAnimatingBounds;
- (void)terminateBoundsAnimation;
- (void)animationDidStop:(id)arg1;
- (void)animationDidEnd:(id)arg1;
- (void)cleanupAfterAnimation;
- (float)animation:(id)arg1 valueForProgress:(float)arg2;
- (void)setPanelFrame:(struct CGRect)arg1 animate:(BOOL)arg2;
- (void)drag:(struct CGPoint)arg1;
- (void)endDrag:(BOOL)arg1;
- (void)startDrag:(struct CGPoint)arg1;
- (void)windowWillClose:(id)arg1;
- (BOOL)windowShouldClose:(id)arg1;
- (void)restoreButtonClicked:(int)arg1;
- (void)minimizeButtonClicked:(int)arg1;
- (void)closePanel;
- (void)commandDispatch:(id)arg1;
- (BOOL)validateUserInterfaceItem:(id)arg1;
- (id)titlebarView;
- (void)webContentsDetached:(struct WebContents *)arg1;
- (void)webContentsInserted:(struct WebContents *)arg1;
- (void)updateTitleBarMinimizeRestoreButtonVisibility;
- (void)updateThrobber:(BOOL)arg1;
- (void)updateIcon;
- (void)updateTitleBar;
- (void)revealAnimatedWithFrame:(const struct CGRect *)arg1;
- (void)enableWebContentsViewAutosizing;
- (void)disableWebContentsViewAutosizing;
- (void)updateWebContentsViewFrame;
- (void)awakeFromNib;
- (struct Panel *)panel;
- (id)initWithPanel:(struct PanelCocoa *)arg1;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

