//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Jun  3 2014 10:55:11).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSWindowController.h"

#import "NSWindowDelegate.h"

@class NSString;

@interface ReauthDialogWindowController : NSWindowController <NSWindowDelegate>
{
    basic_string_805fe43b emailAddress_;
    struct WebContents *webContents_;
    struct unique_ptr<ReauthDialogDelegate, std::__1::default_delete<ReauthDialogDelegate>> webContentsDelegate_;
    struct unique_ptr<ConstrainedWindowMac, std::__1::default_delete<ConstrainedWindowMac>> constrained_window_;
    struct unique_ptr<content::WebContents, std::__1::default_delete<content::WebContents>> reauthWebContents_;
}

- (id).cxx_construct;
- (void).cxx_destruct;
- (void)dealloc;
- (void)close;
- (void)closeButtonClicked:(id)arg1;
- (void)show;
- (id)initWithProfile:(struct Profile *)arg1 email:(basic_string_805fe43b)arg2 webContents:(struct WebContents *)arg3;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

