//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Jun  3 2014 10:55:11).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSViewController.h"

@interface SadTabController : NSViewController
{
    struct WebContents *webContents_;
    struct scoped_nsobject<SadTabView> sadTabView_;
}

- (id).cxx_construct;
- (void).cxx_destruct;
- (void)openLearnMoreAboutCrashLink:(id)arg1;
- (void)reloadPage:(id)arg1;
- (struct WebContents *)webContents;
- (void)loadView;
- (void)dealloc;
- (id)initWithWebContents:(struct WebContents *)arg1;

@end

