//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Jun  3 2014 10:55:11).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

@class TabController;

@protocol TabControllerTarget
- (id <TabDraggingEventTarget>)dragController;
- (struct SimpleMenuModel *)contextMenuModelForController:(TabController *)arg1 menuDelegate:(struct Delegate *)arg2;
- (BOOL)isCommandEnabled:(int)arg1 forController:(TabController *)arg2;
- (void)commandDispatch:(int)arg1 forController:(TabController *)arg2;
- (void)closeTab:(id)arg1;
- (void)selectTab:(id)arg1;
@end

