//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Jun  3 2014 10:55:11).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSWindowController.h"

#import "NSWindowDelegate.h"

@class FastResizeView, NSString, NSView, NSWindow, TabStripView;

@interface TabWindowController : NSWindowController <NSWindowDelegate>
{
    struct scoped_nsobject<FastResizeView> tabContentArea_;
    struct scoped_nsobject<NSView> tabStripBackgroundView_;
    struct scoped_nsobject<TabStripView> tabStripView_;
    struct scoped_nsobject<NSView> chromeContentView_;
    NSWindow *overlayWindow_;
    NSView *originalContentView_;
    struct scoped_nsobject<FocusTracker> focusBeforeOverlay_;
    BOOL closeDeferred_;
}

- (id).cxx_construct;
- (void).cxx_destruct;
- (void)layoutSubviews;
- (void)insertTabStripBackgroundViewIntoWindow:(id)arg1 titleBar:(BOOL)arg2;
- (void)deferPerformClose;
- (BOOL)isTabDraggable:(id)arg1;
- (BOOL)hasTabStrip;
- (id)activeTabTitle;
- (double)menubarOffset;
- (BOOL)hasLiveTabs;
- (long long)numberOfTabs;
- (void)detachTabView:(id)arg1;
- (void)showNewTabButton:(BOOL)arg1;
- (BOOL)isTabFullyVisible:(id)arg1;
- (BOOL)windowMovementAllowed;
- (BOOL)tabTearingAllowed;
- (BOOL)tabDraggingAllowed;
- (BOOL)isDragSessionActive;
- (void)removePlaceholder;
- (void)insertPlaceholderForTab:(id)arg1 frame:(struct CGRect)arg2;
- (void)detachedWindowEnterFullscreenIfNeeded:(id)arg1;
- (id)detachTabsToNewWindow:(id)arg1 draggedTab:(id)arg2;
- (void)layoutTabs;
- (id)activeTabView;
- (id)tabViews;
- (void)moveTabViews:(id)arg1 fromController:(id)arg2;
- (BOOL)canReceiveFrom:(id)arg1;
- (BOOL)shouldConstrainFrameRect;
- (id)overlayWindow;
- (void)setUseOverlay:(BOOL)arg1;
- (void)showOverlay;
- (void)removeOverlay;
@property(readonly, nonatomic) NSView *chromeContentView;
@property(readonly, nonatomic) FastResizeView *tabContentArea;
@property(readonly, nonatomic) TabStripView *tabStripView;
@property(readonly, nonatomic) NSView *tabStripBackgroundView;
- (id)initTabWindowControllerWithTabStrip:(BOOL)arg1 titleBar:(BOOL)arg2;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

