//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Jun  3 2014 10:55:11).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import <Google Chrome Framework/PendingPasswordViewController.h>

#import "NSTextViewDelegate.h"

@class NSButton, NSString;

@interface UpdatePendingPasswordViewController : PendingPasswordViewController <NSTextViewDelegate>
{
    scoped_nsobject_6cadfeaf updateButton_;
    scoped_nsobject_6cadfeaf nopeButton_;
    struct scoped_nsobject<PasswordsListViewController> passwordItem_;
    struct scoped_nsobject<CredentialsSelectionView> passwordWithUsernameSelectionItem_;
}

- (id).cxx_construct;
- (void).cxx_destruct;
- (id)createButtonsAndAddThemToView:(id)arg1;
- (id)createPasswordView;
- (void)onNopeClicked:(id)arg1;
- (void)onUpdateClicked:(id)arg1;
- (id)defaultButton;
@property(readonly) NSButton *noButton;
@property(readonly) NSButton *updateButton;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

