//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Jun  3 2014 10:55:11).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

@class NSMenu, NSSearchField, NSSet, TBrowserContainerController;

@protocol BrowserContainerSearching
- (void)toolbarUpdateForSplitterChange;
- (NSMenu *)toolbarHistorySearchTemplate;
- (_Bool)toolbarMakeSearchFieldFirstResponder;
- (NSSearchField *)toolbarSearchField;
- (_Bool)toolbarSearchFieldIsVisible;
- (NSSet *)containerQuerySearchUTIs:(TBrowserContainerController *)arg1;
@end

