//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Jun  3 2014 10:55:11).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "TDrawRectView.h"

@class NSLayoutConstraint;

@interface TAirDropInfoView : TDrawRectView
{
    struct TNSRef<NSImage *> _infoViewImage;
    struct TKeyValueBinder _ciifamBinder;
    struct TNotificationCenterObserver _wdcbpnObserver;
    double _superviewHeightCache;
    double _initialBottomConstraintConstantCache;
    NSLayoutConstraint *_bottomConstraint;
    _Bool _cachedImageIsForArcMode;
}

@property(nonatomic) _Bool cachedImageIsForArcMode; // @synthesize cachedImageIsForArcMode=_cachedImageIsForArcMode;
- (id).cxx_construct;
- (void).cxx_destruct;
- (void)windowBackingChanged:(id)arg1;
- (void)viewWillMoveToWindow:(id)arg1;
- (void)viewWillMoveToSuperview:(id)arg1;
- (id)infoViewImage;
- (void)updateInfoViewImage;
- (void)invalidateInfoViewImage;
- (void)layout;
- (void)resizeWithOldSuperviewSize:(struct CGSize)arg1;
- (void)setFrameSize:(struct CGSize)arg1;
- (void)drawRect:(struct CGRect)arg1;
- (id)iconViewController;
- (void)viewDidMoveToWindow;
- (void)setUpBindings;
- (void)dealloc;
- (void)awakeFromNib;
- (void)initCommon;

@end

