//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Jun  3 2014 10:55:11).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@interface TICloudAccountManager : NSObject
{
    struct TriStateBool fUserSharingDocuments;
    struct TriStateBool fUserHasDeclinedUpgrade;
    struct TriStateBool fFirstSyncComplete;
    struct TriStateBool fIsOverQuota;
    int _iCloudNotificationToken;
}

+ (_Bool)accountIsOverQuota;
+ (_Bool)showICloudDriveContent;
+ (_Bool)firstSyncCompleted;
+ (_Bool)userHasDeclinedUpgrade;
+ (_Bool)userIsSynchingDocuments;
+ (id)singleton;
+ (void)postOverQuotaChange;
+ (void)postStatusChange;
- (id).cxx_construct;
- (_Bool)isOverQuota;
- (_Bool)firstSyncHasCompleted;
- (_Bool)hasDeclinedUpgrade;
- (_Bool)isSynchingDocuments;
- (_Bool)computeLoginState;
- (_Bool)computeIsOverQuota;
- (void)invalidate;
- (id)_init;
- (id)init;

@end

