//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Jun  3 2014 10:55:11).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "TButton.h"

@interface TMouseOverButton : TButton
{
    _Bool _trackingMouseDown;
    int _mouseState;
    function_1bd45014 _imageForStateGetter;
    struct TNSRef<NSTrackingArea *> _trackingArea;
    struct TNotificationCenterObserver _windowDidResignKeyObserver;
}

@property(nonatomic) int mouseState; // @synthesize mouseState=_mouseState;
- (id).cxx_construct;
- (void).cxx_destruct;
- (void)windowDidResignKey;
- (void)setHidden:(BOOL)arg1;
- (void)mouseExited:(id)arg1;
- (void)mouseEntered:(id)arg1;
- (void)mouseUp:(id)arg1;
- (void)mouseDown:(id)arg1;
- (void)setImageForStateGetter:(const function_1bd45014 *)arg1;
- (void)updateImage;
- (void)updateTrackingAreas;
- (void)initTracking;
- (void)aboutToTearDown;
- (void)viewWillMoveToWindow:(id)arg1;
- (void)initCommon;

@end

