//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Jun  3 2014 10:55:11).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "TScriptableWindowController.h"

#import "NSWindowDelegate.h"
#import "TValidatorClientProtocol.h"

@class NSStackView, NSString;

@interface TProgressWindowController : TScriptableWindowController <NSWindowDelegate, TValidatorClientProtocol>
{
    int _kind;
    NSStackView *_stackView;
    struct TNSRef<NSArray *> _scrollViewHeightConstraints;
    long long _validatorID;
    struct TNotificationCenterObserver _stackViewFrameChangedObserver;
    unsigned long long _numProgressViewsCache;
    double _stackViewHeightCache;
}

+ (id)controllerForWindowKind:(int)arg1;
@property(readonly, nonatomic) long long validatorID; // @synthesize validatorID=_validatorID;
- (id).cxx_construct;
- (void).cxx_destruct;
- (void)windowWillClose:(id)arg1;
- (void)removeProgressView:(id)arg1;
- (void)addProgressView:(id)arg1;
- (void)updateHeightConstraints;
- (double)calculateStackViewYOffset;
- (void)updateSeparators;
- (void)windowDidLoad;
- (void)dealloc;
- (id)initWithWindowKind:(int)arg1;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

