//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Jun  3 2014 10:55:11).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "TViewController.h"

@interface TSearchScopeSliceController : TViewController
{
}

- (void)setScopePlusMinusButtonTitle:(_Bool)arg1;
- (void)setScopePlusMinusButtonEnabled:(_Bool)arg1;
- (void)setSaveButtonEnabled:(_Bool)arg1;
- (id)currentScopeString;
- (unsigned long long)scopeSelection;
- (void)setScopeSelection:(unsigned long long)arg1;
- (void)setButtonTitles:(const struct TStringVector *)arg1 andToolTips:(const struct TStringVector *)arg2;
@property id <TSearchScopeSliceControllerDelegate> scopeSliceDelegate; // @dynamic scopeSliceDelegate;
- (id)scopeSlice;
- (id)nibName;

@end

