//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Jun 14 2016 15:02:16).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <AppKit/NSImage.h>

@interface NSImage (AppKit_SiriUIFrameworkAdditions)
+ (id)siriui_semiTransparentChevronImageAndAllowNaturalLayout:(BOOL)arg1;
+ (id)siriui_semiTransparentChevronImage;
- (id)siriui_pngFileRepresentation;
- (id)siriui_bitmapImageRepresentation;
- (id)siriui_imageByCroppingToRect:(struct CGRect)arg1;
- (BOOL)siriui_saveToURL:(id)arg1 error:(id *)arg2;
@end

