//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Jun 14 2016 15:02:16).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <AppKit/NSViewController.h>

#import <SiriUI/SiriUIViewController-Protocol.h>

@class AceObject, NSString;
@protocol SiriUIAceObjectViewControllerDelegate;

@interface SiriUIAceObjectViewController : NSViewController <SiriUIViewController>
{
    BOOL _virgin;
    AceObject *_aceObject;
    id <SiriUIAceObjectViewControllerDelegate> _delegate;
}

@property(nonatomic) __weak id <SiriUIAceObjectViewControllerDelegate> delegate; // @synthesize delegate=_delegate;
@property(readonly, nonatomic, getter=isVirgin) BOOL virgin; // @synthesize virgin=_virgin;
@property(retain, nonatomic) AceObject *aceObject; // @synthesize aceObject=_aceObject;
- (void).cxx_destruct;
- (void)wasAddedToTranscript;
- (void)siriDidDeactivate;
- (void)siriWillActivateFromSource:(long long)arg1;
- (double)desiredHeight;
- (BOOL)removedAfterDialogProgresses;
- (id)initWithNibName:(id)arg1 bundle:(id)arg2;
- (BOOL)_isUserUtterance;
- (void)_aceObjectViewControllerWillBeRemoved;
- (double)_insertionAnimatedZPosition;
- (long long)_replacementAnimation;
- (long long)_insertionAnimation;
- (void)_setVirgin:(BOOL)arg1;
- (id)_privateDelegate;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

