//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Jun  3 2014 10:55:11).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NCWidget.h"

@class NCWindowPluginLayerView, NSObject<OS_xpc_object>;

@interface NCRemoteWidget : NCWidget
{
    NSObject<OS_xpc_object> *_connection;
    NCWindowPluginLayerView *_view;
    double _height;
    int _state;
}

@property int state; // @synthesize state=_state;
- (double)height;
- (id)view;
- (void).cxx_destruct;
- (void)_sendPositionChange:(struct CGPoint)arg1;
- (void)_requestWindowInfo;
- (void)_connect;
- (void)updateOrigin:(id)arg1;
- (void)widgetRemovedFromView;
- (void)widgetInsertedIntoView;
- (id)_containingCellView;
- (id)initWithID:(id)arg1 andWidth:(double)arg2;

@end

