//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Jun  3 2014 10:55:11).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSView.h"

@class CAGradientLayer;

@interface NCTexturedView : NSView
{
    CAGradientLayer *_backgroundGradient;
    CAGradientLayer *_sideShadow;
    _Bool _textureVisible;
}

@property(nonatomic) _Bool textureVisible; // @synthesize textureVisible=_textureVisible;
- (void).cxx_destruct;
- (void)updateGradientFrameRect:(struct CGRect)arg1;
- (void)awakeFromNib;

@end

