//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Jun 14 2016 15:02:16).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <AppKit/NSViewController.h>

@class NSButton, NSImageView, NSLayoutConstraint, NSTextField;

__attribute__((visibility("hidden")))
@interface NCDNDViewController : NSViewController
{
    NSLayoutConstraint *_reasonTopConstraint;
    NSLayoutConstraint *_reasonHeightConstraint;
    NSTextField *_reasonTextField;
    NSButton *_dndButton;
    NSImageView *_dndImage;
}

@property(nonatomic) NSImageView *dndImage; // @synthesize dndImage=_dndImage;
@property(nonatomic) NSButton *dndButton; // @synthesize dndButton=_dndButton;
@property(nonatomic) NSTextField *reasonTextField; // @synthesize reasonTextField=_reasonTextField;
@property(nonatomic) NSLayoutConstraint *reasonHeightConstraint; // @synthesize reasonHeightConstraint=_reasonHeightConstraint;
@property(retain, nonatomic) NSLayoutConstraint *reasonTopConstraint; // @synthesize reasonTopConstraint=_reasonTopConstraint;
- (void).cxx_destruct;
- (void)dndButtonPressed:(id)arg1;
- (void)_updateDNDButton;
- (void)_updateDNDReason;
- (void)viewDidLoad;

@end

