//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Jun 14 2016 15:02:16).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "NSObject-Protocol.h"

@class NCTCCAlertViewController, NCTCCProvider, NSString;

@protocol NCTCCProviderDelegate <NSObject>
- (void)tccProvider:(NCTCCProvider *)arg1 dismissAlert:(NCTCCAlertViewController *)arg2;
- (_Bool)tccProvider:(NCTCCProvider *)arg1 presentAlert:(NCTCCAlertViewController *)arg2 forBundleID:(NSString *)arg3 andProcessID:(int)arg4;
- (void)tccProviderConnectionDidClose:(NCTCCProvider *)arg1;
@end

