//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Jun 14 2016 15:02:16).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "NCTodayItemViewController.h"

@class NCDNDViewController, NSLayoutConstraint;

__attribute__((visibility("hidden")))
@interface NCTodayDNDViewController : NCTodayItemViewController
{
    NSLayoutConstraint *_heightConstraint;
    NCDNDViewController *_dndViewController;
}

@property(readonly, nonatomic) NCDNDViewController *dndViewController; // @synthesize dndViewController=_dndViewController;
- (void).cxx_destruct;
- (void)loadView;

@end

