//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Jun 14 2016 15:02:16).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "NCTodayItemViewControllerDelegate-Protocol.h"

@class NCTodayHeaderViewController;

@protocol NCTodayHeaderDelegate <NCTodayItemViewControllerDelegate>
- (void)todayHeaderEditPressed:(NCTodayHeaderViewController *)arg1;
- (void)todayHeaderDeletePressed:(NCTodayHeaderViewController *)arg1;
@end

