//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Jun 14 2016 15:02:16).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <AppKit/NSViewController.h>

@class NCCardViewController, NCDNDViewController;

__attribute__((visibility("hidden")))
@interface NotificationsTableDNDRow : NSViewController
{
    // Error parsing type: , name: cardCtrl
    // Error parsing type: , name: dndCtrl
}

- (CDUnknownBlockType).cxx_destruct;
- (id)initWithNibName:(id)arg1 bundle:(id)arg2;
- (id)initWithCoder:(id)arg1;
- (void)loadView;
- (id)init;
@property(nonatomic, readonly) NCDNDViewController *dndCtrl; // @synthesize dndCtrl;
@property(nonatomic, readonly) NCCardViewController *cardCtrl; // @synthesize cardCtrl;

@end

