//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Jun  3 2014 10:55:11).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

#import "NSApplicationDelegate.h"
#import "NSUserNotificationCenterDelegate.h"
#import "SiriNCClientProtocol.h"

@class NSString, NSXPCConnection;

@interface SiriUXAppDelegate : NSObject <SiriNCClientProtocol, NSUserNotificationCenterDelegate, NSApplicationDelegate>
{
    BOOL _screenLocked;
    BOOL _uiIsPresented;
    BOOL _siriIsVisible;
    NSXPCConnection *_ncServiceConnection;
    NSXPCConnection *_ncConnection;
}

+ (id)_radarURL;
+ (id)_nameForActionType:(long long)arg1;
+ (BOOL)_shouldLogInvocationEvents;
@property(nonatomic) BOOL siriIsVisible; // @synthesize siriIsVisible=_siriIsVisible;
@property(nonatomic) BOOL uiIsPresented; // @synthesize uiIsPresented=_uiIsPresented;
@property(nonatomic) BOOL screenLocked; // @synthesize screenLocked=_screenLocked;
@property(retain, nonatomic) NSXPCConnection *ncConnection; // @synthesize ncConnection=_ncConnection;
@property(retain) NSXPCConnection *ncServiceConnection; // @synthesize ncServiceConnection=_ncServiceConnection;
- (void).cxx_destruct;
- (BOOL)userNotificationCenter:(id)arg1 shouldPresentNotification:(id)arg2;
- (void)userNotificationCenter:(id)arg1 didActivateNotification:(id)arg2;
- (void)serviceUIWasDismissed;
- (void)serviceUIWillAppear;
- (void)addViewsCommandStashed:(id)arg1 forCardWithTitle:(id)arg2 imagePath:(id)arg3;
- (void)radarCreated:(id)arg1;
- (void)showBugTemplateWithValues:(id)arg1 completion:(CDUnknownBlockType)arg2;
- (void)handleNCServiceDisconnect;
- (void)setupNCServiceConnection:(id)arg1;
- (void)connectToNCService;
- (void)_disableSiri;
- (void)_enableSiri;
- (void)_showEnableSiriAlert;
- (void)_invokeService:(long long)arg1 fromEventSource:(long long)arg2 completion:(CDUnknownBlockType)arg3;
- (void)_handleInputMethodNotification:(id)arg1;
- (long long)_siriEventSourceFromCurrentAppleEvent;
- (long long)_siriEventSourceForNotification:(id)arg1;
- (long long)_siriActionFromCurrentAppleEvent;
- (long long)_siriActionForNotification:(id)arg1;
- (void)_siriDidDisappear:(id)arg1;
- (void)_siriDidAppear:(id)arg1;
- (void)_screenIsUnlocked:(id)arg1;
- (void)_screenIsLocked:(id)arg1;
- (BOOL)applicationShouldHandleReopen:(id)arg1 hasVisibleWindows:(BOOL)arg2;
- (void)_setupSiri;
- (void)applicationDidFinishLaunching:(id)arg1;
- (void)handleDismissal:(id)arg1;
- (void)handleLongPress:(id)arg1;
- (void)handleShortPress:(id)arg1 withReplyEvent:(id)arg2;
- (void)applicationWillFinishLaunching:(id)arg1;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

