//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Jun 14 2016 15:02:16).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <objc/NSObject.h>

@class NCCARemoteViewController, NSString, NSUUID, NSView, NSXPCConnection;

__attribute__((visibility("hidden")))
@interface NCCARemoteSession : NSObject
{
    NCCARemoteViewController *_remoteViewController;
    _Bool _dark;
    _Bool _dontAnimate;
    _Bool _ignoresDND;
    _Bool _allowsSwipeDismiss;
    _Bool _invalidated;
    NSUUID *_uuid;
    NSString *_appIdentifier;
    NSString *_serviceIdentifier;
    unsigned long long _order;
    CDUnknownBlockType _completion;
    id _context;
    NSXPCConnection *_connection;
}

@property(retain) NSXPCConnection *connection; // @synthesize connection=_connection;
@property __weak id context; // @synthesize context=_context;
@property(copy) CDUnknownBlockType completion; // @synthesize completion=_completion;
@property _Bool invalidated; // @synthesize invalidated=_invalidated;
@property unsigned long long order; // @synthesize order=_order;
@property _Bool allowsSwipeDismiss; // @synthesize allowsSwipeDismiss=_allowsSwipeDismiss;
@property(nonatomic) _Bool ignoresDND; // @synthesize ignoresDND=_ignoresDND;
@property _Bool dontAnimate; // @synthesize dontAnimate=_dontAnimate;
@property _Bool dark; // @synthesize dark=_dark;
@property(readonly) NSString *serviceIdentifier; // @synthesize serviceIdentifier=_serviceIdentifier;
@property(readonly) NSString *appIdentifier; // @synthesize appIdentifier=_appIdentifier;
@property(readonly) NSUUID *uuid; // @synthesize uuid=_uuid;
- (void).cxx_destruct;
- (void)dismissed;
- (void)invalidate;
@property(readonly) NSView *view;
- (id)initWithUUID:(id)arg1 serviceIdentifier:(id)arg2 representingApp:(id)arg3 endPoint:(id)arg4;

@end

