//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Jun 14 2016 15:02:16).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <AppKit/NSWindowController.h>

@class NSString;
@protocol _TtP21NotificationCenterApp21NCDebugWindowDelegate_;

__attribute__((visibility("hidden")))
@interface NCDebugWindow : NSWindowController
{
    // Error parsing type: , name: delegate
    // Error parsing type: , name: dndModeEnabled
    // Error parsing type: , name: screenLockMode
}

- (CDUnknownBlockType).cxx_destruct;
- (id)initWithCoder:(id)arg1;
- (id)initWithWindow:(id)arg1;
@property(nonatomic, readonly) NSString *windowNibName;
@property(nonatomic) unsigned long long screenLockMode; // @synthesize screenLockMode;
@property(nonatomic) BOOL dndModeEnabled; // @synthesize dndModeEnabled;
@property(nonatomic) __weak id <_TtP21NotificationCenterApp21NCDebugWindowDelegate_> delegate; // @synthesize delegate;

@end

