//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Jun 14 2016 15:02:16).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <swiftCore/SwiftObject.h>

__attribute__((visibility("hidden")))
@interface Queue : SwiftObject
{
    // Error parsing type: , name: _q
    // Error parsing type: , name: _timers
}

@end

