//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Jun  3 2014 10:55:11).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSPanel.h"

@class NCBannerWindowController;

@interface _NCBannersWindow : NSPanel
{
    NCBannerWindowController *_owner;
}

@property(nonatomic) __weak NCBannerWindowController *owner; // @synthesize owner=_owner;
- (void).cxx_destruct;
- (void)_adjustWindowToScreen;
- (BOOL)view:(id)arg1 acceptsFirstMouseEvent:(id)arg2 initialKeyWindow:(id)arg3;
- (BOOL)_hasActiveControls;
- (void)recalculateKeyViewLoop;
- (BOOL)accessibilityIsIgnored;
- (void)keyDown:(id)arg1;
- (BOOL)canBecomeKeyWindow;
- (BOOL)_shouldAutoFlattenLayerTree;
- (id)initWithFrame:(struct CGRect)arg1 spaces:(id)arg2;

@end

