//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Jun  3 2014 10:55:11).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSWindowController.h"

@interface NCDebugWindow : NSWindowController
{
    _Bool _dndModeEnabled;
    id <NCDebugWindowDelegate> _delegate;
    unsigned long long _screenLockMode;
}

@property(nonatomic) unsigned long long screenLockMode; // @synthesize screenLockMode=_screenLockMode;
@property(nonatomic) _Bool dndModeEnabled; // @synthesize dndModeEnabled=_dndModeEnabled;
@property(nonatomic) __weak id <NCDebugWindowDelegate> delegate; // @synthesize delegate=_delegate;
- (void).cxx_destruct;
- (void)windowDidLoad;
- (id)init;

@end

