//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Jun  3 2014 10:55:11).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NCBannerModel.h"

@class NCCARemoteSession, NCRemoteNotificationWindow;

@interface NCRemoteAlertModel : NCBannerModel
{
    NCRemoteNotificationWindow *_bannerWindow;
    unsigned long long _sortBehavior;
    NCCARemoteSession *_remoteSession;
}

@property(readonly) NCCARemoteSession *remoteSession; // @synthesize remoteSession=_remoteSession;
@property(nonatomic) unsigned long long sortBehavior; // @synthesize sortBehavior=_sortBehavior;
- (void).cxx_destruct;
- (id)remoteAlert;
- (_Bool)canInteractAtLockscreen;
- (_Bool)canColeasce;
- (_Bool)isRemoteAlert;
@property(readonly, nonatomic) NCRemoteNotificationWindow *bannerWindowCreateIfNecessary;
- (unsigned long long)defaultBehavior;
- (void)clearBannerWindow;
@property(readonly, nonatomic) NCRemoteNotificationWindow *bannerWindow;
- (void)dealloc;
- (id)initWithRemoteSession:(id)arg1 app:(id)arg2 delegate:(id)arg3;

@end

