//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Jun  3 2014 10:55:11).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NCRemoteViewHostViewControllerDelegate.h"

@class NCWidgetHostViewController;

@protocol NCWidgetHostViewControllerDelegate <NCRemoteViewHostViewControllerDelegate>
- (void)widgetViewController:(NCWidgetHostViewController *)arg1 widgetModeChanged:(unsigned long long)arg2;
- (void)widgetViewController:(NCWidgetHostViewController *)arg1 hasContentChanged:(_Bool)arg2;
@end

