//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Jun  3 2014 10:55:11).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@interface AppShimMenuController : NSObject
{
    basic_string_805fe43b appId_;
    struct scoped_nsobject<DoppelgangerMenuItem> aboutDoppelganger_;
    struct scoped_nsobject<DoppelgangerMenuItem> hideDoppelganger_;
    struct scoped_nsobject<DoppelgangerMenuItem> quitDoppelganger_;
    struct scoped_nsobject<DoppelgangerMenuItem> newDoppelganger_;
    struct scoped_nsobject<DoppelgangerMenuItem> openDoppelganger_;
    struct scoped_nsobject<DoppelgangerMenuItem> closeWindowDoppelganger_;
    struct scoped_nsobject<DoppelgangerMenuItem> allToFrontDoppelganger_;
    struct scoped_nsobject<NSMenuItem> appMenuItem_;
    struct scoped_nsobject<NSMenuItem> fileMenuItem_;
    struct scoped_nsobject<NSMenuItem> editMenuItem_;
    struct scoped_nsobject<NSMenuItem> windowMenuItem_;
    struct scoped_nsobject<NSMenuItem> viewMenuItem_;
    struct scoped_nsobject<NSMenuItem> historyMenuItem_;
}

- (id).cxx_construct;
- (void).cxx_destruct;
- (void)focusCurrentPlatformApp;
- (void)hideCurrentPlatformApp;
- (void)quitCurrentPlatformApp;
- (void)removeMenuItems;
- (void)addMenuItems:(const struct Extension *)arg1;
- (void)chromeBecameMain;
- (void)appBecameMain:(const struct Extension *)arg1;
- (void)windowMainStatusChanged:(id)arg1;
- (void)registerEventHandlers;
- (void)buildAppMenuItems;
- (void)dealloc;
- (id)init;

@end

