//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Jun  3 2014 10:55:11).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import <Google Chrome Framework/BaseBubbleController.h>

@interface AutofillBubbleController : BaseBubbleController
{
    scoped_nsobject_0ef9b51e label_;
    struct CGSize inset_;
}

- (id).cxx_construct;
- (void).cxx_destruct;
- (void)updateMessage:(id)arg1 display:(BOOL)arg2;
- (void)setMessage:(id)arg1;
- (double)maxWidth;
- (id)initWithParentWindow:(id)arg1 message:(id)arg2 inset:(struct CGSize)arg3 arrowLocation:(int)arg4;
- (id)initWithParentWindow:(id)arg1 message:(id)arg2;

@end

