//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Jun  3 2014 10:55:11).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import <Google Chrome Framework/AvatarBaseController.h>

@interface AvatarButtonController : AvatarBaseController
{
    BOOL isThemedWindow_;
    BOOL hasError_;
}

- (void)updateErrorStatus:(BOOL)arg1;
- (void)updateAvatarButtonAndLayoutParent:(BOOL)arg1;
- (void)themeDidChangeNotification:(id)arg1;
- (void)dealloc;
- (id)initWithBrowser:(struct Browser *)arg1;

@end

