//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Jun  3 2014 10:55:11).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import <Google Chrome Framework/BaseBubbleController.h>

@interface AvatarMenuBubbleController : BaseBubbleController
{
    struct unique_ptr<AvatarMenu, std::__1::default_delete<AvatarMenu>> menu_;
    scoped_nsobject_9420f295 items_;
    BOOL expanded_;
}

- (id).cxx_construct;
- (void).cxx_destruct;
- (void)highlightItem:(id)arg1;
- (void)highlightNextItemByDelta:(long long)arg1;
- (void)insertNewline:(id)arg1;
- (void)moveUp:(id)arg1;
- (void)moveDown:(id)arg1;
- (void)keyDown:(id)arg1;
- (id)items;
- (id)configureSwitchUserButton:(double)arg1 updateWidthAdjust:(double *)arg2;
- (id)configureNewUserButton:(double)arg1 updateWidthAdjust:(double *)arg2;
- (id)configureSupervisedUserInformation:(double)arg1;
- (void)performLayout;
- (void)initSupervisedUserContents;
- (void)initMenuContents;
- (void)setWindowFrame:(double)arg1 widthAdjust:(double)arg2;
- (id)initAvatarItem:(int)arg1 updateWidthAdjust:(double *)arg2 setYOffset:(double)arg3;
- (id)initWithMenu:(struct AvatarMenu *)arg1 parentWindow:(id)arg2 anchoredAt:(struct CGPoint)arg3;
- (void)switchProfile:(id)arg1;
- (void)editProfile:(id)arg1;
- (void)switchToProfile:(id)arg1;
- (void)newProfile:(id)arg1;
- (id)initWithBrowser:(struct Browser *)arg1 anchoredAt:(struct CGPoint)arg2;

@end

