//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Jun  3 2014 10:55:11).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import <Google Chrome Framework/TranslateInfoBarControllerBase.h>

@interface BeforeTranslateInfobarController : TranslateInfoBarControllerBase
{
    scoped_nsobject_6cadfeaf alwaysTranslateButton_;
    scoped_nsobject_6cadfeaf neverTranslateButton_;
}

- (id).cxx_construct;
- (void).cxx_destruct;
- (_Bool)verifyLayout;
- (void)alwaysTranslate:(id)arg1;
- (void)neverTranslate:(id)arg1;
- (id)visibleControls;
- (void)loadLabelText;
- (void)layout;
- (void)initializeExtraControls;
- (id)initWithInfoBar:(struct InfoBarCocoa *)arg1;
- (void)dealloc;
- (id)neverTranslateButton;
- (id)alwaysTranslateButton;

@end

