//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Jun  3 2014 10:55:11).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import <Google Chrome Framework/BookmarkNodeAppleScript.h>

@interface BookmarkFolderAppleScript : BookmarkNodeAppleScript
{
}

- (int)calculatePositionOfBookmarkItemAt:(int)arg1;
- (int)calculatePositionOfBookmarkFolderAt:(int)arg1;
- (void)removeFromBookmarkItemsAtIndex:(int)arg1;
- (void)insertInBookmarkItems:(id)arg1 atIndex:(int)arg2;
- (void)insertInBookmarkItems:(id)arg1;
- (id)bookmarkItems;
- (void)removeFromBookmarkFoldersAtIndex:(int)arg1;
- (void)insertInBookmarkFolders:(id)arg1 atIndex:(int)arg2;
- (void)insertInBookmarkFolders:(id)arg1;
- (id)bookmarkFolders;

@end

