//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Jun  3 2014 10:55:11).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSWindowController.h"

#import "NSOutlineViewDelegate.h"

@class NSArray, NSButton, NSOutlineView, NSString, NSTreeController, NSWindow;

@interface BookmarkEditorBaseController : NSWindowController <NSOutlineViewDelegate>
{
    NSButton *newFolderButton_;
    NSButton *okButton_;
    NSTreeController *folderTreeController_;
    NSOutlineView *folderTreeView_;
    NSWindow *parentWindow_;
    struct Profile *profile_;
    const struct BookmarkNode *parentNode_;
    struct GURL url_;
    basic_string_61b65554 title_;
    int configuration_;
    NSString *initialName_;
    NSString *displayName_;
    BOOL creatingNewFolders_;
    struct scoped_nsobject<NSArray> folderTreeArray_;
    struct scoped_nsobject<NSArray> tableSelectionPaths_;
    struct unique_ptr<BookmarkEditorBaseControllerBridge, std::__1::default_delete<BookmarkEditorBaseControllerBridge>> observer_;
}

@property(copy, nonatomic) NSString *displayName; // @synthesize displayName=displayName_;
@property(copy, nonatomic) NSString *initialName; // @synthesize initialName=initialName_;
- (id).cxx_construct;
- (void).cxx_destruct;
- (BOOL)outlineView:(id)arg1 shouldEditTableColumn:(id)arg2 item:(id)arg3;
- (void)selectTestNodeInBrowser:(const struct BookmarkNode *)arg1;
- (BOOL)okButtonEnabled;
- (void)createNewFolders;
- (void)newFolder:(id)arg1;
- (void)createNewFoldersForFolder:(id)arg1 selectedFolderInfo:(id)arg2;
- (void)nodeRemoved:(const struct BookmarkNode *)arg1 fromParent:(const struct BookmarkNode *)arg2;
- (void)modelChangedPreserveSelection:(BOOL)arg1;
- (void)buildFolderTree;
- (id)addChildFoldersFromNode:(const struct BookmarkNode *)arg1;
- (id)selectionPathForNode:(const struct BookmarkNode *)arg1;
- (void)selectNodeInBrowser:(const struct BookmarkNode *)arg1;
@property(copy, nonatomic) NSArray *tableSelectionPaths;
- (void)setTableSelectionPath:(id)arg1;
@property(readonly, retain, nonatomic) NSArray *folderTreeArray;
- (void)getExpandedNodes:(set_aabfe767 *)arg1 folder:(id)arg2 path:(vector_eb9481f9 *)arg3 root:(id)arg4;
- (set_aabfe767)getExpandedNodes;
- (void)expandNodes:(const set_aabfe767 *)arg1;
- (const struct BookmarkNode *)selectedNode;
- (id)selectedFolder;
- (id)selectedIndexPath;
- (id)folderForIndexPath:(id)arg1;
- (const basic_string_61b65554 *)title;
- (const struct GURL *)url;
- (const struct BookmarkNode *)parentNode;
- (struct Profile *)profile;
- (struct BookmarkModel *)bookmarkModel;
- (void)windowWillClose:(id)arg1;
- (void)didEndSheet:(id)arg1 returnCode:(int)arg2 contextInfo:(void *)arg3;
- (void)cancel:(id)arg1;
- (void)ok:(id)arg1;
- (BOOL)okEnabled;
- (void)runAsModalSheet;
- (void)windowDidLoad;
- (void)awakeFromNib;
- (void)dealloc;
- (id)initWithParentWindow:(id)arg1 nibName:(id)arg2 profile:(struct Profile *)arg3 parent:(const struct BookmarkNode *)arg4 url:(const struct GURL *)arg5 title:(const basic_string_61b65554 *)arg6 configuration:(int)arg7;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

