//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Jun  3 2014 10:55:11).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@interface BrowserWindowUtils : NSObject
{
}

+ (void)activateWindowForController:(id)arg1;
+ (struct CGPoint)themeImagePositionInTabStripCoords:(id)arg1 alignment:(int)arg2;
+ (struct CGPoint)themeImagePositionFor:(id)arg1 withTabStrip:(id)arg2 alignment:(int)arg3;
+ (id)scheduleReplaceOldTitle:(id)arg1 withNewTitle:(id)arg2 forWindow:(id)arg3;
+ (BOOL)handleKeyboardEvent:(id)arg1 inWindow:(id)arg2;
+ (int)getCommandId:(const struct NativeWebKeyboardEvent *)arg1;
+ (BOOL)isTextEditingEvent:(const struct NativeWebKeyboardEvent *)arg1;
+ (BOOL)shouldHandleKeyboardEvent:(const struct NativeWebKeyboardEvent *)arg1;

@end

