//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Jun  3 2014 10:55:11).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@interface BrowserWindowLayout : NSObject
{
    struct LayoutParameters parameters_;
    struct LayoutOutput output_;
    double fullscreenYOffset_;
    double maxY_;
}

- (double)fullscreenBackingBarHeight;
- (void)computeContentViewLayout;
- (void)computeTabStripLayout;
- (void)computeFullscreenYOffset;
- (void)setDownloadShelfHeight:(double)arg1;
- (void)setHasDownloadShelf:(BOOL)arg1;
- (void)setPageInfoBubblePointY:(double)arg1;
- (void)setInfoBarHeight:(double)arg1;
- (void)setBookmarkBarHeight:(double)arg1;
- (void)setPlaceBookmarkBarBelowInfoBar:(BOOL)arg1;
- (void)setBookmarkBarHidden:(BOOL)arg1;
- (void)setToolbarHeight:(double)arg1;
- (void)setHasLocationBar:(BOOL)arg1;
- (void)setHasToolbar:(BOOL)arg1;
- (void)setAvatarLineWidth:(double)arg1;
- (void)setAvatarSize:(struct CGSize)arg1;
- (void)setShouldUseNewAvatar:(BOOL)arg1;
- (void)setShouldShowAvatar:(BOOL)arg1;
- (void)setFullscreenButtonFrame:(struct CGRect)arg1;
- (void)setHasTabStrip:(BOOL)arg1;
- (void)setFullscreenToolbarFraction:(double)arg1;
- (void)setFullscreenMenubarOffset:(double)arg1;
- (void)setFullscreenSlidingStyle:(int)arg1;
- (void)setInAnyFullscreen:(BOOL)arg1;
- (void)setWindowSize:(struct CGSize)arg1;
- (void)setContentViewSize:(struct CGSize)arg1;
- (struct LayoutOutput)computeLayout;
- (id)init;
- (void)setOSYosemiteOrLater:(BOOL)arg1;

@end

