//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Jun  3 2014 10:55:11).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class NSArray, NSButton, NSString, NSView, NSWindow;

@interface ConstrainedWindowAlert : NSObject
{
    scoped_nsobject_0ef9b51e informativeTextField_;
    scoped_nsobject_0ef9b51e messageTextField_;
    scoped_nsobject_6cadfeaf linkView_;
    struct scoped_nsobject<NSView> accessoryView_;
    scoped_nsobject_9420f295 buttons_;
    scoped_nsobject_6cadfeaf closeButton_;
    struct scoped_nsobject<NSWindow> window_;
}

- (id).cxx_construct;
- (void).cxx_destruct;
- (id)linkView;
- (void)layoutCloseButtonWithWindowWidth:(double)arg1 windowHeight:(double)arg2;
- (double)layoutAccessoryViewAtYPos:(double)arg1;
- (double)layoutLinkAtYPos:(double)arg1 windowWidth:(double)arg2;
- (double)layoutTextField:(id)arg1 yPos:(double)arg2 windowWidth:(double)arg3;
- (void)layoutButtonsWithWindowWidth:(double)arg1;
- (void)layout;
- (void)addButtonWithTitle:(id)arg1 keyEquivalent:(id)arg2 target:(id)arg3 action:(SEL)arg4;
@property(readonly, nonatomic) NSWindow *window;
@property(readonly, nonatomic) NSButton *closeButton;
@property(readonly, nonatomic) NSArray *buttons;
@property(retain, nonatomic) NSView *accessoryView;
- (void)setLinkText:(id)arg1 target:(id)arg2 action:(SEL)arg3;
@property(copy, nonatomic) NSString *messageText;
@property(copy, nonatomic) NSString *informativeText;
- (id)init;

@end

