//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Jun  3 2014 10:55:11).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSTrackingArea.h"

@interface CrTrackingArea : NSTrackingArea
{
    struct scoped_nsobject<CrTrackingAreaOwnerProxy> ownerProxy_;
}

- (id).cxx_construct;
- (void).cxx_destruct;
- (void)windowWillClose:(id)arg1;
- (void)clearOwnerWhenWindowWillClose:(id)arg1;
- (void)clearOwner;
- (void)dealloc;
- (id)initWithRect:(struct CGRect)arg1 options:(unsigned long long)arg2 owner:(id)arg3 userInfo:(id)arg4;

@end

