//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Jun  3 2014 10:55:11).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import <Google Chrome Framework/BaseBubbleController.h>

@class NSTextField;

@interface FirstRunBubbleController : BaseBubbleController
{
    NSTextField *header_;
    struct Browser *browser_;
    struct Profile *profile_;
}

+ (id)showForView:(id)arg1 offset:(struct CGPoint)arg2 browser:(struct Browser *)arg3 profile:(struct Profile *)arg4;
- (void)onChange:(id)arg1;
- (void)closeIfNotKey;
- (void)close;
- (void)awakeFromNib;
- (id)initRelativeToView:(id)arg1 offset:(struct CGPoint)arg2 browser:(struct Browser *)arg3 profile:(struct Profile *)arg4;

@end

