//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Jun  3 2014 10:55:11).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSWindow.h"

@interface FullscreenLowPowerWindow : NSWindow
{
    struct scoped_nsobject<NSWindow> eventTargetWindow_;
}

- (id).cxx_construct;
- (void).cxx_destruct;
- (void)sendEvent:(id)arg1;
- (id)initWithEventTargetWindow:(id)arg1 withLayer:(id)arg2;

@end

