//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Jun  3 2014 10:55:11).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSProxy.h"

@interface GTMLightweightProxy : NSProxy
{
    id representedObject_;
}

- (BOOL)respondsToSelector:(SEL)arg1;
- (void)doesNotRecognizeSelector:(SEL)arg1;
- (id)methodSignatureForSelector:(SEL)arg1;
- (void)forwardInvocation:(id)arg1;
- (void)setRepresentedObject:(id)arg1;
- (id)representedObject;
- (void)dealloc;
- (id)init;
- (id)initWithRepresentedObject:(id)arg1;

@end

