//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Jun  3 2014 10:55:11).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import <Google Chrome Framework/BaseBubbleController.h>

#import "NSTextViewDelegate.h"

@class NSString;

@interface PermissionBubbleController : BaseBubbleController <NSTextViewDelegate>
{
    scoped_nsobject_9420f295 checkboxes_;
    struct Delegate *delegate_;
    struct Browser *browser_;
    struct unique_ptr<ui::SimpleMenuModel::Delegate, std::__1::default_delete<ui::SimpleMenuModel::Delegate>> menuDelegate_;
    struct PermissionBubbleCocoa *bridge_;
}

+ (void)alignCenterOf:(id)arg1 verticallyToCenterOf:(id)arg2;
+ (double)matchWidthsOf:(id)arg1 andOf:(id)arg2;
+ (_Bool)hasVisibleLocationBarForBrowser:(struct Browser *)arg1;
+ (struct CGPoint)getAnchorPointForBrowser:(struct Browser *)arg1;
- (id).cxx_construct;
- (void).cxx_destruct;
- (void)activateTabWithContents:(struct WebContents *)arg1 previousContents:(struct WebContents *)arg2 atIndex:(long long)arg3 reason:(int)arg4;
- (void)onClose:(id)arg1;
- (void)onBlock:(id)arg1;
- (void)onAllow:(id)arg1;
- (void)ok:(id)arg1;
- (id)closeButton;
- (id)blockButton;
- (id)buttonWithTitle:(id)arg1 action:(SEL)arg2;
- (id)menuForRequest:(struct PermissionBubbleRequest *)arg1 atIndex:(int)arg2 allow:(BOOL)arg3;
- (id)titleWithOrigin:(const struct GURL *)arg1;
- (id)labelForRequest:(struct PermissionBubbleRequest *)arg1;
- (id)getExpectedParentWindow;
- (int)getExpectedArrowLocation;
- (_Bool)hasVisibleLocationBar;
- (struct CGPoint)getExpectedAnchorPoint;
- (void)updateAnchorPosition;
- (void)showWithDelegate:(struct Delegate *)arg1 forRequests:(const vector_3273bf1c *)arg2 acceptStates:(const vector_a7cf9eda *)arg3;
- (void)parentWindowDidMove:(id)arg1;
- (void)parentWindowDidResize:(id)arg1;
- (void)parentWindowWillToggleFullScreen:(id)arg1;
- (void)windowWillClose:(id)arg1;
- (id)initWithBrowser:(struct Browser *)arg1 bridge:(struct PermissionBubbleCocoa *)arg2;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

