//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Jun  3 2014 10:55:11).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import <Google Chrome Framework/ToolTipBaseView.h>

#import "CommandDispatcherTarget.h"
#import "NSTextInputClient.h"
#import "RenderWidgetHostViewMacOwner.h"

@interface RenderWidgetHostViewCocoa : ToolTipBaseView <CommandDispatcherTarget, RenderWidgetHostViewMacOwner, NSTextInputClient>
{
    struct unique_ptr<content::RenderWidgetHostViewMac, std::__1::default_delete<content::RenderWidgetHostViewMac>> renderWidgetHostView_;
    struct scoped_nsobject<NSObject<RenderWidgetHostViewMacDelegate>> responderDelegate_;
    BOOL canBeKeyView_;
    BOOL closeOnDeactivate_;
    BOOL opaque_;
    struct unique_ptr<content::RenderWidgetHostViewMacEditCommandHelper, std::__1::default_delete<content::RenderWidgetHostViewMacEditCommandHelper>> editCommand_helper_;
    BOOL hasOpenMouseDown_;
    struct scoped_nsobject<NSCursor> currentCursor_;
    struct scoped_nsobject<NSArray> validAttributesForMarkedText_;
    BOOL handlingKeyDown_;
    BOOL hasMarkedText_;
    BOOL unmarkTextCalled_;
    struct _NSRange markedRange_;
    struct _NSRange selectedRange_;
    basic_string_61b65554 textToBeInserted_;
    basic_string_61b65554 markedText_;
    struct _NSRange markedTextSelectedRange_;
    struct vector<blink::WebCompositionUnderline, std::__1::allocator<blink::WebCompositionUnderline>> underlines_;
    struct Range setMarkedTextReplacementRange_;
    BOOL hasEditCommands_;
    struct vector<content::EditCommand, std::__1::allocator<content::EditCommand>> editCommands_;
    BOOL mouseEventWasIgnored_;
    id endWheelMonitor_;
    struct unique_ptr<blink::WebGestureEvent, std::__1::default_delete<blink::WebGestureEvent>> gestureBeginEvent_;
    _Bool pinchHasReachedZoomThreshold_;
    float pinchUnusedAmount_;
    double pinchLastGestureTimestamp_;
    BOOL gestureBeginPinchSent_;
    BOOL suppressNextEscapeKeyUp_;
    struct set<unsigned short, std::__1::less<unsigned short>, std::__1::allocator<unsigned short>> keyDownCodes_;
    struct MouseWheelRailsFilterMac mouseWheelFilter_;
}

+ (BOOL)shouldAutohideCursorForEvent:(id)arg1;
@property(nonatomic) struct _NSRange markedRange; // @synthesize markedRange=markedRange_;
@property(readonly, nonatomic) BOOL suppressNextEscapeKeyUp; // @synthesize suppressNextEscapeKeyUp=suppressNextEscapeKeyUp_;
@property(nonatomic) struct _NSRange selectedRange; // @synthesize selectedRange=selectedRange_;
- (id).cxx_construct;
- (void).cxx_destruct;
- (void)popupWindowWillClose:(id)arg1;
- (void)updateCursor:(id)arg1;
- (id)validRequestorForSendType:(id)arg1 returnType:(id)arg2;
- (void)confirmComposition;
- (void)cancelComposition;
- (void)stopSpeaking:(id)arg1;
- (void)startSpeaking:(id)arg1;
- (void)selectAll:(id)arg1;
- (void)pasteAndMatchStyle:(id)arg1;
- (void)paste:(id)arg1;
- (void)copyToFindPboard:(id)arg1;
- (void)copy:(id)arg1;
- (void)cut:(id)arg1;
- (void)redo:(id)arg1;
- (void)undo:(id)arg1;
- (void)viewDidMoveToWindow;
- (void)insertText:(id)arg1;
- (void)insertText:(id)arg1 replacementRange:(struct _NSRange)arg2;
- (void)doCommandBySelector:(SEL)arg1;
- (void)setMarkedText:(id)arg1 selectedRange:(struct _NSRange)arg2 replacementRange:(struct _NSRange)arg3;
- (void)unmarkText;
- (BOOL)hasMarkedText;
- (id)inputContext;
- (long long)conversationIdentifier;
- (id)attributedSubstringForProposedRange:(struct _NSRange)arg1 actualRange:(struct _NSRange *)arg2;
- (struct CGRect)firstRectForCharacterRange:(struct _NSRange)arg1 actualRange:(struct _NSRange *)arg2;
- (struct CGRect)firstViewRectForCharacterRange:(struct _NSRange)arg1 actualRange:(struct _NSRange *)arg2;
- (unsigned long long)characterIndexForPoint:(struct CGPoint)arg1;
- (id)validAttributesForMarkedText;
- (id)accessibilityFocusedUIElement;
- (unsigned long long)accessibilityGetIndexOf:(id)arg1;
- (BOOL)accessibilityIsIgnored;
- (id)accessibilityHitTest:(struct CGPoint)arg1;
- (id)accessibilityAttributeNames;
- (id)accessibilityAttributeValue:(id)arg1;
- (unsigned long long)accessibilityArrayAttributeCount:(id)arg1;
- (id)accessibilityArrayAttributeValues:(id)arg1 index:(unsigned long long)arg2 maxCount:(unsigned long long)arg3;
- (struct RenderWidgetHostViewMac *)renderWidgetHostViewMac;
- (BOOL)validateUserInterfaceItem:(id)arg1;
- (BOOL)resignFirstResponder;
- (BOOL)becomeFirstResponder;
- (void)windowDidResignKey:(id)arg1;
- (void)windowDidBecomeKey:(id)arg1;
- (BOOL)acceptsFirstResponder;
- (BOOL)canBecomeKeyView;
- (void)setFrameSize:(struct CGSize)arg1;
- (void)windowChangedGlobalFrame:(id)arg1;
- (void)windowDidChangeBackingProperties:(id)arg1;
- (void)updateScreenProperties;
- (void)viewWillMoveToWindow:(id)arg1;
- (void)magnifyWithEvent:(id)arg1;
- (void)scrollWheel:(id)arg1;
- (void)quickLookWithEvent:(id)arg1;
- (void)showLookUpDictionaryOverlayAtPoint:(struct CGPoint)arg1;
- (void)showLookUpDictionaryOverlayFromRange:(struct _NSRange)arg1 targetView:(id)arg2;
- (void)showLookUpDictionaryOverlayInternal:(id)arg1 baselinePoint:(struct CGPoint)arg2 targetView:(id)arg3;
- (void)smartMagnifyWithEvent:(id)arg1;
- (void)touchesEndedWithEvent:(id)arg1;
- (void)touchesCancelledWithEvent:(id)arg1;
- (void)touchesBeganWithEvent:(id)arg1;
- (void)touchesMovedWithEvent:(id)arg1;
- (void)endGestureWithEvent:(id)arg1;
- (void)beginGestureWithEvent:(id)arg1;
- (void)shortCircuitScrollWheelEvent:(id)arg1;
- (void)forceTouchEvent:(id)arg1;
- (void)keyEvent:(id)arg1 wasKeyEquivalent:(BOOL)arg2;
- (int)keyEvent:(id)arg1;
- (BOOL)_wantsKeyDownForEvent:(id)arg1;
- (BOOL)performKeyEquivalent:(id)arg1;
- (void)mouseEvent:(id)arg1;
- (BOOL)shouldIgnoreMouseEvent:(id)arg1;
- (void)setOpaque:(BOOL)arg1;
- (void)setCloseOnDeactivate:(BOOL)arg1;
- (BOOL)acceptsFirstMouse:(id)arg1;
- (BOOL)acceptsMouseEventsWhenInactive;
- (void)setCanBeKeyView:(BOOL)arg1;
- (id)forwardingTargetForSelector:(SEL)arg1;
- (BOOL)respondsToSelector:(SEL)arg1;
- (void)processedGestureScrollEvent:(const struct WebGestureEvent *)arg1 consumed:(BOOL)arg2;
- (void)processedWheelEvent:(const struct WebMouseWheelEvent *)arg1 consumed:(BOOL)arg2;
- (void)resetCursorRects;
- (void)setResponderDelegate:(id)arg1;
- (void)didChangeScreenParameters:(id)arg1;
- (void)dealloc;
- (id)initWithRenderWidgetHostViewMac:(struct RenderWidgetHostViewMac *)arg1;
- (BOOL)mouseDownCanMoveWindow;
- (BOOL)isOpaque;
- (BOOL)readSelectionFromPasteboard:(id)arg1;
- (BOOL)writeSelectionToPasteboard:(id)arg1 types:(id)arg2;

@end

