//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Jun  3 2014 10:55:11).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@interface ReplyEventHandler : NSObject
{
    Callback_55c68326 onReply_;
    struct AEDesc replyEvent_;
}

+ (void)pingProcess:(const struct ProcessSerialNumber *)arg1 andCall:(Callback_55c68326)arg2;
- (id).cxx_construct;
- (void).cxx_destruct;
- (void)closeWithSuccess:(_Bool)arg1;
- (void)message:(id)arg1 withReply:(id)arg2;
- (void)pingProcess:(const struct ProcessSerialNumber *)arg1;
- (id)initWithCallback:(Callback_55c68326)arg1;

@end

