//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Jun  3 2014 10:55:11).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSView.h"

#import "NSTextViewDelegate.h"

@class NSButton, NSString;

@interface SadTabContainerView : NSView <NSTextViewDelegate>
{
    struct scoped_nsobject<NSImageView> image_;
    scoped_nsobject_0ef9b51e title_;
    scoped_nsobject_0ef9b51e message_;
    scoped_nsobject_1b22b22f help_;
    scoped_nsobject_6cadfeaf button_;
}

- (id).cxx_construct;
- (void).cxx_destruct;
- (BOOL)textView:(id)arg1 clickedOnLink:(id)arg2 atIndex:(unsigned long long)arg3;
- (void)initializeHelpText;
- (void)resizeSubviewsWithOldSize:(struct CGSize)arg1;
@property(readonly, nonatomic) double contentHeight;
@property(readonly, nonatomic) NSButton *reloadButton;
- (BOOL)isFlipped;
- (id)initWithBackgroundColor:(id)arg1;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

