//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Jun  3 2014 10:55:11).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSWindowController.h"

#import "NSWindowDelegate.h"

@class NSString;

@interface ScreenCaptureNotificationController : NSWindowController <NSWindowDelegate>
{
    Callback_036fa0f5 stop_callback_;
    scoped_nsobject_6cadfeaf stopButton_;
    scoped_nsobject_6cadfeaf minimizeButton_;
}

- (id).cxx_construct;
- (void).cxx_destruct;
- (void)windowWillClose:(id)arg1;
- (void)populateWithText:(const basic_string_61b65554 *)arg1;
- (void)hide;
- (void)minimize:(id)arg1;
- (void)stopSharing:(id)arg1;
- (void)dealloc;
- (id)initWithCallback:(const Callback_036fa0f5 *)arg1 text:(const basic_string_61b65554 *)arg2;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

