//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Jun  3 2014 10:55:11).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSButton.h"

#import "ThemedWindowDrawing.h"

@interface ToolbarButton : NSButton <ThemedWindowDrawing>
{
    struct scoped_nsobject<NSImage> image_;
    BOOL handleMiddleClick_;
}

+ (struct CGSize)toolbarButtonSize;
@property(nonatomic) BOOL handleMiddleClick; // @synthesize handleMiddleClick=handleMiddleClick_;
- (id).cxx_construct;
- (void).cxx_destruct;
- (void)windowDidChangeActive;
- (void)windowDidChangeTheme;
- (void)viewDidMoveToWindow;
- (void)resetButtonStateImages;
- (void)setImage:(id)arg1;
- (id)image;
- (id)imageForIcon:(id)arg1 withBackgroundStyle:(int)arg2;
- (id)browserToolsIconForFillColor:(unsigned int)arg1;
- (unsigned int)vectorIconColor:(BOOL)arg1;
- (int)vectorIconId;
- (void)drawFocusRingMask;
- (BOOL)shouldHandleEvent:(id)arg1;
- (void)otherMouseDown:(id)arg1;

@end

