//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Jun  3 2014 10:55:11).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import <Google Chrome Framework/MenuController.h>

#import "HasWeakBrowserPointer.h"
#import "NSMenuDelegate.h"

@class NSMenuItem, NSString;

@interface AppMenuController : MenuController <NSMenuDelegate, HasWeakBrowserPointer>
{
    struct unique_ptr<AppMenuControllerInternal::AcceleratorDelegate, std::__1::default_delete<AppMenuControllerInternal::AcceleratorDelegate>> acceleratorDelegate_;
    struct unique_ptr<AppMenuModel, std::__1::default_delete<AppMenuModel>> appMenuModel_;
    struct unique_ptr<RecentTabsMenuModelDelegate, std::__1::default_delete<RecentTabsMenuModelDelegate>> recentTabsMenuModelDelegate_;
    struct scoped_nsobject<AppMenuButtonViewController> buttonViewController_;
    struct Browser *browser_;
    struct unique_ptr<BookmarkMenuBridge, std::__1::default_delete<BookmarkMenuBridge>> bookmarkMenuBridge_;
    struct unique_ptr<AppMenuControllerInternal::ZoomLevelObserver, std::__1::default_delete<AppMenuControllerInternal::ZoomLevelObserver>> zoom_level_observer_;
    struct unique_ptr<AppMenuControllerInternal::ToolbarActionsBarObserverHelper, std::__1::default_delete<AppMenuControllerInternal::ToolbarActionsBarObserverHelper>> toolbar_actions_bar_observer_;
    struct scoped_nsobject<BrowserActionsController> browserActionsController_;
    NSMenuItem *browserActionsMenuItem_;
    struct TimeTicks menuOpenTime_;
}

- (id).cxx_construct;
- (void).cxx_destruct;
- (int)maxWidthForMenuModel:(struct MenuModel *)arg1 modelIndex:(int)arg2;
- (struct RecentTabsSubMenuModel *)recentTabsMenuModel;
- (id)recentTabsSubmenu;
- (void)menu:(id)arg1 willHighlightItem:(id)arg2;
- (id)zoomDisplay;
- (void)adjustPositioning;
- (void)createModel;
- (id)browserActionsController;
- (void)updateRecentTabsSubmenu;
- (struct AppMenuModel *)appMenuModel;
- (void)performCommandDispatch:(id)arg1;
- (void)dispatchAppMenuCommand:(id)arg1;
- (void)menuNeedsUpdate:(id)arg1;
- (void)menuDidClose:(id)arg1;
- (void)menuWillOpen:(id)arg1;
- (void)updateBrowserActionsSubmenu;
- (void)updateBookmarkSubMenu;
- (id)bookmarkSubMenu;
- (BOOL)validateUserInterfaceItem:(id)arg1;
- (void)addItemToMenu:(id)arg1 atIndex:(long long)arg2 fromModel:(struct MenuModel *)arg3;
- (void)browserWillBeDestroyed;
- (void)dealloc;
- (id)initWithBrowser:(struct Browser *)arg1;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

