//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Jun  3 2014 10:55:11).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import <Google Chrome Framework/AutofillPopupBaseViewCocoa.h>

@interface AutofillPopupViewCocoa : AutofillPopupBaseViewCocoa
{
    struct AutofillPopupController *controller_;
    struct AutofillPopupViewCocoaDelegate *delegate_;
}

- (id)iconAtIndex:(unsigned long long)arg1;
- (double)drawSubtext:(id)arg1 atX:(double)arg2 rightAlign:(BOOL)arg3 bounds:(struct CGRect)arg4 textYOffset:(double)arg5;
- (double)drawIconAtIndex:(unsigned long long)arg1 atX:(double)arg2 rightAlign:(BOOL)arg3 bounds:(struct CGRect)arg4;
- (double)drawName:(id)arg1 atX:(double)arg2 index:(unsigned long long)arg3 rightAlign:(BOOL)arg4 bounds:(struct CGRect)arg5 textYOffset:(double)arg6;
- (void)drawSuggestionWithName:(id)arg1 subtext:(id)arg2 index:(unsigned long long)arg3 bounds:(struct CGRect)arg4 selected:(BOOL)arg5 textYOffset:(double)arg6;
- (void)invalidateRow:(unsigned long long)arg1;
- (void)controllerDestroyed;
- (void)drawRect:(struct CGRect)arg1;
- (id)initWithController:(struct AutofillPopupController *)arg1 frame:(struct CGRect)arg2 delegate:(struct AutofillPopupViewCocoaDelegate *)arg3;
- (id)initWithFrame:(struct CGRect)arg1;

@end

