//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Jun  3 2014 10:55:11).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSViewController.h"

#import "NSTableViewDataSource.h"
#import "NSTableViewDelegate.h"

@class NSButton, NSString, NSTableView;

@interface ChooserDialogCocoaController : NSViewController <NSTableViewDataSource, NSTableViewDelegate>
{
    struct scoped_nsobject<ChooserContentView> chooserContentView_;
    NSTableView *tableView_;
    NSButton *connectButton_;
    NSButton *cancelButton_;
    NSButton *helpButton_;
    struct ChooserDialogCocoa *chooserDialogCocoa_;
    struct ChooserController *chooserController_;
}

- (id).cxx_construct;
- (void).cxx_destruct;
- (id)chooserContentView;
- (void)onHelpPressed:(id)arg1;
- (void)onCancel:(id)arg1;
- (void)onConnect:(id)arg1;
- (void)tableViewSelectionDidChange:(id)arg1;
- (void)updateTableView;
- (void)onOptionRemoved:(long long)arg1;
- (void)onOptionAdded:(long long)arg1;
- (void)onOptionsInitialized;
- (BOOL)tableView:(id)arg1 shouldEditTableColumn:(id)arg2 row:(long long)arg3;
- (id)tableView:(id)arg1 objectValueForTableColumn:(id)arg2 row:(long long)arg3;
- (long long)numberOfRowsInTableView:(id)arg1;
- (id)initWithChooserDialogCocoa:(struct ChooserDialogCocoa *)arg1 chooserController:(struct ChooserController *)arg2;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

