//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Jun  3 2014 10:55:11).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSWindowController.h"

#import "NSOutlineViewDelegate.h"
#import "NSTabViewDelegate.h"
#import "NSWindowDelegate.h"

@class NSImageView, NSOutlineView, NSScrollView, NSString, NSTabView, NSTextField, NSTreeController, NSView, VerticalGradientView;

@interface CollectedCookiesWindowController : NSWindowController <NSOutlineViewDelegate, NSTabViewDelegate, NSWindowDelegate>
{
    struct unique_ptr<CookiesTreeModel, std::__1::default_delete<CookiesTreeModel>> allowedTreeModel_;
    struct unique_ptr<CookiesTreeModel, std::__1::default_delete<CookiesTreeModel>> blockedTreeModel_;
    scoped_nsobject_9420f295 icons_;
    struct unique_ptr<CookiesTreeControllerBridge, std::__1::default_delete<CookiesTreeControllerBridge>> allowedControllerBridge_;
    struct unique_ptr<CookiesTreeControllerBridge, std::__1::default_delete<CookiesTreeControllerBridge>> blockedControllerBridge_;
    BOOL allowedCookiesButtonsEnabled_;
    BOOL blockedCookiesButtonsEnabled_;
    BOOL deleteCookiesButtonEnabled_;
    NSTreeController *allowedTreeController_;
    NSTreeController *blockedTreeController_;
    NSOutlineView *allowedOutlineView_;
    NSOutlineView *blockedOutlineView_;
    VerticalGradientView *infoBar_;
    NSImageView *infoBarIcon_;
    NSTextField *infoBarText_;
    NSTabView *tabView_;
    NSScrollView *blockedScrollView_;
    NSTextField *blockedCookiesText_;
    NSView *cookieDetailsViewPlaceholder_;
    struct scoped_nsobject<NSViewAnimation> animation_;
    struct scoped_nsobject<CookieDetailsViewController> detailsViewController_;
    struct WebContents *webContents_;
    struct CollectedCookiesMac *collectedCookiesMac_;
    BOOL infoBarVisible_;
    BOOL contentSettingsChanged_;
}

+ (id)normalizeNodeSelection:(id)arg1;
@property(nonatomic) BOOL deleteCookiesButtonEnabled; // @synthesize deleteCookiesButtonEnabled=deleteCookiesButtonEnabled_;
@property(nonatomic) BOOL blockedCookiesButtonsEnabled; // @synthesize blockedCookiesButtonsEnabled=blockedCookiesButtonsEnabled_;
@property(nonatomic) BOOL allowedCookiesButtonsEnabled; // @synthesize allowedCookiesButtonsEnabled=allowedCookiesButtonsEnabled_;
@property(readonly, nonatomic) NSView *cookieDetailsViewPlaceholder; // @synthesize cookieDetailsViewPlaceholder=cookieDetailsViewPlaceholder_;
@property(readonly, nonatomic) NSTextField *blockedCookiesText; // @synthesize blockedCookiesText=blockedCookiesText_;
@property(readonly, nonatomic) NSScrollView *blockedScrollView; // @synthesize blockedScrollView=blockedScrollView_;
@property(readonly, nonatomic) NSTabView *tabView; // @synthesize tabView=tabView_;
@property(readonly, nonatomic) NSTextField *infoBarText; // @synthesize infoBarText=infoBarText_;
@property(readonly, nonatomic) NSImageView *infoBarIcon; // @synthesize infoBarIcon=infoBarIcon_;
@property(readonly, nonatomic) VerticalGradientView *infoBar; // @synthesize infoBar=infoBar_;
@property(readonly, nonatomic) NSOutlineView *blockedOutlineView; // @synthesize blockedOutlineView=blockedOutlineView_;
@property(readonly, nonatomic) NSOutlineView *allowedOutlineView; // @synthesize allowedOutlineView=allowedOutlineView_;
@property(readonly, nonatomic) NSTreeController *blockedTreeController; // @synthesize blockedTreeController=blockedTreeController_;
@property(readonly, nonatomic) NSTreeController *allowedTreeController; // @synthesize allowedTreeController=allowedTreeController_;
- (id).cxx_construct;
- (void).cxx_destruct;
- (void)tabView:(id)arg1 didSelectTabViewItem:(id)arg2;
- (void)animateInfoBar;
- (void)showInfoBarForDomain:(const basic_string_61b65554 *)arg1 setting:(int)arg2;
- (void)showInfoBarForMultipleDomainsAndSetting:(int)arg1;
- (void)loadTreeModelFromWebContents;
- (void)outlineViewSelectionDidChange:(id)arg1;
- (void)outlineView:(id)arg1 willDisplayCell:(id)arg2 forTableColumn:(id)arg3 item:(id)arg4;
- (struct CookiesTreeModel *)blockedTreeModel;
- (id)cocoaBlockedTreeModel;
- (struct CookiesTreeModel *)allowedTreeModel;
- (id)cocoaAllowedTreeModel;
- (void)deleteSelected:(id)arg1;
- (void)blockOrigin:(id)arg1;
- (void)allowForSessionFromOrigin:(id)arg1;
- (void)allowOrigin:(id)arg1;
- (void)addException:(int)arg1 forTreeController:(id)arg2;
- (void)closeSheet:(id)arg1;
- (void)windowWillClose:(id)arg1;
- (void)awakeFromNib;
- (id)initWithWebContents:(struct WebContents *)arg1 collectedCookiesMac:(struct CollectedCookiesMac *)arg2;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

