//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Jun  3 2014 10:55:11).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class NSTimer;

@interface ContentSettingAnimationState : NSObject
{
    struct ContentSettingDecoration *owner_;
    double progress_;
    NSTimer *timer_;
}

@property(readonly, nonatomic) double progress; // @synthesize progress=progress_;
- (void)timerFired:(id)arg1;
- (int)animationState;
- (void)stopAnimation;
- (void)dealloc;
- (id)initWithOwner:(struct ContentSettingDecoration *)arg1;

@end

