//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Jun  3 2014 10:55:11).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSViewController.h"

@class GTMUILocalizerAndLayoutTweaker, NSObjectController;

@interface CookieDetailsViewController : NSViewController
{
    NSObjectController *objectController_;
    GTMUILocalizerAndLayoutTweaker *tweaker_;
}

@property(readonly, nonatomic) BOOL hasExpiration; // @dynamic hasExpiration;
- (void)setCookieHasExplicitExpiration:(id)arg1;
- (void)setCookieDoesntHaveExplicitExpiration:(id)arg1;
- (void)configureBindingsForTreeController:(id)arg1;
- (void)shrinkViewToFit;
- (void)setContentObject:(id)arg1;
- (void)getLowestLabelVerticalPosition:(id)arg1 lowestLabelPosition:(float *)arg2;
- (void)awakeFromNib;
- (id)init;

@end

