//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Jun  3 2014 10:55:11).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSButtonCell.h"

@interface CredentialItemButtonCell : NSButtonCell
{
    int marginSpacing_;
    int imageTitleSpacing_;
}

- (void)drawWithFrame:(struct CGRect)arg1 inView:(id)arg2;
- (unsigned long long)focusRingType;
- (struct CGSize)cellSize;
- (void)drawImage:(id)arg1 withFrame:(struct CGRect)arg2 inView:(id)arg3;
- (struct CGRect)drawTitle:(id)arg1 withFrame:(struct CGRect)arg2 inView:(id)arg3;
- (id)initWithMarginSpacing:(int)arg1 imageTitleSpacing:(int)arg2;

@end

