//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Jun  3 2014 10:55:11).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import <Google Chrome Framework/HoverButton.h>

@interface CredentialItemButton : HoverButton
{
    struct scoped_nsobject<NSColor> backgroundColor_;
    struct scoped_nsobject<NSColor> hoverColor_;
    int credentialType_;
    struct PasswordForm *passwordForm_;
}

+ (id)defaultAvatar;
@property(nonatomic) int credentialType; // @synthesize credentialType=credentialType_;
@property(nonatomic) struct PasswordForm *passwordForm; // @synthesize passwordForm=passwordForm_;
- (id).cxx_construct;
- (void).cxx_destruct;
- (BOOL)canBecomeKeyView;
- (void)setHoverState:(int)arg1;
- (id)initWithFrame:(struct CGRect)arg1 backgroundColor:(id)arg2 hoverColor:(id)arg3;

@end

