//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Jun  3 2014 10:55:11).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@interface DesktopMediaPickerItem : NSObject
{
    struct DesktopMediaID sourceID_;
    struct scoped_nsobject<NSString> imageUID_;
    struct scoped_nsobject<NSString> imageTitle_;
    struct scoped_nsobject<NSImage> image_;
    unsigned long long imageVersion_;
}

- (id).cxx_construct;
- (void).cxx_destruct;
- (id)imageRepresentation;
- (unsigned long long)imageVersion;
- (id)imageTitle;
- (id)imageRepresentationType;
- (id)imageUID;
- (void)setImageTitle:(id)arg1;
- (void)setImageRepresentation:(id)arg1;
- (struct DesktopMediaID)sourceID;
- (id)initWithSourceId:(struct DesktopMediaID)arg1 imageUID:(int)arg2 imageTitle:(id)arg3;

@end

