//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Jun  3 2014 10:55:11).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import <Google Chrome Framework/BaseBubbleController.h>

@class GTMUILocalizerAndLayoutTweaker, GTMWidthBasedTweaker, NSButton, NSImageView, NSTextField;

@interface GlobalErrorBubbleController : BaseBubbleController
{
    WeakPtr_9b84912e error_;
    struct unique_ptr<GlobalErrorBubbleControllerInternal::Bridge, std::__1::default_delete<GlobalErrorBubbleControllerInternal::Bridge>> bridge_;
    struct Browser *browser_;
    NSImageView *iconView_;
    NSTextField *title_;
    NSTextField *message_;
    NSButton *acceptButton_;
    NSButton *cancelButton_;
    GTMUILocalizerAndLayoutTweaker *layoutTweaker_;
    GTMWidthBasedTweaker *buttonContainer_;
}

+ (struct GlobalErrorBubbleViewBase *)showForBrowser:(struct Browser *)arg1 error:(const WeakPtr_9b84912e *)arg2;
- (id).cxx_construct;
- (void).cxx_destruct;
- (void)onCancel:(id)arg1;
- (void)onAccept:(id)arg1;
- (void)close;
- (void)showWindow:(id)arg1;
- (void)awakeFromNib;

@end

