//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Jun  3 2014 10:55:11).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class NSString;

@interface GTMFileSystemKQueue : NSObject
{
    NSString *path_;
    int fd_;
    unsigned int events_;
    BOOL acrossReplace_;
    id target_;
    SEL action_;
}

- (void)notify:(unsigned int)arg1;
- (void)unregisterWithKQueue;
- (int)registerWithKQueue;
- (void)addFileDescriptorMonitor:(int)arg1;
- (id)path;
- (void)dealloc;
- (id)initWithPath:(id)arg1 forEvents:(unsigned int)arg2 acrossReplace:(BOOL)arg3 target:(id)arg4 action:(SEL)arg5;
- (id)init;

@end

