//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Jun  3 2014 10:55:11).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

#import "GTMLogWriter.h"

@class NSString;

@interface GTMLoggerRingBufferWriter : NSObject <GTMLogWriter>
{
    id <GTMLogWriter> writer_;
    struct GTMRingBufferPair *buffer_;
    unsigned long long capacity_;
    unsigned long long nextIndex_;
    unsigned long long totalLogged_;
}

+ (id)ringBufferWriterWithCapacity:(unsigned long long)arg1 writer:(id)arg2;
- (void)logMessage:(id)arg1 level:(int)arg2;
- (void)addMessage:(id)arg1 level:(int)arg2;
- (void)dumpContents;
- (void)reset;
- (void)iterateBufferWithCallback:(CDUnknownFunctionPointerType)arg1;
- (unsigned long long)totalLogged;
- (unsigned long long)droppedLogCount;
- (unsigned long long)count;
- (id)writer;
- (unsigned long long)capacity;
- (void)dealloc;
- (id)init;
- (id)initWithCapacity:(unsigned long long)arg1 writer:(id)arg2;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

