//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Jun  3 2014 10:55:11).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@interface GTMLoginItems : NSObject
{
}

+ (void)removeItemWithNameFromLoginItems:(id)arg1;
+ (void)removePathFromLoginItems:(id)arg1;
+ (void)addPathToLoginItems:(id)arg1 hide:(BOOL)arg2;
+ (BOOL)itemWithNameInLoginItems:(id)arg1;
+ (BOOL)pathInLoginItems:(id)arg1;
+ (id)loginItems:(id *)arg1;
+ (id)loginItemsArrayForFileListRef:(struct OpaqueLSSharedFileListRef *)arg1;
+ (struct OpaqueLSSharedFileListRef *)loginItemsFileListRef;
+ (long long)indexOfLoginItemWithValue:(id)arg1 forKey:(id)arg2 loginItems:(id)arg3;

@end

