//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Jun  3 2014 10:55:11).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@interface GTMSignalHandler : NSObject
{
    int signo_;
    id target_;
    SEL action_;
}

- (void)notify;
- (void)invalidate;
- (void)registerWithKQueue;
- (void)addFileDescriptorMonitor:(int)arg1;
- (void)dealloc;
- (id)initWithSignal:(int)arg1 target:(id)arg2 action:(SEL)arg3;
- (id)init;

@end

