//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Jun  3 2014 10:55:11).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@interface GTMSystemVersion : NSObject
{
}

+ (id)runtimeArchitecture;
+ (BOOL)isSnowLeopardOrGreater;
+ (BOOL)isLeopardOrGreater;
+ (BOOL)isTigerOrGreater;
+ (BOOL)isPantherOrGreater;
+ (BOOL)isSnowLeopard;
+ (BOOL)isLeopard;
+ (BOOL)isTiger;
+ (BOOL)isPanther;
+ (BOOL)isBuildEqualTo:(id)arg1;
+ (BOOL)isBuildGreaterThanOrEqualTo:(id)arg1;
+ (BOOL)isBuildGreaterThan:(id)arg1;
+ (BOOL)isBuildLessThanOrEqualTo:(id)arg1;
+ (BOOL)isBuildLessThan:(id)arg1;
+ (id)build;
+ (void)getMajor:(int *)arg1 minor:(int *)arg2 bugFix:(int *)arg3;
+ (void)initialize;

@end

