//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Jun  3 2014 10:55:11).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSButtonCell.h"

@class NSColor;

@interface HyperlinkButtonCell : NSButtonCell
{
    struct scoped_nsobject<NSColor> textColor_;
    int underlineBehavior_;
    BOOL mouseIsInside_;
}

+ (id)buttonWithString:(id)arg1;
+ (id)defaultTextColor;
@property(nonatomic) int underlineBehavior; // @synthesize underlineBehavior=underlineBehavior_;
- (id).cxx_construct;
- (void).cxx_destruct;
- (struct CGSize)cellSize;
@property(retain, nonatomic) NSColor *textColor; // @dynamic textColor;
- (void)mouseExited:(id)arg1;
- (void)mouseEntered:(id)arg1;
- (struct CGRect)drawTitle:(id)arg1 withFrame:(struct CGRect)arg2 inView:(id)arg3;
- (id)linkAttributes;
- (void)setControlSize:(unsigned long long)arg1;
- (void)customizeButtonCell;
- (id)copyWithZone:(struct _NSZone *)arg1;
- (id)initTextCell:(id)arg1;
- (id)initWithCoder:(id)arg1;
- (id)init;

@end

