//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Jun  3 2014 10:55:11).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSViewController.h"

#import "InfoBarContainerControllerBase.h"

@interface InfoBarContainerController : NSViewController <InfoBarContainerControllerBase>
{
    id <ViewResizer> resizeDelegate_;
    struct WebContents *currentWebContents_;
    scoped_nsobject_9420f295 infobarControllers_;
    struct unique_ptr<InfoBarContainerCocoa, std::__1::default_delete<InfoBarContainerCocoa>> containerCocoa_;
    BOOL shouldSuppressTopInfoBarTip_;
    double infobarArrowX_;
    BOOL isAnimating_;
}

@property(nonatomic) double infobarArrowX; // @synthesize infobarArrowX=infobarArrowX_;
@property(nonatomic) BOOL shouldSuppressTopInfoBarTip; // @synthesize shouldSuppressTopInfoBarTip=shouldSuppressTopInfoBarTip_;
- (id).cxx_construct;
- (void).cxx_destruct;
- (double)heightOfInfoBars;
- (void)setMaxTopArrowHeight:(long long)arg1;
- (void)removeController:(id)arg1;
- (void)positionInfoBarsAndRedraw:(BOOL)arg1;
- (void)removeInfoBar:(struct InfoBarCocoa *)arg1;
- (void)addInfoBar:(struct InfoBarCocoa *)arg1 position:(unsigned long long)arg2;
- (double)overlappingTipHeight;
- (void)tabDetachedWithContents:(struct WebContents *)arg1;
- (void)changeWebContents:(struct WebContents *)arg1;
- (void)dealloc;
- (id)initWithResizeDelegate:(id)arg1;

@end

