//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Jun  3 2014 10:55:11).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSBezierPath.h"

@interface NSBezierPath (GTMBezierPathRoundRectAdditions)
+ (id)gtm_bezierPathWithRoundRect:(struct CGRect)arg1 topLeftCornerRadius:(double)arg2 topRightCornerRadius:(double)arg3 bottomLeftCornerRadius:(double)arg4 bottomRightCornerRadius:(double)arg5;
+ (id)gtm_bezierPathWithRoundRect:(struct CGRect)arg1 cornerRadius:(double)arg2;
- (void)gtm_appendBezierPathWithRoundRect:(struct CGRect)arg1 topLeftCornerRadius:(double)arg2 topRightCornerRadius:(double)arg3 bottomLeftCornerRadius:(double)arg4 bottomRightCornerRadius:(double)arg5;
- (void)gtm_appendBezierPathWithRoundRect:(struct CGRect)arg1 cornerRadius:(double)arg2;
@end

