//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Jun  3 2014 10:55:11).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSString.h"

@interface NSString (GTMStringFindFolderAdditions)
+ (id)gtm_stringWithPathForFolder:(unsigned int)arg1 subfolderName:(id)arg2 inDomain:(short)arg3 doCreate:(BOOL)arg4;
+ (id)gtm_stringWithPathForFolder:(unsigned int)arg1 inDomain:(short)arg2 doCreate:(BOOL)arg3;
@end

