//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Jun  3 2014 10:55:11).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSWorkspace.h"

@interface NSWorkspace (GTMWorkspaceRunningAdditions)
- (id)gtm_launchedApplications;
- (struct ProcessSerialNumber)gtm_numberToProcessSerialNumber:(id)arg1;
- (BOOL)gtm_processSerialNumber:(struct ProcessSerialNumber *)arg1 withBundleID:(id)arg2;
- (BOOL)gtm_wasLaunchedByProcess:(id)arg1;
- (BOOL)gtm_wasLaunchedAsLoginItem;
- (id)gtm_processInfoDictionaryForActiveApp;
- (id)gtm_processInfoDictionary;
- (id)gtm_processInfoDictionaryForPSN:(const struct ProcessSerialNumber *)arg1;
- (id)gtm_processInfoDictionaryForPID:(int)arg1;
- (BOOL)gtm_isAppWithIdentifierRunning:(id)arg1;
@end

