//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Jun  3 2014 10:55:11).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSWorkspace.h"

@interface NSWorkspace (CaminoDefaultBrowserAdditions)
+ (id)osVersionString;
- (id)displayNameForFile:(id)arg1;
- (id)identifierForBundle:(id)arg1;
- (id)urlOfApplicationWithIdentifier:(id)arg1;
- (void)setDefaultFeedViewerWithIdentifier:(id)arg1;
- (void)setDefaultBrowserWithIdentifier:(id)arg1;
- (id)defaultFeedViewerURL;
- (id)defaultBrowserURL;
- (id)defaultFeedViewerIdentifier;
- (id)defaultBrowserIdentifier;
- (id)installedFeedViewerIdentifiers;
- (id)installedBrowserIdentifiers;
@end

