//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Jun  3 2014 10:55:11).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSView.h"

#import "MouseDragControllerClient.h"
#import "NSAnimationDelegate.h"

@class HoverImageButton, NSButton, NSString, NSTextField, PanelWindowControllerCocoa;

@interface PanelTitlebarViewCocoa : NSView <NSAnimationDelegate, MouseDragControllerClient>
{
    PanelWindowControllerCocoa *controller_;
    NSView *icon_;
    NSTextField *title_;
    HoverImageButton *minimizeButton_;
    HoverImageButton *restoreButton_;
    HoverImageButton *customCloseButton_;
    NSView *overlay_;
    NSButton *closeButton_;
    struct ScopedCrTrackingArea closeButtonTrackingArea_;
    BOOL isDrawingAttention_;
    struct scoped_nsobject<RepaintAnimation> glintAnimation_;
    struct scoped_nsobject<NSTimer> glintAnimationTimer_;
    int glintCounter_;
    struct scoped_nsobject<MouseDragController> dragController_;
}

- (id).cxx_construct;
- (void).cxx_destruct;
- (id)restoreButton;
- (id)minimizeButton;
- (id)closeButton;
- (void)finishDragTitlebar;
- (void)cancelDragTitlebar;
- (void)dragTitlebar:(struct CGPoint)arg1;
- (void)releaseLeftMouseButtonTitlebar:(int)arg1;
- (void)pressLeftMouseButtonTitlebar:(struct CGPoint)arg1 modifiers:(int)arg2;
- (void)simulateCloseButtonClick;
- (id)title;
- (id)controller;
- (float)animation:(id)arg1 valueForProgress:(float)arg2;
- (void)animationDidEnd:(id)arg1;
- (void)restartGlintAnimation:(id)arg1;
- (void)stopGlintAnimation;
- (void)startGlintAnimation;
- (BOOL)isDrawingAttention;
- (void)stopDrawingAttention;
- (void)drawAttention;
- (void)cleanupAfterDrag;
- (void)dragProgress:(struct CGPoint)arg1;
- (void)dragEnded:(BOOL)arg1;
- (void)dragStarted:(struct CGPoint)arg1;
- (void)prepareForDrag;
- (void)mouseDragged:(id)arg1;
- (void)mouseUp:(id)arg1;
- (void)mouseDown:(id)arg1;
- (void)didChangeMainWindow:(id)arg1;
- (void)didChangeFrame:(id)arg1;
- (BOOL)acceptsFirstMouse:(id)arg1;
- (BOOL)mouseDownCanMoveWindow;
- (void)updateIconAndTitleLayout;
- (void)updateCustomButtonsLayout;
- (void)setRestoreButtonVisibility:(BOOL)arg1;
- (void)setMinimizeButtonVisibility:(BOOL)arg1;
- (id)icon;
- (void)setIcon:(id)arg1;
- (void)setTitle:(id)arg1;
- (void)initializeImageButton:(id)arg1 image:(id)arg2 hoverImage:(id)arg3 pressedImage:(id)arg4 toolTip:(id)arg5;
- (void)attach;
- (void)drawRect:(struct CGRect)arg1;
- (void)onRestoreButtonClick:(id)arg1;
- (void)onMinimizeButtonClick:(id)arg1;
- (void)onCloseButtonClick:(id)arg1;
- (void)dealloc;
- (id)initWithFrame:(struct CGRect)arg1;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

