//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Jun  3 2014 10:55:11).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import <Google Chrome Framework/MenuButton.h>

#import "ImageButton.h"

@class NSTimer;

@interface ReloadButton : MenuButton <ImageButton>
{
    NSTimer *pendingReloadTimer_;
    struct scoped_nsobject<NSMenu> menu_;
    struct CommandUpdater *commandUpdater_;
}

+ (Class)cellClass;
+ (void)setPendingReloadTimeout:(double)arg1;
- (id).cxx_construct;
- (void).cxx_destruct;
- (void)executeMenuItem:(id)arg1;
- (void)populateMenu;
- (void)mouseInsideStateDidChange:(BOOL)arg1;
- (int)vectorIconId;
- (int)viewID;
- (BOOL)sendAction:(SEL)arg1 to:(id)arg2;
- (void)forceReloadState:(id)arg1;
- (void)setCommandUpdater:(struct CommandUpdater *)arg1;
- (void)setMenuEnabled:(BOOL)arg1;
- (void)setIsLoading:(BOOL)arg1 force:(BOOL)arg2;
- (id)accessibilityAttributeValue:(id)arg1;
- (void)updateTag:(long long)arg1;
- (void)invalidatePendingReloadTimer;
- (void)awakeFromNib;
- (void)viewWillMoveToWindow:(id)arg1;
- (id)initWithFrame:(struct CGRect)arg1;

@end

