//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Jun  3 2014 10:55:11).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

@class NSEvent, NSView;

@protocol RenderWidgetHostViewMacDelegate
- (void)rendererHandledGestureScrollEvent:(const struct WebGestureEvent *)arg1 consumed:(BOOL)arg2;
- (void)rendererHandledWheelEvent:(const struct WebMouseWheelEvent *)arg1 consumed:(BOOL)arg2;
- (BOOL)canRubberbandRight:(NSView *)arg1;
- (BOOL)canRubberbandLeft:(NSView *)arg1;
- (void)touchesEndedWithEvent:(NSEvent *)arg1;
- (void)touchesCancelledWithEvent:(NSEvent *)arg1;
- (void)touchesBeganWithEvent:(NSEvent *)arg1;
- (void)touchesMovedWithEvent:(NSEvent *)arg1;
- (void)endGestureWithEvent:(NSEvent *)arg1;
- (void)beginGestureWithEvent:(NSEvent *)arg1;

@optional
- (BOOL)validateUserInterfaceItem:(id <NSValidatedUserInterfaceItem>)arg1 isValidItem:(char *)arg2;
- (BOOL)handleEvent:(NSEvent *)arg1;
- (void)viewGone:(NSView *)arg1;
@end

