//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Jun  3 2014 10:55:11).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@interface ScrollbarPrefsObserver : NSObject
{
}

+ (void)notifyPrefsChangedWithRedraw:(BOOL)arg1;
+ (void)systemColorsChanged:(id)arg1;
+ (void)behaviorPrefsChanged:(id)arg1;
+ (void)appearancePrefsChanged:(id)arg1;
+ (void)registerAsObserver;

@end

