//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Jun  3 2014 10:55:11).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

#import "NSOpenSavePanelDelegate.h"

@class NSString;

@interface SelectFileDialogBridge : NSObject <NSOpenSavePanelDelegate>
{
    struct SelectFileDialogImpl *selectFileDialogImpl_;
}

- (BOOL)panel:(id)arg1 shouldEnableURL:(id)arg2;
- (void)endedPanel:(id)arg1 didCancel:(_Bool)arg2 type:(int)arg3 parentWindow:(id)arg4;
- (id)initWithSelectFileDialogImpl:(struct SelectFileDialogImpl *)arg1;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

