//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Jun  3 2014 10:55:11).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSView.h"

@class TabContentsController;

@interface TabContentsContainerView : NSView
{
    TabContentsController *delegate_;
}

- (BOOL)canBecomeKeyView;
- (BOOL)becomeFirstResponder;
- (BOOL)acceptsFirstResponder;
- (int)viewID;
- (void)updateBackgroundColor;
- (void)setNeedsDisplayInRect:(struct CGRect)arg1;
- (void)resizeSubviewsWithOldSize:(struct CGSize)arg1;
- (void)delegateDestroyed;
- (id)initWithDelegate:(id)arg1;

@end

