//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Jun  3 2014 10:55:11).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import <Google Chrome Framework/BackgroundGradientView.h>

#import "URLDropTarget.h"

@class TabStripController;

@interface TabStripView : BackgroundGradientView <URLDropTarget>
{
    TabStripController *controller_;
    double lastMouseUp_;
    struct scoped_nsobject<URLDropTargetHandler> dropHandler_;
    struct scoped_nsobject<NewTabButton> newTabButton_;
    BOOL dropArrowShown_;
    struct CGPoint dropArrowPosition_;
    BOOL inATabDraggingOverlayWindow_;
}

@property(nonatomic) BOOL inATabDraggingOverlayWindow; // @synthesize inATabDraggingOverlayWindow=inATabDraggingOverlayWindow_;
@property(nonatomic) struct CGPoint dropArrowPosition; // @synthesize dropArrowPosition=dropArrowPosition_;
@property(nonatomic) BOOL dropArrowShown; // @synthesize dropArrowShown=dropArrowShown_;
- (id).cxx_construct;
- (void).cxx_destruct;
- (void)windowDidChangeActive;
- (void)windowDidChangeTheme;
- (void)setController:(id)arg1;
- (id)visualEffectView;
- (void)setNewTabButton:(id)arg1;
- (id)getNewTabButton;
- (int)viewID;
- (id)accessibilityAttributeNames;
- (id)accessibilityAttributeValue:(id)arg1;
- (id)tabStripViewAccessibilityChildren;
- (BOOL)accessibilityIsIgnored;
- (BOOL)performDragOperation:(id)arg1;
- (void)draggingExited:(id)arg1;
- (unsigned long long)draggingUpdated:(id)arg1;
- (unsigned long long)draggingEntered:(id)arg1;
- (id)urlDropController;
- (void)mouseUp:(id)arg1;
- (BOOL)acceptsFirstMouse:(id)arg1;
- (BOOL)doubleClickMinimizesWindow;
- (void)drawRect:(struct CGRect)arg1;
- (void)drawBottomEdge:(struct CGRect)arg1;
- (id)initWithFrame:(struct CGRect)arg1;

@end

