//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Jun  3 2014 10:55:11).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSViewController.h"

#import "HasWeakBrowserPointer.h"
#import "URLDropTargetController.h"

@class AutocompleteTextField, BrowserActionsContainerView, MenuButton, NSButton, ReloadButton, ToolbarButton;

@interface ToolbarController : NSViewController <URLDropTargetController, HasWeakBrowserPointer>
{
    MenuButton *backButton_;
    MenuButton *forwardButton_;
    ReloadButton *reloadButton_;
    ToolbarButton *homeButton_;
    MenuButton *appMenuButton_;
    AutocompleteTextField *locationBar_;
    BrowserActionsContainerView *browserActionsContainerView_;
    struct CommandUpdater *commands_;
    struct Profile *profile_;
    struct Browser *browser_;
    struct unique_ptr<ToolbarControllerInternal::CommandObserverBridge, std::__1::default_delete<ToolbarControllerInternal::CommandObserverBridge>> commandObserver_;
    struct unique_ptr<LocationBarViewMac, std::__1::default_delete<LocationBarViewMac>> locationBarView_;
    struct scoped_nsobject<AutocompleteTextFieldEditor> autocompleteTextFieldEditor_;
    struct scoped_nsobject<BackForwardMenuController> backMenuController_;
    struct scoped_nsobject<BackForwardMenuController> forwardMenuController_;
    struct scoped_nsobject<BrowserActionsController> browserActionsController_;
    struct unique_ptr<BrowserActionsContainerViewSizeDelegate, std::__1::default_delete<BrowserActionsContainerViewSizeDelegate>> browserActionsContainerDelegate_;
    struct scoped_nsobject<AppMenuController> appMenuController_;
    struct unique_ptr<ToolbarControllerInternal::NotificationBridge, std::__1::default_delete<ToolbarControllerInternal::NotificationBridge>> notificationBridge_;
    struct PrefMember<bool> showHomeButton_;
    BOOL hasToolbar_;
    BOOL hasLocationBar_;
    BOOL locationBarAtMinSize_;
    struct ScopedCrTrackingArea trackingArea_;
    NSButton *hoveredButton_;
}

+ (double)materialDesignButtonInset;
+ (double)appMenuLeftPadding;
+ (double)locationBarHeight;
@property(nonatomic) struct Browser *browser; // @synthesize browser=browser_;
- (id).cxx_construct;
- (void).cxx_destruct;
- (BOOL)isUnsupportedDropData:(id)arg1;
- (void)hideDropURLsIndicatorInView:(id)arg1;
- (void)indicateDropURLsInView:(id)arg1 at:(struct CGPoint)arg2;
- (void)dropText:(id)arg1 inView:(id)arg2 at:(struct CGPoint)arg3;
- (void)dropURLs:(id)arg1 inView:(id)arg2 at:(struct CGPoint)arg3;
- (id)appMenuController;
- (id)appMenuButton;
- (id)browserActionsController;
- (void)setDividerOpacity:(double)arg1;
- (double)desiredHeightForCompression:(double)arg1;
- (double)baseToolbarHeight;
- (struct CGPoint)translateBubblePoint;
- (struct CGPoint)saveCreditCardBubblePoint;
- (struct CGPoint)managePasswordsBubblePoint;
- (struct CGPoint)bookmarkBubblePoint;
- (void)adjustLocationSizeBy:(double)arg1 animate:(BOOL)arg2;
- (void)showLocationBarOnly;
- (void)toolbarFrameChanged;
- (void)maintainMinimumLocationBarWidth;
- (void)pinLocationBarToLeftOfBrowserActionsContainerAndAnimate:(BOOL)arg1;
- (void)browserActionsContainerWillAnimate:(id)arg1;
- (void)browserActionsVisibilityChanged:(id)arg1;
- (void)browserActionsContainerDragged:(id)arg1;
- (void)adjustBrowserActionsContainerForNewWindow:(id)arg1;
- (void)updateVisibility:(BOOL)arg1 withAnimation:(BOOL)arg2;
- (void)createBrowserActionButtons;
- (void)prefChanged:(const basic_string_805fe43b *)arg1;
- (void)updateAppMenuButtonSeverity:(int)arg1 animate:(BOOL)arg2;
- (void)installAppMenu;
- (void)showOptionalHomeButton;
- (struct CGRect)adjustRect:(struct CGRect)arg1 byAmount:(double)arg2;
- (id)toolbarViews;
- (id)customFieldEditorForObject:(id)arg1;
- (id)toolbarView;
- (void)setHasToolbar:(BOOL)arg1 hasLocationBar:(BOOL)arg2;
- (void)setIsLoading:(BOOL)arg1 force:(BOOL)arg2;
- (void)zoomChangedForActiveTab:(BOOL)arg1;
- (void)setTranslateIconLit:(BOOL)arg1;
- (void)setStarredState:(BOOL)arg1;
- (void)resetTabState:(struct WebContents *)arg1;
- (void)updateToolbarWithContents:(struct WebContents *)arg1;
- (void)initCommandStatus:(struct CommandUpdater *)arg1;
- (void)enabledStateChangedForCommand:(int)arg1 enabled:(_Bool)arg2;
- (void)focusLocationBar:(BOOL)arg1;
- (void)locationBarWasAddedToWindow;
- (struct LocationBarViewMac *)locationBarBridge;
- (void)mouseEntered:(id)arg1;
- (void)mouseMoved:(id)arg1;
- (id)hoverButtonForEvent:(id)arg1;
- (void)mouseExited:(id)arg1;
- (void)addAccessibilityDescriptions;
- (void)cleanUp;
- (void)browserWillBeDestroyed;
- (void)dealloc;
- (void)viewDidLoad;
- (void)awakeFromNib;
- (id)initWithCommands:(struct CommandUpdater *)arg1 profile:(struct Profile *)arg2 browser:(struct Browser *)arg3 resizeDelegate:(id)arg4;

@end

