//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Jun  3 2014 10:55:11).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSButton.h"

@interface NCConfigButton : NSButton
{
    _Bool _showsNewIndicator;
    double _titleWidth;
}

+ (Class)cellClass;
@property(nonatomic) double titleWidth; // @synthesize titleWidth=_titleWidth;
@property(nonatomic) _Bool showsNewIndicator; // @synthesize showsNewIndicator=_showsNewIndicator;
- (void)_setIndicatorImage;
- (struct CGSize)intrinsicContentSize;
- (void)setTitle:(id)arg1;
- (void)awakeFromNib;

@end

