//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Jun  3 2014 10:55:11).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NCTableCellView.h"

#import "NCNotificationTableCellHeight.h"

@class NCAppListViewController, NSLayoutConstraint, NSString;

@interface NCNotificationTableCellView : NCTableCellView <NCNotificationTableCellHeight>
{
    NCAppListViewController *_listViewController;
    NSLayoutConstraint *_widthConstraint;
    BOOL _setup;
    float _height;
}

- (void).cxx_destruct;
- (void)updateDate;
@property(readonly, nonatomic) float height; // @synthesize height=_height;
- (void)setObjectValue:(id)arg1;
- (void)_tableWidthChanged:(id)arg1;
- (void)viewDidMoveToSuperview;
- (void)viewWillMoveToSuperview:(id)arg1;
- (BOOL)wantsUpdateLayer;
- (void)setupForNotifications;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

