//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Jun  3 2014 10:55:11).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

#import "DOCKGestureHandler.h"

@class CALayer, NSArray, NSMutableArray, NSObject<OS_dispatch_queue>, NSObject<OS_dispatch_source>, NSObject<OS_xpc_object>, NSSet, WALayerKitWindow, WAWindow, _CGSSpace;

@interface DockNotificationCenter : NSObject <DOCKGestureHandler>
{
    NSObject<OS_dispatch_queue> *_server_queue;
    NSObject<OS_xpc_object> *_connection;
    NSObject<OS_xpc_object> *_center_connection;
    BOOL _connectionValidated;
    BOOL _debugShieldWindow;
    NSSet *_notificationWIDs;
    WAWindow *_shieldWindow;
    unsigned int _lastDisplay;
    unsigned int _alertWID;
    _CGSSpace *_space;
    double _currentProgress;
    double _centerWidth;
    double _centerMaxWidth;
    double _singlePixelScrollAmount;
    NSArray *_windowsMoved;
    unsigned long long _totalWindowCount;
    struct CGRect _shieldWindowFrame;
    struct CGRect _shieldWindowEndClip;
    struct CGRect _desktopCopyStart;
    struct CGRect _desktopCopyEnd;
    WALayerKitWindow *_lineAndShadowWindow;
    CALayer *_lineLayer;
    WAWindow *_desktopCopyWindow;
    BOOL _notificationCenterOpen;
    BOOL _animating;
    BOOL _animatingWithGesture;
    BOOL _animatingWithNC;
    BOOL _notificationGesturesOn;
    BOOL _gestureStartedMidAnimation;
    BOOL _gestureUsingNotificationGesture;
    BOOL _waitingForNCResponse;
    double _gestureProgressStart;
    unsigned int _phaseBeginCount;
    unsigned int _currentMotion;
    BOOL _gestureOpenWhileOpen;
    BOOL _gestureOpenWhileOpenReachedFullPosition;
    struct __IOHIDEventSystemClient *_HIDSystemClient;
    CDUnknownBlockType _gesturePerformanceBlock;
    NSObject<OS_dispatch_source> *_gestureSource;
    NSObject<OS_dispatch_queue> *_gestureQueue;
    CDUnknownBlockType _delayed_animation_block;
    NSMutableArray *_animationCompletionBlocks;
    NSObject<OS_dispatch_source> *_animationTimer;
    double _lastAnimateTime;
    double _velocity;
    double _startProgress;
    BOOL _allowBounce;
    BOOL _animateOpen;
    BOOL _animatingToEndPosition;
    BOOL _moveOnlyNeccessaryWindows;
    BOOL _weveGotMoreBounceInCalifornia;
    BOOL _menuBarIsTransparent;
    BOOL _showDesktopCopy;
}

@property(readonly) unsigned int alertWID; // @synthesize alertWID=_alertWID;
- (void).cxx_destruct;
- (void)_messageSimulateGesture:(id)arg1;
- (void)_messageOpenClose:(id)arg1;
- (void)_messageWindowList:(id)arg1;
- (void)_tellNCWeAreAnimatingOpen:(BOOL)arg1 fluid:(BOOL)arg2 startedOrDone:(BOOL)arg3 ncOriginated:(BOOL)arg4 display:(unsigned int)arg5 block:(CDUnknownBlockType)arg6;
- (void)_acceptConnection:(id)arg1;
- (void)_setupListener;
- (void)_pingNC;
- (void)_enableNotificationCloseGesture:(BOOL)arg1;
- (BOOL)_animateFluidToDone;
- (void)_gestureEndedClose:(BOOL)arg1 velocity:(double)arg2 ncOriginated:(BOOL)arg3;
- (void)_gestureProgressed:(double)arg1;
- (void)_gestureStartFromOpen:(BOOL)arg1;
- (void)_gestureStartFromClosed:(BOOL)arg1;
- (void)_animationOrderWindowsOff;
- (void)_animationOrderWindowsOn;
- (void)_animationUpdateFrame;
- (void)_setPositionImmediateAtPercent:(double)arg1;
- (void)_clipShieldWindowToCenter;
- (void)_setGlobalClip:(struct CGRect)arg1 onWindow:(unsigned int)arg2;
- (void)_finishCommon;
- (void)_finishClose:(BOOL)arg1 ncOriginated:(BOOL)arg2;
- (void)_finishOpen:(BOOL)arg1 ncOriginated:(BOOL)arg2;
- (void)_setupOpenFluid:(BOOL)arg1 fromNC:(BOOL)arg2 display:(unsigned int)arg3 readyBlock:(CDUnknownBlockType)arg4;
- (void)_setupOpenState:(unsigned int)arg1;
- (void)_gatherWindowsToTransformAndClip:(id)arg1;
- (void)_setupSpecialWindows:(id)arg1;
- (void)_closeNotificationCenter;
- (void)_openNotificationCenterOnDisplay:(unsigned int)arg1;
- (BOOL)_animateStart:(double)arg1 duration:(double)arg2 from:(double)arg3 to:(double)arg4;
- (BOOL)_makeCopyOfDesktop:(unsigned int)arg1;
- (void)_setupDesktopCopyWindow;
- (void)_setupShadowWindow;
- (void)open:(BOOL)arg1 display:(unsigned int)arg2;
- (_Bool)isFluidGesturing;
- (void)fluidGestureProgress:(id)arg1;
- (void)fluidGestureEnd:(id)arg1;
- (_Bool)fluidGestureStart:(id)arg1;
- (void)closeIfNecessaryImmediate;
- (void)closeIfNecessaryAndDoWorkAfter:(CDUnknownBlockType)arg1;
@property(readonly) BOOL isShowing;
- (void)dealloc;
- (id)init;

@end

