//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Jun  3 2014 10:55:11).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "CALayer.h"

@class Tile;

@interface DOCKLabelLayer : CALayer
{
    float _blendFrom;
    float _blendNow;
    float _blendTo;
    double _blendST;
    double _blendDur;
    Tile *_source;
    unsigned int _blending:1;
    unsigned int _needUpdate:1;
    CALayer *_cutoutLayer;
    CALayer *_textLayer;
}

+ (id)lineForString:(id)arg1 width:(unsigned int *)arg2 ascent:(double *)arg3 descent:(double *)arg4;
- (void).cxx_destruct;
- (void)_updateLabelImage:(float)arg1;
- (void)update;
- (void)scaleFactorChanged;
- (void)detach;
- (void)attach:(id)arg1;
- (id)init;

@end

