//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Jun  3 2014 10:55:11).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "DOCKStackExpandedItemLayer.h"

@class CALayer;

@interface DOCKStackFanItemLayer : DOCKStackExpandedItemLayer
{
    CALayer *_shadowLayer;
    struct CGSize _preferredSize;
}

@property(readonly, nonatomic) struct CGSize preferredTextSize; // @synthesize preferredTextSize=_preferredSize;
@property(retain, nonatomic) CALayer *shadowLayer; // @synthesize shadowLayer=_shadowLayer;
- (void).cxx_destruct;
- (id)hitTest:(struct CGPoint)arg1;
- (void)layoutSublayers;
- (void)setScaleFactor:(float)arg1;
- (void)darkenForProgress:(BOOL)arg1;
- (CDStruct_caf9bca6)previewRect;
@property(readonly, nonatomic) struct CGRect progressLayerBounds; // @dynamic progressLayerBounds;
@property(readonly, nonatomic) struct CGPoint progressLayerPosition; // @dynamic progressLayerPosition;
@property(readonly, nonatomic) struct CGRect closeBoxLayerBounds; // @dynamic closeBoxLayerBounds;
@property(readonly, nonatomic) struct CGPoint closeBoxLayerPosition; // @dynamic closeBoxLayerPosition;
@property(readonly, nonatomic) struct CGPoint shadowLayerPosition; // @dynamic shadowLayerPosition;
@property(readonly, nonatomic) struct CGRect shadowLayerBounds; // @dynamic shadowLayerBounds;
@property(readonly, nonatomic) struct CGPoint textLayerPosition; // @dynamic textLayerPosition;
@property(readonly, nonatomic) struct CGRect textLayerBounds; // @dynamic textLayerBounds;
@property(readonly, nonatomic) id textBackgroundColor; // @dynamic textBackgroundColor;
@property(readonly, nonatomic) struct CGPoint textBackgroundLayerPosition; // @dynamic textBackgroundLayerPosition;
@property(readonly, nonatomic) struct CGRect textBackgroundLayerBounds; // @dynamic textBackgroundLayerBounds;
@property(readonly, nonatomic) struct CGPoint imageLayerPosition; // @dynamic imageLayerPosition;
@property(readonly, nonatomic) struct CGRect imageLayerBounds; // @dynamic imageLayerBounds;
- (id)initWithScaleFactor:(float)arg1;

@end

