//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Jun  3 2014 10:55:11).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "CALayer.h"

@interface DOCKFloorLayer : CALayer
{
    CALayer *_separatorLayer;
    CALayer *_glassLayer;
    struct CGRect _previousFrame;
    int _orientation;
    double _separatorPosition;
    unsigned int _iconOffset;
    int _mirrorLevel;
    unsigned int _lastDisplay;
    _Bool _dontEverShowMirror;
    _Bool _mirrorOff;
    _Bool _mirrorOverride;
    _Bool _mirrorOn;
}

@property(readonly, nonatomic) _Bool mirrorOn; // @synthesize mirrorOn=_mirrorOn;
- (void).cxx_destruct;
- (void)_mirrorStateChange:(_Bool)arg1 previous:(_Bool)arg2;
- (void)layoutSublayers;
@property(nonatomic) int mirrorLevel;
@property(nonatomic) _Bool overrideMirror;
- (void)forceMirrorUpdate;
- (void)turnMirrorOff;
- (void)accelerationChanged;
- (void)displayReconfig;
- (void)scaleFactorChanged;
- (void)updateFrame:(struct CGRect)arg1 iconOffset:(unsigned int)arg2;
- (void)setGlobalSeparatorPosition:(double)arg1;
- (void)setOrientation:(int)arg1;
- (id)separatorResourceForOrientation:(int)arg1;
- (id)initWithOrientation:(int)arg1;

@end

