//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Jun  3 2014 10:55:11).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "CALayer.h"

@class NSString;

@interface DOCKTileLabelLayer : CALayer
{
    struct CGRect _normalizedBounds;
    struct CGPoint _normalizedCenter;
    CALayer *_textLayer;
}

- (void).cxx_destruct;
@property(readonly, nonatomic) NSString *label; // @dynamic label;
- (id)initWithLabel:(id)arg1 normalizedBounds:(struct CGRect)arg2 normalizedCenter:(struct CGPoint)arg3;

@end

