//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Jun  3 2014 10:55:11).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "CALayer.h"

#import "ECEventHandling.h"

@class ECShadowTextLayer, NSString;

@interface ECButtonLayer : CALayer <ECEventHandling>
{
    int _buttonType;
    CALayer *_backgroundLayer;
    ECShadowTextLayer *_titleLayer;
    CDUnknownBlockType _actionBlock;
    float _scaleFactor;
    BOOL _inButton;
}

@property(nonatomic) float scaleFactor; // @synthesize scaleFactor=_scaleFactor;
@property(copy, nonatomic) CDUnknownBlockType actionBlock; // @synthesize actionBlock=_actionBlock;
- (void).cxx_destruct;
- (BOOL)leftMouseUp:(id)arg1;
- (BOOL)leftMouseDragged:(id)arg1;
- (BOOL)leftMouseDown:(id)arg1;
- (struct CGSize)preferredFrameSize;
- (void)layout;
@property(retain, nonatomic) NSString *title; // @dynamic title;
- (id)initWithTitle:(id)arg1 buttonType:(int)arg2 scaleFactor:(float)arg3 actionBlock:(CDUnknownBlockType)arg4;

@end

