//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Jun  3 2014 10:55:11).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "CALayer.h"

#import "ECCoverFlowItem.h"
#import "ECEventHandling.h"

@class ECCoverFlowLabelLayer;

@interface ECCoverFlowItemLayer : CALayer <ECCoverFlowItem, ECEventHandling>
{
    CALayer *_transformLayer;
    CALayer *_imageLayer;
    ECCoverFlowLabelLayer *_labelLayer;
    CALayer *_highlightLayer;
    float _scaleFactor;
    unsigned int _highlighted:1;
    unsigned int _needsUpdate:1;
}

@property(nonatomic) float scaleFactor; // @synthesize scaleFactor=_scaleFactor;
@property(nonatomic) BOOL needsUpdate; // @synthesize needsUpdate=_needsUpdate;
@property(nonatomic) BOOL highlighted; // @synthesize highlighted=_highlighted;
@property(retain, nonatomic) CALayer *highlightLayer; // @synthesize highlightLayer=_highlightLayer;
@property(retain, nonatomic) ECCoverFlowLabelLayer *labelLayer; // @synthesize labelLayer=_labelLayer;
@property(retain, nonatomic) CALayer *imageLayer; // @synthesize imageLayer=_imageLayer;
@property(retain, nonatomic) CALayer *transformLayer; // @synthesize transformLayer=_transformLayer;
- (void).cxx_destruct;
- (id)maskLayerForHighlight;
- (void)layout;
- (struct CGRect)frameForHighlight;
- (void)setContentFromDataSource:(id)arg1 atIndex:(unsigned long long)arg2 withItemInfo:(id)arg3;
- (id)initWithScaleFactor:(float)arg1;

@end

