//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Jun  3 2014 10:55:11).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "ECPage.h"

@interface ECSBSearchPage : ECPage
{
    id <ECSBSearchDelegate><ECSBSearchDataSource> _handler;
    float _scaleFactor;
}

@property(nonatomic) float scaleFactor; // @synthesize scaleFactor=_scaleFactor;
@property(retain, nonatomic) id <ECSBSearchDelegate><ECSBSearchDataSource> handler; // @synthesize handler=_handler;
- (void).cxx_destruct;
- (id)offIndicatorImage;
- (id)onIndicatorImage;

@end

