//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Jun  3 2014 10:55:11).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "CIFilter.h"

@class CIImage, CIVector, NSNumber;

@interface GradientBlurFilter : CIFilter
{
    CIImage *inputImage;
    CIVector *inputExtent;
    NSNumber *inputRadius0;
    NSNumber *inputRadius1;
}

- (void).cxx_destruct;
- (id)outputImage;
- (struct CGRect)regionOf:(int)arg1 forRect:(struct CGRect)arg2 userInfo:(id)arg3;

@end

